<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Agenda.php');
	include_once(__DIR__ . '/Agenda_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Agenda');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Agenda';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Agenda`.`Id`" => "Id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '     -     ', `Funcoes1`.`Nome`), '') /* Responsavel */" => "Responsavel",
		"if(`Agenda`.`Data`,date_format(`Agenda`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Agenda`.`Hora`" => "Hora",
		"`Agenda`.`Evento`" => "Evento",
		"`Agenda`.`Local`" => "Local",
		"`Agenda`.`Obs`" => "Obs",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Agenda`.`Id`',
		2 => 2,
		3 => '`Agenda`.`Data`',
		4 => '`Agenda`.`Hora`',
		5 => 5,
		6 => 6,
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Agenda`.`Id`" => "Id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '     -     ', `Funcoes1`.`Nome`), '') /* Responsavel */" => "Responsavel",
		"if(`Agenda`.`Data`,date_format(`Agenda`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Agenda`.`Hora`" => "Hora",
		"`Agenda`.`Evento`" => "Evento",
		"`Agenda`.`Local`" => "Local",
		"`Agenda`.`Obs`" => "Obs",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Agenda`.`Id`" => "Id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '     -     ', `Funcoes1`.`Nome`), '') /* Responsavel */" => "Responsavel",
		"`Agenda`.`Data`" => "Data",
		"`Agenda`.`Hora`" => "Hora",
		"`Agenda`.`Evento`" => "Evento",
		"`Agenda`.`Local`" => "Local",
		"`Agenda`.`Obs`" => "Obs",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Agenda`.`Id`" => "Id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '     -     ', `Funcoes1`.`Nome`), '') /* Responsavel */" => "Responsavel",
		"if(`Agenda`.`Data`,date_format(`Agenda`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Agenda`.`Hora`" => "Hora",
		"`Agenda`.`Evento`" => "Evento",
		"`Agenda`.`Local`" => "Local",
		"`Agenda`.`Obs`" => "Obs",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Responsavel' => 'Responsavel', ];

	$x->QueryFrom = "`Agenda` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Agenda`.`Responsavel` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores1`.`Funcao` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Agenda_view.php';
	$x->TableTitle = 'Agenda';
	$x->TableIcon = 'resources/table_icons/book_addresses.png';
	$x->PrimaryKey = '`Agenda`.`Id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Responsavel', 'Data', 'Hora', 'Evento', 'Local', ];
	$x->ColFieldName = ['Responsavel', 'Data', 'Hora', 'Evento', 'Local', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Agenda_templateTV.html';
	$x->SelectedTemplate = 'templates/Agenda_templateTVS.html';
	$x->TemplateDV = 'templates/Agenda_templateDV.html';
	$x->TemplateDVP = 'templates/Agenda_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Agenda_init
	$render = true;
	if(function_exists('Agenda_init')) {
		$args = [];
		$render = Agenda_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Agenda_header
	$headerCode = '';
	if(function_exists('Agenda_header')) {
		$args = [];
		$headerCode = Agenda_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Agenda_footer
	$footerCode = '';
	if(function_exists('Agenda_footer')) {
		$args = [];
		$footerCode = Agenda_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
