<?php

// Data functions (insert, update, delete, form) for table Agenda

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Agenda_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Agenda');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Responsavel' => Request::lookup('Responsavel', ''),
		'Data' => Request::dateComponents('Data', ''),
		'Hora' => Request::val('Hora', ''),
		'Evento' => Request::val('Evento', ''),
		'Local' => Request::val('Local', ''),
		'Obs' => br2nl(Request::val('Obs', '')),
	];

	if($data['Responsavel'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Responsavel': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Data'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Data': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Evento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Evento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Agenda_before_insert
	if(function_exists('Agenda_before_insert')) {
		$args = [];
		if(!Agenda_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Agenda', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Agenda', $recID, calculated_fields()['Agenda']);

	// hook: Agenda_after_insert
	if(function_exists('Agenda_after_insert')) {
		$res = sql("SELECT * FROM `Agenda` WHERE `Id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Agenda_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Agenda', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Agenda_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Agenda_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Agenda_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Agenda', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Agenda_before_delete
	if(function_exists('Agenda_before_delete')) {
		$args = [];
		if(!Agenda_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Agenda` WHERE `Id`='{$selected_id}'", $eo);

	// hook: Agenda_after_delete
	if(function_exists('Agenda_after_delete')) {
		$args = [];
		Agenda_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Agenda' AND `pkValue`='{$selected_id}'", $eo);
}

function Agenda_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Agenda', $selected_id, 'edit')) return false;

	$data = [
		'Responsavel' => Request::lookup('Responsavel', ''),
		'Data' => Request::dateComponents('Data', ''),
		'Hora' => Request::val('Hora', ''),
		'Evento' => Request::val('Evento', ''),
		'Local' => Request::val('Local', ''),
		'Obs' => br2nl(Request::val('Obs', '')),
	];

	if($data['Responsavel'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Responsavel': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Data'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Data': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Evento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Evento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Agenda', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Agenda_before_update
	if(function_exists('Agenda_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Agenda_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Agenda', 
		backtick_keys_once($set), 
		['`Id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Agenda_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Agenda', $data['selectedID'], calculated_fields()['Agenda']);

	// hook: Agenda_after_update
	if(function_exists('Agenda_after_update')) {
		$res = sql("SELECT * FROM `Agenda` WHERE `Id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['Id'];
		$args = ['old_data' => $old_data];
		if(!Agenda_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Agenda', $selected_id);
}

function Agenda_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Agenda');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Agenda', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Agenda', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Agenda', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Responsavel = Request::val('filterer_Responsavel');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Responsavel
	$combo_Responsavel = new DataCombo;
	// combobox: Data
	$combo_Data = new DateCombo;
	$combo_Data->DateFormat = "dmy";
	$combo_Data->MinYear = defined('Agenda.Data.MinYear') ? constant('Agenda.Data.MinYear') : 1900;
	$combo_Data->MaxYear = defined('Agenda.Data.MaxYear') ? constant('Agenda.Data.MaxYear') : 2100;
	$combo_Data->DefaultDate = parseMySQLDate('', '');
	$combo_Data->MonthNames = $Translation['month names'];
	$combo_Data->NamePrefix = 'Data';

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Agenda` WHERE `Id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Agenda_view.php', false);
		}
		$combo_Responsavel->SelectedData = $row['Responsavel'];
		$combo_Data->DefaultDate = $row['Data'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Responsavel->SelectedData = $filterer_Responsavel;
	}
	$combo_Responsavel->HTML = '<span id="Responsavel-container' . $rnd1 . '"></span><input type="hidden" name="Responsavel" id="Responsavel' . $rnd1 . '" value="' . html_attr($combo_Responsavel->SelectedData) . '">';
	$combo_Responsavel->MatchText = '<span id="Responsavel-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Responsavel" id="Responsavel' . $rnd1 . '" value="' . html_attr($combo_Responsavel->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Responsavel__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Responsavel'] : htmlspecialchars($filterer_Responsavel, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Responsavel_reload__RAND__) == 'function') Responsavel_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Responsavel_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Responsavel-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Agenda', f: 'Responsavel' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Responsavel"]').val(resp.results[0].id);
							$j('[id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


							if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Agenda', f: 'Responsavel' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Responsavel__RAND__.value = e.added.id;
				AppGini.current_Responsavel__RAND__.text = e.added.text;
				$j('[name="Responsavel"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


				if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
			});

			if(!$j("#Responsavel-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Agenda', f: 'Responsavel' },
					success: function(resp) {
						$j('[name="Responsavel"]').val(resp.results[0].id);
						$j('[id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

						if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Agenda', f: 'Responsavel' },
				success: function(resp) {
					$j('[id=Responsavel-container__RAND__], [id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

					if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Agenda_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Agenda_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Agenda_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Agenda_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Agenda_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Responsavel').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Responsavel_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Data').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DataDay, #DataMonth, #DataYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Hora').replaceWith('<div class=\"form-control-static\" id=\"Hora\">' + (jQuery('#Hora').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Evento').replaceWith('<div class=\"form-control-static\" id=\"Evento\">' + (jQuery('#Evento').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Local').replaceWith('');\n";
		$jsReadOnly .= "\tjQuery('#Local, #Local-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#Obs').replaceWith('<div class=\"form-control-static\" id=\"Obs\">' + (jQuery('#Obs').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('#Hora').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: false, showInputs: false, disableFocus: true, minuteStep: 5 });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Responsavel)%%>', $combo_Responsavel->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Responsavel)%%>', $combo_Responsavel->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Responsavel)%%>', urlencode($combo_Responsavel->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(Data)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_Data->GetHTML(true) . '</div>' : 
			$combo_Data->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Data)%%>', $combo_Data->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Responsavel' => ['Colaboradores', 'Responsavel'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(Id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Responsavel)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Data)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Hora)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Evento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Local)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Obs)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(Id)%%>', safe_html($urow['Id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode($urow['Id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Responsavel)%%>', safe_html($urow['Responsavel']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Responsavel)%%>', html_attr($row['Responsavel']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsavel)%%>', urlencode($urow['Responsavel']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Data)%%>', app_datetime($row['Data']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data)%%>', urlencode(app_datetime($urow['Data'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Hora)%%>', safe_html($urow['Hora']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Hora)%%>', html_attr($row['Hora']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora)%%>', urlencode($urow['Hora']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Evento)%%>', safe_html($urow['Evento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Evento)%%>', html_attr($row['Evento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Evento)%%>', urlencode($urow['Evento']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Local)%%>', html_attr($row['Local']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Local)%%>', urlencode($urow['Local']), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAP(Local)%%>', get_embed('googlemap', $urow['Local'], '480', '360'), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAPTHUMB(Local)%%>', thisOr(get_embed('googlemap', $urow['Local'], '480', '360', 'thumbnail_url'), 'blank.gif'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', safe_html($urow['Obs'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode($urow['Obs']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(Id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Responsavel)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsavel)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Data)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Hora)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Hora)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Evento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Evento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Local)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Local)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAP(Local)%%>', '', $templateCode);
		$templateCode = str_replace('<%%GOOGLEMAPTHUMB(Local)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Agenda');
	if($hasSelectedId) {
		$jdata = get_joined_record('Agenda', $selectedId);
		if($jdata === false) $jdata = get_defaults('Agenda');
		$rdata = $row;
	}
	$templateCode .= loadView('Agenda-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Agenda_dv
	if(function_exists('Agenda_dv')) {
		$args = [];
		Agenda_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}