<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list, applicable only for radio lookups
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
	ut: 0 (default) returns all results, 1 returns unique texts (useful only if we don't care about ids, only text)
	json: 0 (default) returns HTML output for radio lookups, 1 forces json results for all including radio lookups
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	// drop-downs config
	$lookups = [
		'Pessoas' => [
			'Estado' => [
				'parent_table' => 'Estados',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Estados`.`Nome`) || CHAR_LENGTH(`Estados`.`Sigla`), CONCAT_WS(\'\', `Estados`.`Nome`, \'    -    \', `Estados`.`Sigla`), \'\')',
				'parent_from' => '`Estados` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Cidade' => [
				'parent_table' => 'Municipios',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Municipios`.`Nome`',
				'parent_from' => '`Municipios` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Municipios`.`Estado` ',
				'filterers' => ['Estado' => 'Estado'],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Bairro' => [
				'parent_table' => 'Bairro',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Bairro`.`Nome`',
				'parent_from' => '`Bairro` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Bairro`.`Cidade` ',
				'filterers' => ['Cidade' => 'Cidade'],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'profissao' => [
				'parent_table' => 'Profissoes',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Profissoes`.`Profissao`) || CHAR_LENGTH(`Profissoes`.`Seguimento`), CONCAT_WS(\'\', `Profissoes`.`Profissao`, \'   -   \', `Profissoes`.`Seguimento`), \'\')',
				'parent_from' => '`Profissoes` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Eleitores' => [
			'Nome' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Pessoas`.`Nome`',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Estado' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS(\'\',   `Estados1`.`Nome`, \'    -    \', `Estados1`.`Sigla`), \'\')',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Cidade' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS(\'\',   `Municipios1`.`Nome`), \'\')',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Bairro' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS(\'\',   `Bairro1`.`Nome`), \'\')',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Zona' => [
				'parent_table' => 'Zona',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Zona`.`Numero`',
				'parent_from' => '`Zona` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Zona`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona`.`Municipio` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'secao' => [
				'parent_table' => 'Secao',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Secao`.`Numero`), CONCAT_WS(\'\', `Secao`.`Numero`, \'    -    \'), \'\')',
				'parent_from' => '`Secao` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Secao`.`Cidade` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona1`.`Municipio` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Secao`.`Bairro` LEFT JOIN `Zona` as Zona2 ON `Zona2`.`id`=`Secao`.`Zona` ',
				'filterers' => ['Zona' => 'Cidade'],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'local' => [
				'parent_table' => 'Secao',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Secao`.`Local`',
				'parent_from' => '`Secao` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Secao`.`Cidade` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona1`.`Municipio` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Secao`.`Bairro` LEFT JOIN `Zona` as Zona2 ON `Zona2`.`id`=`Secao`.`Zona` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'partido' => [
				'parent_table' => 'Partidos',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Partidos`.`Sigla`',
				'parent_from' => '`Partidos` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'indicacao' => [
				'parent_table' => 'Colaboradores',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Colaboradores`.`Nome`) || CHAR_LENGTH(`Colaboradores`.`Funcao`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\'), \'    -    \', IF(    CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS(\'\',   `Funcoes1`.`Nome`), \'\')), \'\')',
				'parent_from' => '`Colaboradores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores`.`Nome` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Colaboradores`.`Profissao` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores`.`Funcao` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Colaboradores`.`Responsavel` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes2 ON `Funcoes2`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Candidatos' => [
			'Partido' => [
				'parent_table' => 'Partidos',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Partidos`.`Sigla`) || CHAR_LENGTH(`Partidos`.`Numero`), CONCAT_WS(\'\', `Partidos`.`Sigla`, \'   -   \', `Partidos`.`Numero`), \'\')',
				'parent_from' => '`Partidos` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Nome' => [
				'parent_table' => 'Eleitores',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\')',
				'parent_from' => '`Eleitores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Eleitores`.`Nome` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Eleitores`.`Zona` LEFT JOIN `Secao` as Secao1 ON `Secao1`.`id`=`Eleitores`.`secao` LEFT JOIN `Partidos` as Partidos1 ON `Partidos1`.`id`=`Eleitores`.`partido` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Eleitores`.`indicacao` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas1`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas1`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => ['Partido' => 'partido'],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Colaboradores' => [
			'Nome' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Pessoas`.`Nome`',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Bairro' => [
				'parent_table' => 'Pessoas',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS(\'\',   `Bairro1`.`Nome`), \'\')',
				'parent_from' => '`Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Profissao' => [
				'parent_table' => 'Profissoes',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Profissoes`.`Profissao`) || CHAR_LENGTH(`Profissoes`.`Seguimento`), CONCAT_WS(\'\', `Profissoes`.`Profissao`, \'   -   \', `Profissoes`.`Seguimento`), \'\')',
				'parent_from' => '`Profissoes` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
			'Funcao' => [
				'parent_table' => 'Funcoes',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Funcoes`.`Nome`',
				'parent_from' => '`Funcoes` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Responsavel' => [
				'parent_table' => 'Colaboradores',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Colaboradores`.`Nome`) || CHAR_LENGTH(`Colaboradores`.`Funcao`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\'), \'   -   \', IF(    CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS(\'\',   `Funcoes1`.`Nome`), \'\')), \'\')',
				'parent_from' => '`Colaboradores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores`.`Nome` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Colaboradores`.`Profissao` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores`.`Funcao` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Colaboradores`.`Responsavel` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes2 ON `Funcoes2`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false,
			],
		],
		'Partidos' => [
		],
		'Profissoes' => [
		],
		'Funcoes' => [
		],
		'Estados' => [
		],
		'Municipios' => [
			'Estado' => [
				'parent_table' => 'Estados',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Estados`.`Nome`) || CHAR_LENGTH(`Estados`.`Sigla`), CONCAT_WS(\'\', `Estados`.`Nome`, \'    -    \', `Estados`.`Sigla`), \'\')',
				'parent_from' => '`Estados` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Bairro' => [
			'Cidade' => [
				'parent_table' => 'Municipios',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Municipios`.`Nome`',
				'parent_from' => '`Municipios` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Municipios`.`Estado` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Zona' => [
			'Estado' => [
				'parent_table' => 'Estados',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Estados`.`Nome`) || CHAR_LENGTH(`Estados`.`Sigla`), CONCAT_WS(\'\', `Estados`.`Nome`, \'    -    \', `Estados`.`Sigla`), \'\')',
				'parent_from' => '`Estados` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Municipio' => [
				'parent_table' => 'Municipios',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Municipios`.`Nome`',
				'parent_from' => '`Municipios` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Municipios`.`Estado` ',
				'filterers' => ['Estado' => 'Estado'],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Secao' => [
			'Cidade' => [
				'parent_table' => 'Zona',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS(\'\',   `Municipios1`.`Nome`), \'\')',
				'parent_from' => '`Zona` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Zona`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona`.`Municipio` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Bairro' => [
				'parent_table' => 'Bairro',
				'parent_pk_field' => 'Id',
				'parent_caption' => '`Bairro`.`Nome`',
				'parent_from' => '`Bairro` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Bairro`.`Cidade` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Zona' => [
				'parent_table' => 'Zona',
				'parent_pk_field' => 'id',
				'parent_caption' => '`Zona`.`Numero`',
				'parent_from' => '`Zona` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Zona`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona`.`Municipio` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Agenda' => [
			'Responsavel' => [
				'parent_table' => 'Colaboradores',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Colaboradores`.`Nome`) || CHAR_LENGTH(`Colaboradores`.`Funcao`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\'), \'     -     \', IF(    CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS(\'\',   `Funcoes1`.`Nome`), \'\')), \'\')',
				'parent_from' => '`Colaboradores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores`.`Nome` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Colaboradores`.`Profissao` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores`.`Funcao` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Colaboradores`.`Responsavel` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes2 ON `Funcoes2`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
		'Atendimentos' => [
			'Colaborador' => [
				'parent_table' => 'Colaboradores',
				'parent_pk_field' => 'Id',
				'parent_caption' => 'IF(CHAR_LENGTH(`Colaboradores`.`Nome`) || CHAR_LENGTH(`Colaboradores`.`Funcao`), CONCAT_WS(\'\', IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\'), \'    -    \', IF(    CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS(\'\',   `Funcoes1`.`Nome`), \'\')), \'\')',
				'parent_from' => '`Colaboradores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores`.`Nome` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Colaboradores`.`Profissao` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores`.`Funcao` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Colaboradores`.`Responsavel` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes2 ON `Funcoes2`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
			'Eleitor' => [
				'parent_table' => 'Eleitores',
				'parent_pk_field' => 'id',
				'parent_caption' => 'IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS(\'\',   `Pessoas1`.`Nome`), \'\')',
				'parent_from' => '`Eleitores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Eleitores`.`Nome` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Eleitores`.`Zona` LEFT JOIN `Secao` as Secao1 ON `Secao1`.`id`=`Eleitores`.`secao` LEFT JOIN `Partidos` as Partidos1 ON `Partidos1`.`id`=`Eleitores`.`partido` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Eleitores`.`indicacao` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas1`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas1`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ',
				'filterers' => [],
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true,
			],
		],
	];

	// XSS prevention
	$xss = new CI_Input(datalist_db_encoding);

	// receive and verify user input
	$table_name = Request::val('t');
	$field_name = Request::val('f');
	$search_id = makeSafe(from_utf8(Request::val('id')));
	$selected_text = from_utf8(Request::val('text'));
	$returnOptions = (Request::val('o') == 1 ? true : false);
	$page = intval(Request::val('p'));
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8(Request::val('s')));
	$uniqueText = Request::val('ut') ? true : false;
	$forceJson = Request::val('json') ? true : false;

	$res = null;

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm['access'] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = [];

	// search term provided?
	if($search_term) {
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])) {
		foreach($field['filterers'] as $filterer => $filterer_parent) {
			if($get = Request::val("filterer_{$filterer}", false))
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']) {
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id) {
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	$where = '';
	if(count($wheres)) {
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']) {
		$qm = []; $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)) {
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)) {
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where) {
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		} elseif($custom_where) {
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		} else {
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = [];
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])) {
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		} else {
			$count_query = '';
		}
	} else {
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id) {
		$combo->SelectedData = $search_id;
	} elseif($selected_text) {
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2 && !$forceJson) {
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions) {
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		} else {
			?>
				<span class="match-text" id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>">
			<?php
		}
	} else {
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)) {
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = [];

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text) {
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = ['id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text))];
		} else {
			/*
			 * in case we have a search term, show matches starting with it first,
			 * followed by those containing it.
			 * build a UNION query for that purpose
			 */
			if($search_term) {
				$query2 = $combo->Query;
				$query1 = str_replace(" like '%{$search_term}%'", " like '{$search_term}%'", $query2);
				$combo->Query = "({$query1}) UNION ({$query2})";
			}

			$eo = ['silentErrors' => true];

			/* 
			if unique text (ut=1), we don't care about IDs and can group by text.
			initiate array to hold unique texts.
			*/
			if($uniqueText) $uniqueArr = [];

			$res = sql($combo->Query, $eo);
			if($res) while($row = db_fetch_row($res)) {
				// Add initial empty value if field is not required and this is the first page of results
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']) {
					$prepared_data[] = ['id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>")];
				}

				// if unique text, add to uniqueArr and skip if already exists
				if($uniqueText) {
					if(in_array($row[1], $uniqueArr)) continue;
					$uniqueArr[] = $row[1];
				}

				$prepared_data[] = ['id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1]))];
			}
		}

		if(empty($prepared_data)) { $prepared_data[] = ['id' => '', 'text' => to_utf8($Translation['No matches found!'])]; }

		echo json_encode([
			'results' => $prepared_data,
			'more' => ($res && db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3),
		]);
	}

