<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Atendimentos.php');
	include_once(__DIR__ . '/Atendimentos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Atendimentos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Atendimentos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Atendimentos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Colaborador */" => "Colaborador",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`), '') /* Eleitor */" => "Eleitor",
		"if(`Atendimentos`.`Data`,date_format(`Atendimentos`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Atendimentos`.`Situacao`" => "Situacao",
		"`Atendimentos`.`Pedido`" => "Pedido",
		"`Atendimentos`.`Pendencias`" => "Pendencias",
		"`Atendimentos`.`Solucao`" => "Solucao",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Atendimentos`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Atendimentos`.`Data`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Atendimentos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Colaborador */" => "Colaborador",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`), '') /* Eleitor */" => "Eleitor",
		"if(`Atendimentos`.`Data`,date_format(`Atendimentos`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Atendimentos`.`Situacao`" => "Situacao",
		"`Atendimentos`.`Pedido`" => "Pedido",
		"`Atendimentos`.`Pendencias`" => "Pendencias",
		"`Atendimentos`.`Solucao`" => "Solucao",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Atendimentos`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Colaborador */" => "Colaborador",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`), '') /* Eleitor */" => "Eleitor",
		"`Atendimentos`.`Data`" => "Data",
		"`Atendimentos`.`Situacao`" => "Situa&#231;&#227;o",
		"`Atendimentos`.`Pedido`" => "Descri&#231;&#227;o dos pedidos",
		"`Atendimentos`.`Pendencias`" => "Pend&#234;ncias",
		"`Atendimentos`.`Solucao`" => "Solu&#231;&#227;o",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Atendimentos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Colaborador */" => "Colaborador",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`), '') /* Eleitor */" => "Eleitor",
		"if(`Atendimentos`.`Data`,date_format(`Atendimentos`.`Data`,'%d/%m/%Y'),'')" => "Data",
		"`Atendimentos`.`Situacao`" => "Situacao",
		"`Atendimentos`.`Pedido`" => "Pedido",
		"`Atendimentos`.`Pendencias`" => "Pendencias",
		"`Atendimentos`.`Solucao`" => "Solucao",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Colaborador' => 'Colaborador', 'Eleitor' => 'Eleitor', ];

	$x->QueryFrom = "`Atendimentos` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Atendimentos`.`Colaborador` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Eleitores` as Eleitores1 ON `Eleitores1`.`id`=`Atendimentos`.`Eleitor` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Eleitores1`.`Nome` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Atendimentos_view.php';
	$x->TableTitle = 'Atendimentos';
	$x->TableIcon = 'resources/table_icons/horoscopes.png';
	$x->PrimaryKey = '`Atendimentos`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Colaborador', 'Eleitor', 'Data', 'Situa&#231;&#227;o', ];
	$x->ColFieldName = ['Colaborador', 'Eleitor', 'Data', 'Situacao', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Atendimentos_templateTV.html';
	$x->SelectedTemplate = 'templates/Atendimentos_templateTVS.html';
	$x->TemplateDV = 'templates/Atendimentos_templateDV.html';
	$x->TemplateDVP = 'templates/Atendimentos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Atendimentos_init
	$render = true;
	if(function_exists('Atendimentos_init')) {
		$args = [];
		$render = Atendimentos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Atendimentos_header
	$headerCode = '';
	if(function_exists('Atendimentos_header')) {
		$args = [];
		$headerCode = Atendimentos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Atendimentos_footer
	$footerCode = '';
	if(function_exists('Atendimentos_footer')) {
		$args = [];
		$footerCode = Atendimentos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
