<?php

// Data functions (insert, update, delete, form) for table Candidatos

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Candidatos_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Candidatos');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Partido' => Request::lookup('Partido', ''),
		'Nome' => Request::lookup('Nome', ''),
		'Numero' => Request::val('Numero', ''),
		'Cargo' => Request::val('Cargo', ''),
		'Midias' => Request::val('Midias', ''),
	];

	if($data['Partido'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Partido': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Candidatos_before_insert
	if(function_exists('Candidatos_before_insert')) {
		$args = [];
		if(!Candidatos_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Candidatos', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Candidatos', $recID, calculated_fields()['Candidatos']);

	// hook: Candidatos_after_insert
	if(function_exists('Candidatos_after_insert')) {
		$res = sql("SELECT * FROM `Candidatos` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Candidatos_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Candidatos', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Candidatos_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Candidatos_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Candidatos_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Candidatos', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Candidatos_before_delete
	if(function_exists('Candidatos_before_delete')) {
		$args = [];
		if(!Candidatos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `Candidatos` WHERE `id`='{$selected_id}'", $eo);

	// hook: Candidatos_after_delete
	if(function_exists('Candidatos_after_delete')) {
		$args = [];
		Candidatos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Candidatos' AND `pkValue`='{$selected_id}'", $eo);
}

function Candidatos_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Candidatos', $selected_id, 'edit')) return false;

	$data = [
		'Partido' => Request::lookup('Partido', ''),
		'Nome' => Request::lookup('Nome', ''),
		'Numero' => Request::val('Numero', ''),
		'Cargo' => Request::val('Cargo', ''),
		'Midias' => Request::val('Midias', ''),
	];

	if($data['Partido'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Partido': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Candidatos', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Candidatos_before_update
	if(function_exists('Candidatos_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Candidatos_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Candidatos', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Candidatos_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Candidatos', $data['selectedID'], calculated_fields()['Candidatos']);

	// hook: Candidatos_after_update
	if(function_exists('Candidatos_after_update')) {
		$res = sql("SELECT * FROM `Candidatos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Candidatos_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Candidatos', $selected_id);
}

function Candidatos_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Candidatos');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Candidatos', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Candidatos', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Candidatos', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Partido = Request::val('filterer_Partido');
	$filterer_Nome = Request::val('filterer_Nome');

	// populate filterers, starting from children to grand-parents
	if($filterer_Nome && !$filterer_Partido) $filterer_Partido = sqlValue("select partido from Eleitores where id='" . makeSafe($filterer_Nome) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Partido
	$combo_Partido = new DataCombo;
	// combobox: Nome, filterable by: Partido
	$combo_Nome = new DataCombo;
	// combobox: Cargo
	$combo_Cargo = new Combo;
	$combo_Cargo->ListType = 0;
	$combo_Cargo->MultipleSeparator = ', ';
	$combo_Cargo->ListBoxHeight = 10;
	$combo_Cargo->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Candidatos.Cargo.csv')) {
		$Cargo_data = addslashes(implode('', @file(__DIR__ . '/hooks/Candidatos.Cargo.csv')));
		$combo_Cargo->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Cargo_data))));
		$combo_Cargo->ListData = $combo_Cargo->ListItem;
	} else {
		$combo_Cargo->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Selecione;;Presidente;;Governador;;Prefeito;;Vice-Prefeito;;Vereador;;"))));
		$combo_Cargo->ListData = $combo_Cargo->ListItem;
	}
	$combo_Cargo->SelectName = 'Cargo';

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Candidatos` WHERE `id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Candidatos_view.php', false);
		}
		$combo_Partido->SelectedData = $row['Partido'];
		$combo_Nome->SelectedData = $row['Nome'];
		$combo_Cargo->SelectedData = $row['Cargo'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Partido->SelectedData = $filterer_Partido;
		$combo_Nome->SelectedData = $filterer_Nome;
		$combo_Cargo->SelectedText = (isset($filterField[1]) && $filterField[1] == '5' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_Partido->HTML = '<span id="Partido-container' . $rnd1 . '"></span><input type="hidden" name="Partido" id="Partido' . $rnd1 . '" value="' . html_attr($combo_Partido->SelectedData) . '">';
	$combo_Partido->MatchText = '<span id="Partido-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Partido" id="Partido' . $rnd1 . '" value="' . html_attr($combo_Partido->SelectedData) . '">';
	$combo_Nome->HTML = '<span id="Nome-container' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Nome->MatchText = '<span id="Nome-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Cargo->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Partido__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Partido'] : htmlspecialchars($filterer_Partido, ENT_QUOTES)); ?>"};
		AppGini.current_Nome__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Nome'] : htmlspecialchars($filterer_Nome, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Partido_reload__RAND__) == 'function') Partido_reload__RAND__();
				<?php echo (!$allowUpdate || $dvprint ? 'if(typeof(Nome_reload__RAND__) == \'function\') Nome_reload__RAND__(AppGini.current_Partido__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Partido_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Partido-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Partido__RAND__.value, t: 'Candidatos', f: 'Partido' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Partido"]').val(resp.results[0].id);
							$j('[id=Partido-container-readonly__RAND__]').html('<span class="match-text" id="Partido-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

						if(typeof(Nome_reload__RAND__) == 'function') Nome_reload__RAND__(AppGini.current_Partido__RAND__.value);

							if(typeof(Partido_update_autofills__RAND__) == 'function') Partido_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Candidatos', f: 'Partido' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Partido__RAND__.value = e.added.id;
				AppGini.current_Partido__RAND__.text = e.added.text;
				$j('[name="Partido"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

						if(typeof(Nome_reload__RAND__) == 'function') Nome_reload__RAND__(AppGini.current_Partido__RAND__.value);

				if(typeof(Partido_update_autofills__RAND__) == 'function') Partido_update_autofills__RAND__();
			});

			if(!$j("#Partido-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Partido__RAND__.value, t: 'Candidatos', f: 'Partido' },
					success: function(resp) {
						$j('[name="Partido"]').val(resp.results[0].id);
						$j('[id=Partido-container-readonly__RAND__]').html('<span class="match-text" id="Partido-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

						if(typeof(Partido_update_autofills__RAND__) == 'function') Partido_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Partido__RAND__.value, t: 'Candidatos', f: 'Partido' },
				success: function(resp) {
					$j('[id=Partido-container__RAND__], [id=Partido-container-readonly__RAND__]').html('<span class="match-text" id="Partido-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

					if(typeof(Partido_update_autofills__RAND__) == 'function') Partido_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Nome_reload__RAND__(filterer_Partido) {
		<?php if($fieldsAreEditable) { ?>

			$j("#Nome-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_Partido: filterer_Partido, id: AppGini.current_Nome__RAND__.value, t: 'Candidatos', f: 'Nome' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Nome"]').val(resp.results[0].id);
							$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Eleitores_view_parent]').hide(); } else { $j('.btn[id=Eleitores_view_parent]').show(); }


							if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_Partido: filterer_Partido, s: term, p: page, t: 'Candidatos', f: 'Nome' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Nome__RAND__.value = e.added.id;
				AppGini.current_Nome__RAND__.text = e.added.text;
				$j('[name="Nome"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Eleitores_view_parent]').hide(); } else { $j('.btn[id=Eleitores_view_parent]').show(); }


				if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
			});

			if(!$j("#Nome-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Nome__RAND__.value, t: 'Candidatos', f: 'Nome' },
					success: function(resp) {
						$j('[name="Nome"]').val(resp.results[0].id);
						$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Eleitores_view_parent]').hide(); } else { $j('.btn[id=Eleitores_view_parent]').show(); }

						if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Nome__RAND__.value, t: 'Candidatos', f: 'Nome' },
				success: function(resp) {
					$j('[id=Nome-container__RAND__], [id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Eleitores_view_parent]').hide(); } else { $j('.btn[id=Eleitores_view_parent]').show(); }

					if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Candidatos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Candidatos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Candidatos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Candidatos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Candidatos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Partido').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Partido_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Nome').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Nome_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Numero').replaceWith('<div class=\"form-control-static\" id=\"Numero\">' + (jQuery('#Numero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Cargo').replaceWith('<div class=\"form-control-static\" id=\"Cargo\">' + (jQuery('#Cargo').val() || '') + '</div>'); jQuery('#Cargo-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#Midias').replaceWith('<div class=\"form-control-static\" id=\"Midias\">' + (jQuery('#Midias').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Partido)%%>', $combo_Partido->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Partido)%%>', $combo_Partido->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Partido)%%>', urlencode($combo_Partido->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Nome)%%>', $combo_Nome->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Nome)%%>', $combo_Nome->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Nome)%%>', urlencode($combo_Nome->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Cargo)%%>', $combo_Cargo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Cargo)%%>', $combo_Cargo->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Partido' => ['Partidos', 'Partido'], 'Nome' => ['Eleitores', 'Nome'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Partido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Numero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cargo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Midias)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Partido)%%>', safe_html($urow['Partido']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Partido)%%>', html_attr($row['Partido']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Partido)%%>', urlencode($urow['Partido']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', safe_html($urow['Nome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', html_attr($row['Nome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode($urow['Nome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', safe_html($urow['Numero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', html_attr($row['Numero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode($urow['Numero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cargo)%%>', safe_html($urow['Cargo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cargo)%%>', html_attr($row['Cargo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cargo)%%>', urlencode($urow['Cargo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Midias)%%>', safe_html($urow['Midias']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Midias)%%>', html_attr($row['Midias']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Midias)%%>', urlencode($urow['Midias']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Partido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Partido)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Numero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cargo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cargo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Midias)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Midias)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Candidatos');
	if($hasSelectedId) {
		$jdata = get_joined_record('Candidatos', $selectedId);
		if($jdata === false) $jdata = get_defaults('Candidatos');
		$rdata = $row;
	}
	$templateCode .= loadView('Candidatos-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Candidatos_dv
	if(function_exists('Candidatos_dv')) {
		$args = [];
		Candidatos_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}