<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Candidatos.php');
	include_once(__DIR__ . '/Candidatos_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Candidatos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Candidatos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Candidatos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`) || CHAR_LENGTH(`Partidos1`.`Numero`), CONCAT_WS('',   `Partidos1`.`Sigla`, '   -   ', `Partidos1`.`Numero`), '') /* Partido */" => "Partido",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Candidatos`.`Numero`" => "Numero",
		"`Candidatos`.`Cargo`" => "Cargo",
		"`Candidatos`.`Midias`" => "Midias",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Candidatos`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Candidatos`.`Numero`',
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Candidatos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`) || CHAR_LENGTH(`Partidos1`.`Numero`), CONCAT_WS('',   `Partidos1`.`Sigla`, '   -   ', `Partidos1`.`Numero`), '') /* Partido */" => "Partido",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Candidatos`.`Numero`" => "Numero",
		"`Candidatos`.`Cargo`" => "Cargo",
		"`Candidatos`.`Midias`" => "Midias",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Candidatos`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`) || CHAR_LENGTH(`Partidos1`.`Numero`), CONCAT_WS('',   `Partidos1`.`Sigla`, '   -   ', `Partidos1`.`Numero`), '') /* Partido */" => "Partido",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Candidatos`.`Numero`" => "Numero",
		"`Candidatos`.`Cargo`" => "Cargo",
		"`Candidatos`.`Midias`" => "Midias Sociais",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Candidatos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`) || CHAR_LENGTH(`Partidos1`.`Numero`), CONCAT_WS('',   `Partidos1`.`Sigla`, '   -   ', `Partidos1`.`Numero`), '') /* Partido */" => "Partido",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Candidatos`.`Numero`" => "Numero",
		"`Candidatos`.`Cargo`" => "Cargo",
		"`Candidatos`.`Midias`" => "Midias",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Partido' => 'Partido', 'Nome' => 'Nome', ];

	$x->QueryFrom = "`Candidatos` LEFT JOIN `Partidos` as Partidos1 ON `Partidos1`.`id`=`Candidatos`.`Partido` LEFT JOIN `Eleitores` as Eleitores1 ON `Eleitores1`.`id`=`Candidatos`.`Nome` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Eleitores1`.`Nome` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Candidatos_view.php';
	$x->TableTitle = 'Candidatos';
	$x->TableIcon = 'resources/table_icons/reseller_programm.png';
	$x->PrimaryKey = '`Candidatos`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Partido', 'Nome', 'Numero', 'Cargo', ];
	$x->ColFieldName = ['Partido', 'Nome', 'Numero', 'Cargo', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Candidatos_templateTV.html';
	$x->SelectedTemplate = 'templates/Candidatos_templateTVS.html';
	$x->TemplateDV = 'templates/Candidatos_templateDV.html';
	$x->TemplateDVP = 'templates/Candidatos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Candidatos_init
	$render = true;
	if(function_exists('Candidatos_init')) {
		$args = [];
		$render = Candidatos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Candidatos_header
	$headerCode = '';
	if(function_exists('Candidatos_header')) {
		$args = [];
		$headerCode = Candidatos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Candidatos_footer
	$footerCode = '';
	if(function_exists('Candidatos_footer')) {
		$args = [];
		$footerCode = Candidatos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
