<?php

// Data functions (insert, update, delete, form) for table Colaboradores

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Colaboradores_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Colaboradores');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Nome' => Request::lookup('Nome', ''),
		'Bairro' => Request::lookup('Nome'),
		'Profissao' => Request::lookup('Profissao', ''),
		'Funcao' => Request::lookup('Funcao', ''),
		'Responsavel' => Request::lookup('Responsavel', ''),
		'Obs' => br2nl(Request::val('Obs', '')),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Funcao'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fun&#231;&#227;o': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Colaboradores_before_insert
	if(function_exists('Colaboradores_before_insert')) {
		$args = [];
		if(!Colaboradores_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Colaboradores', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Colaboradores', $recID, calculated_fields()['Colaboradores']);

	// hook: Colaboradores_after_insert
	if(function_exists('Colaboradores_after_insert')) {
		$res = sql("SELECT * FROM `Colaboradores` WHERE `Id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Colaboradores_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Colaboradores', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Colaboradores_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Colaboradores_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Colaboradores_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Colaboradores', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Colaboradores_before_delete
	if(function_exists('Colaboradores_before_delete')) {
		$args = [];
		if(!Colaboradores_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Eleitores
	$res = sql("SELECT `Id` FROM `Colaboradores` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Eleitores` WHERE `indicacao`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Colaboradores
	$res = sql("SELECT `Id` FROM `Colaboradores` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Colaboradores` WHERE `Responsavel`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Colaboradores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Colaboradores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Agenda
	$res = sql("SELECT `Id` FROM `Colaboradores` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Agenda` WHERE `Responsavel`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Agenda', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Agenda', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Atendimentos
	$res = sql("SELECT `Id` FROM `Colaboradores` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Atendimentos` WHERE `Colaborador`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Atendimentos', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Atendimentos', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Colaboradores` WHERE `Id`='{$selected_id}'", $eo);

	// hook: Colaboradores_after_delete
	if(function_exists('Colaboradores_after_delete')) {
		$args = [];
		Colaboradores_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Colaboradores' AND `pkValue`='{$selected_id}'", $eo);
}

function Colaboradores_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Colaboradores', $selected_id, 'edit')) return false;

	$data = [
		'Nome' => Request::lookup('Nome', ''),
		'Bairro' => Request::lookup('Nome'),
		'Profissao' => Request::lookup('Profissao', ''),
		'Funcao' => Request::lookup('Funcao', ''),
		'Responsavel' => Request::lookup('Responsavel', ''),
		'Obs' => br2nl(Request::val('Obs', '')),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Funcao'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fun&#231;&#227;o': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Colaboradores', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Colaboradores_before_update
	if(function_exists('Colaboradores_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Colaboradores_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Colaboradores', 
		backtick_keys_once($set), 
		['`Id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Colaboradores_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Colaboradores', $data['selectedID'], calculated_fields()['Colaboradores']);

	// hook: Colaboradores_after_update
	if(function_exists('Colaboradores_after_update')) {
		$res = sql("SELECT * FROM `Colaboradores` WHERE `Id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['Id'];
		$args = ['old_data' => $old_data];
		if(!Colaboradores_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Colaboradores', $selected_id);
}

function Colaboradores_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Colaboradores');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Colaboradores', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Colaboradores', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Colaboradores', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Nome = Request::val('filterer_Nome');
	$filterer_Profissao = Request::val('filterer_Profissao');
	$filterer_Funcao = Request::val('filterer_Funcao');
	$filterer_Responsavel = Request::val('filterer_Responsavel');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Nome
	$combo_Nome = new DataCombo;
	// combobox: Profissao
	$combo_Profissao = new DataCombo;
	// combobox: Funcao
	$combo_Funcao = new DataCombo;
	// combobox: Responsavel
	$combo_Responsavel = new DataCombo;

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Colaboradores` WHERE `Id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Colaboradores_view.php', false);
		}
		$combo_Nome->SelectedData = $row['Nome'];
		$combo_Profissao->SelectedData = $row['Profissao'];
		$combo_Funcao->SelectedData = $row['Funcao'];
		$combo_Responsavel->SelectedData = $row['Responsavel'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Nome->SelectedData = $filterer_Nome;
		$combo_Profissao->SelectedData = $filterer_Profissao;
		$combo_Funcao->SelectedData = $filterer_Funcao;
		$combo_Responsavel->SelectedData = $filterer_Responsavel;
	}
	$combo_Nome->HTML = '<span id="Nome-container' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Nome->MatchText = '<span id="Nome-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Profissao->HTML = '<span id="Profissao-container' . $rnd1 . '"></span><input type="hidden" name="Profissao" id="Profissao' . $rnd1 . '" value="' . html_attr($combo_Profissao->SelectedData) . '">';
	$combo_Profissao->MatchText = '<span id="Profissao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Profissao" id="Profissao' . $rnd1 . '" value="' . html_attr($combo_Profissao->SelectedData) . '">';
	$combo_Funcao->HTML = '<span id="Funcao-container' . $rnd1 . '"></span><input type="hidden" name="Funcao" id="Funcao' . $rnd1 . '" value="' . html_attr($combo_Funcao->SelectedData) . '">';
	$combo_Funcao->MatchText = '<span id="Funcao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Funcao" id="Funcao' . $rnd1 . '" value="' . html_attr($combo_Funcao->SelectedData) . '">';
	$combo_Responsavel->HTML = '<span id="Responsavel-container' . $rnd1 . '"></span><input type="hidden" name="Responsavel" id="Responsavel' . $rnd1 . '" value="' . html_attr($combo_Responsavel->SelectedData) . '">';
	$combo_Responsavel->MatchText = '<span id="Responsavel-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Responsavel" id="Responsavel' . $rnd1 . '" value="' . html_attr($combo_Responsavel->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Nome__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Nome'] : htmlspecialchars($filterer_Nome, ENT_QUOTES)); ?>"};
		AppGini.current_Profissao__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Profissao'] : htmlspecialchars($filterer_Profissao, ENT_QUOTES)); ?>"};
		AppGini.current_Funcao__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Funcao'] : htmlspecialchars($filterer_Funcao, ENT_QUOTES)); ?>"};
		AppGini.current_Responsavel__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Responsavel'] : htmlspecialchars($filterer_Responsavel, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Nome_reload__RAND__) == 'function') Nome_reload__RAND__();
				if(typeof(Profissao_reload__RAND__) == 'function') Profissao_reload__RAND__();
				if(typeof(Funcao_reload__RAND__) == 'function') Funcao_reload__RAND__();
				if(typeof(Responsavel_reload__RAND__) == 'function') Responsavel_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Nome_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Nome-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Nome__RAND__.value, t: 'Colaboradores', f: 'Nome' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Nome"]').val(resp.results[0].id);
							$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }


							if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Colaboradores', f: 'Nome' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Nome__RAND__.value = e.added.id;
				AppGini.current_Nome__RAND__.text = e.added.text;
				$j('[name="Nome"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }


				if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
			});

			if(!$j("#Nome-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Nome__RAND__.value, t: 'Colaboradores', f: 'Nome' },
					success: function(resp) {
						$j('[name="Nome"]').val(resp.results[0].id);
						$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }

						if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Nome__RAND__.value, t: 'Colaboradores', f: 'Nome' },
				success: function(resp) {
					$j('[id=Nome-container__RAND__], [id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }

					if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Profissao_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Profissao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Profissao__RAND__.value, t: 'Colaboradores', f: 'Profissao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Profissao"]').val(resp.results[0].id);
							$j('[id=Profissao-container-readonly__RAND__]').html('<span class="match-text" id="Profissao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }


							if(typeof(Profissao_update_autofills__RAND__) == 'function') Profissao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Colaboradores', f: 'Profissao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Profissao__RAND__.value = e.added.id;
				AppGini.current_Profissao__RAND__.text = e.added.text;
				$j('[name="Profissao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }


				if(typeof(Profissao_update_autofills__RAND__) == 'function') Profissao_update_autofills__RAND__();
			});

			if(!$j("#Profissao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Profissao__RAND__.value, t: 'Colaboradores', f: 'Profissao' },
					success: function(resp) {
						$j('[name="Profissao"]').val(resp.results[0].id);
						$j('[id=Profissao-container-readonly__RAND__]').html('<span class="match-text" id="Profissao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }

						if(typeof(Profissao_update_autofills__RAND__) == 'function') Profissao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Profissao__RAND__.value, t: 'Colaboradores', f: 'Profissao' },
				success: function(resp) {
					$j('[id=Profissao-container__RAND__], [id=Profissao-container-readonly__RAND__]').html('<span class="match-text" id="Profissao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }

					if(typeof(Profissao_update_autofills__RAND__) == 'function') Profissao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Funcao_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Funcao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Funcao__RAND__.value, t: 'Colaboradores', f: 'Funcao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Funcao"]').val(resp.results[0].id);
							$j('[id=Funcao-container-readonly__RAND__]').html('<span class="match-text" id="Funcao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Funcoes_view_parent]').hide(); } else { $j('.btn[id=Funcoes_view_parent]').show(); }


							if(typeof(Funcao_update_autofills__RAND__) == 'function') Funcao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Colaboradores', f: 'Funcao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Funcao__RAND__.value = e.added.id;
				AppGini.current_Funcao__RAND__.text = e.added.text;
				$j('[name="Funcao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Funcoes_view_parent]').hide(); } else { $j('.btn[id=Funcoes_view_parent]').show(); }


				if(typeof(Funcao_update_autofills__RAND__) == 'function') Funcao_update_autofills__RAND__();
			});

			if(!$j("#Funcao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Funcao__RAND__.value, t: 'Colaboradores', f: 'Funcao' },
					success: function(resp) {
						$j('[name="Funcao"]').val(resp.results[0].id);
						$j('[id=Funcao-container-readonly__RAND__]').html('<span class="match-text" id="Funcao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Funcoes_view_parent]').hide(); } else { $j('.btn[id=Funcoes_view_parent]').show(); }

						if(typeof(Funcao_update_autofills__RAND__) == 'function') Funcao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Funcao__RAND__.value, t: 'Colaboradores', f: 'Funcao' },
				success: function(resp) {
					$j('[id=Funcao-container__RAND__], [id=Funcao-container-readonly__RAND__]').html('<span class="match-text" id="Funcao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Funcoes_view_parent]').hide(); } else { $j('.btn[id=Funcoes_view_parent]').show(); }

					if(typeof(Funcao_update_autofills__RAND__) == 'function') Funcao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Responsavel_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Responsavel-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Colaboradores', f: 'Responsavel' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Responsavel"]').val(resp.results[0].id);
							$j('[id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


							if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Colaboradores', f: 'Responsavel' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Responsavel__RAND__.value = e.added.id;
				AppGini.current_Responsavel__RAND__.text = e.added.text;
				$j('[name="Responsavel"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


				if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
			});

			if(!$j("#Responsavel-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Colaboradores', f: 'Responsavel' },
					success: function(resp) {
						$j('[name="Responsavel"]').val(resp.results[0].id);
						$j('[id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

						if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Responsavel__RAND__.value, t: 'Colaboradores', f: 'Responsavel' },
				success: function(resp) {
					$j('[id=Responsavel-container__RAND__], [id=Responsavel-container-readonly__RAND__]').html('<span class="match-text" id="Responsavel-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

					if(typeof(Responsavel_update_autofills__RAND__) == 'function') Responsavel_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Colaboradores_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Colaboradores_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Colaboradores_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Colaboradores_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Colaboradores_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Nome').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Nome_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Profissao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Profissao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Funcao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Funcao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Responsavel').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Responsavel_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Obs').replaceWith('<div class=\"form-control-static\" id=\"Obs\">' + (jQuery('#Obs').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Nome)%%>', $combo_Nome->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Nome)%%>', $combo_Nome->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Nome)%%>', urlencode($combo_Nome->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Profissao)%%>', $combo_Profissao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Profissao)%%>', $combo_Profissao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Profissao)%%>', urlencode($combo_Profissao->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Funcao)%%>', $combo_Funcao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Funcao)%%>', $combo_Funcao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Funcao)%%>', urlencode($combo_Funcao->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Responsavel)%%>', $combo_Responsavel->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Responsavel)%%>', $combo_Responsavel->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Responsavel)%%>', urlencode($combo_Responsavel->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Nome' => ['Pessoas', 'Nome'], 'Profissao' => ['Profissoes', 'Profiss&#227;o'], 'Funcao' => ['Funcoes', 'Fun&#231;&#227;o'], 'Responsavel' => ['Colaboradores', 'Responsavel'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(Id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Profissao)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Funcao)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Responsavel)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Obs)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(Id)%%>', safe_html($urow['Id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode($urow['Id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', safe_html($urow['Nome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', html_attr($row['Nome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode($urow['Nome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Profissao)%%>', safe_html($urow['Profissao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Profissao)%%>', html_attr($row['Profissao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Profissao)%%>', urlencode($urow['Profissao']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Funcao)%%>', safe_html($urow['Funcao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Funcao)%%>', html_attr($row['Funcao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Funcao)%%>', urlencode($urow['Funcao']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Responsavel)%%>', safe_html($urow['Responsavel']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Responsavel)%%>', html_attr($row['Responsavel']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsavel)%%>', urlencode($urow['Responsavel']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', safe_html($urow['Obs'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode($urow['Obs']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(Id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Profissao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Profissao)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Funcao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Funcao)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Responsavel)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Responsavel)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tNome_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Colaboradores_autofill.php?rnd1=$rnd1&mfk=Nome&id=' + encodeURIComponent('".addslashes($row['Nome'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Colaboradores_autofill.php?rnd1=$rnd1&mfk=Nome&id=' + encodeURIComponent(AppGini.current_Nome{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Nome$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#Nome$rnd1').prop('disabled', false); " : "\$j('#Nome$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Nome_caption').length) \$j('#Nome_caption').click(function() { Nome_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Colaboradores');
	if($hasSelectedId) {
		$jdata = get_joined_record('Colaboradores', $selectedId);
		if($jdata === false) $jdata = get_defaults('Colaboradores');
		$rdata = $row;
	}
	$templateCode .= loadView('Colaboradores-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Colaboradores_dv
	if(function_exists('Colaboradores_dv')) {
		$args = [];
		Colaboradores_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}