<?php

// Data functions (insert, update, delete, form) for table Eleitores

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Eleitores_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Eleitores');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Nome' => Request::lookup('Nome', ''),
		'Mae' => Request::val('Mae', ''),
		'DataN' => Request::dateComponents('DataN', ''),
		'CPF' => Request::val('CPF', ''),
		'Titulo' => Request::val('Titulo', ''),
		'Estado' => Request::lookup('Nome'),
		'Cidade' => Request::lookup('Nome'),
		'Bairro' => Request::lookup('Nome'),
		'Zona' => Request::lookup('Zona', ''),
		'secao' => Request::lookup('secao', ''),
		'local' => Request::lookup('secao'),
		'partido' => Request::lookup('partido', ''),
		'indicacao' => Request::lookup('indicacao', ''),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Eleitores_before_insert
	if(function_exists('Eleitores_before_insert')) {
		$args = [];
		if(!Eleitores_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Eleitores', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Eleitores', $recID, calculated_fields()['Eleitores']);

	// hook: Eleitores_after_insert
	if(function_exists('Eleitores_after_insert')) {
		$res = sql("SELECT * FROM `Eleitores` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Eleitores_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Eleitores', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Eleitores_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Eleitores_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Eleitores_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Eleitores', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Eleitores_before_delete
	if(function_exists('Eleitores_before_delete')) {
		$args = [];
		if(!Eleitores_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Candidatos
	$res = sql("SELECT `id` FROM `Eleitores` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Candidatos` WHERE `Nome`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Candidatos', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Candidatos', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Eleitores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Eleitores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Atendimentos
	$res = sql("SELECT `id` FROM `Eleitores` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Atendimentos` WHERE `Eleitor`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Atendimentos', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Atendimentos', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Eleitores_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Eleitores_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Eleitores` WHERE `id`='{$selected_id}'", $eo);

	// hook: Eleitores_after_delete
	if(function_exists('Eleitores_after_delete')) {
		$args = [];
		Eleitores_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Eleitores' AND `pkValue`='{$selected_id}'", $eo);
}

function Eleitores_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Eleitores', $selected_id, 'edit')) return false;

	$data = [
		'Nome' => Request::lookup('Nome', ''),
		'Mae' => Request::val('Mae', ''),
		'DataN' => Request::dateComponents('DataN', ''),
		'CPF' => Request::val('CPF', ''),
		'Titulo' => Request::val('Titulo', ''),
		'Estado' => Request::lookup('Nome'),
		'Cidade' => Request::lookup('Nome'),
		'Bairro' => Request::lookup('Nome'),
		'Zona' => Request::lookup('Zona', ''),
		'secao' => Request::lookup('secao', ''),
		'local' => Request::lookup('secao'),
		'partido' => Request::lookup('partido', ''),
		'indicacao' => Request::lookup('indicacao', ''),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Eleitores', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Eleitores_before_update
	if(function_exists('Eleitores_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Eleitores_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Eleitores', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Eleitores_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Eleitores', $data['selectedID'], calculated_fields()['Eleitores']);

	// hook: Eleitores_after_update
	if(function_exists('Eleitores_after_update')) {
		$res = sql("SELECT * FROM `Eleitores` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Eleitores_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Eleitores', $selected_id);
}

function Eleitores_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Eleitores');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Eleitores', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Eleitores', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Eleitores', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Nome = Request::val('filterer_Nome');
	$filterer_Zona = Request::val('filterer_Zona');
	$filterer_secao = Request::val('filterer_secao');
	$filterer_partido = Request::val('filterer_partido');
	$filterer_indicacao = Request::val('filterer_indicacao');

	// populate filterers, starting from children to grand-parents
	if($filterer_secao && !$filterer_Zona) $filterer_Zona = sqlValue("select Cidade from Secao where id='" . makeSafe($filterer_secao) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Nome
	$combo_Nome = new DataCombo;
	// combobox: DataN
	$combo_DataN = new DateCombo;
	$combo_DataN->DateFormat = "dmy";
	$combo_DataN->MinYear = defined('Eleitores.DataN.MinYear') ? constant('Eleitores.DataN.MinYear') : 1900;
	$combo_DataN->MaxYear = defined('Eleitores.DataN.MaxYear') ? constant('Eleitores.DataN.MaxYear') : 2100;
	$combo_DataN->DefaultDate = parseMySQLDate('', '');
	$combo_DataN->MonthNames = $Translation['month names'];
	$combo_DataN->NamePrefix = 'DataN';
	// combobox: Zona
	$combo_Zona = new DataCombo;
	// combobox: secao, filterable by: Zona
	$combo_secao = new DataCombo;
	// combobox: partido
	$combo_partido = new DataCombo;
	// combobox: indicacao
	$combo_indicacao = new DataCombo;

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Eleitores` WHERE `id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Eleitores_view.php', false);
		}
		$combo_Nome->SelectedData = $row['Nome'];
		$combo_DataN->DefaultDate = $row['DataN'];
		$combo_Zona->SelectedData = $row['Zona'];
		$combo_secao->SelectedData = $row['secao'];
		$combo_partido->SelectedData = $row['partido'];
		$combo_indicacao->SelectedData = $row['indicacao'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Nome->SelectedData = $filterer_Nome;
		$combo_Zona->SelectedData = $filterer_Zona;
		$combo_secao->SelectedData = $filterer_secao;
		$combo_partido->SelectedData = $filterer_partido;
		$combo_indicacao->SelectedData = $filterer_indicacao;
	}
	$combo_Nome->HTML = '<span id="Nome-container' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Nome->MatchText = '<span id="Nome-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Nome" id="Nome' . $rnd1 . '" value="' . html_attr($combo_Nome->SelectedData) . '">';
	$combo_Zona->HTML = '<span id="Zona-container' . $rnd1 . '"></span><input type="hidden" name="Zona" id="Zona' . $rnd1 . '" value="' . html_attr($combo_Zona->SelectedData) . '">';
	$combo_Zona->MatchText = '<span id="Zona-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Zona" id="Zona' . $rnd1 . '" value="' . html_attr($combo_Zona->SelectedData) . '">';
	$combo_secao->HTML = '<span id="secao-container' . $rnd1 . '"></span><input type="hidden" name="secao" id="secao' . $rnd1 . '" value="' . html_attr($combo_secao->SelectedData) . '">';
	$combo_secao->MatchText = '<span id="secao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="secao" id="secao' . $rnd1 . '" value="' . html_attr($combo_secao->SelectedData) . '">';
	$combo_partido->HTML = '<span id="partido-container' . $rnd1 . '"></span><input type="hidden" name="partido" id="partido' . $rnd1 . '" value="' . html_attr($combo_partido->SelectedData) . '">';
	$combo_partido->MatchText = '<span id="partido-container-readonly' . $rnd1 . '"></span><input type="hidden" name="partido" id="partido' . $rnd1 . '" value="' . html_attr($combo_partido->SelectedData) . '">';
	$combo_indicacao->HTML = '<span id="indicacao-container' . $rnd1 . '"></span><input type="hidden" name="indicacao" id="indicacao' . $rnd1 . '" value="' . html_attr($combo_indicacao->SelectedData) . '">';
	$combo_indicacao->MatchText = '<span id="indicacao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="indicacao" id="indicacao' . $rnd1 . '" value="' . html_attr($combo_indicacao->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Nome__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Nome'] : htmlspecialchars($filterer_Nome, ENT_QUOTES)); ?>"};
		AppGini.current_Zona__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Zona'] : htmlspecialchars($filterer_Zona, ENT_QUOTES)); ?>"};
		AppGini.current_secao__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['secao'] : htmlspecialchars($filterer_secao, ENT_QUOTES)); ?>"};
		AppGini.current_partido__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['partido'] : htmlspecialchars($filterer_partido, ENT_QUOTES)); ?>"};
		AppGini.current_indicacao__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['indicacao'] : htmlspecialchars($filterer_indicacao, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Nome_reload__RAND__) == 'function') Nome_reload__RAND__();
				if(typeof(Zona_reload__RAND__) == 'function') Zona_reload__RAND__();
				<?php echo (!$allowUpdate || $dvprint ? 'if(typeof(secao_reload__RAND__) == \'function\') secao_reload__RAND__(AppGini.current_Zona__RAND__.value);' : ''); ?>
				if(typeof(partido_reload__RAND__) == 'function') partido_reload__RAND__();
				if(typeof(indicacao_reload__RAND__) == 'function') indicacao_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Nome_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Nome-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Nome__RAND__.value, t: 'Eleitores', f: 'Nome' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Nome"]').val(resp.results[0].id);
							$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }


							if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Eleitores', f: 'Nome' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Nome__RAND__.value = e.added.id;
				AppGini.current_Nome__RAND__.text = e.added.text;
				$j('[name="Nome"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }


				if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
			});

			if(!$j("#Nome-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Nome__RAND__.value, t: 'Eleitores', f: 'Nome' },
					success: function(resp) {
						$j('[name="Nome"]').val(resp.results[0].id);
						$j('[id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }

						if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Nome__RAND__.value, t: 'Eleitores', f: 'Nome' },
				success: function(resp) {
					$j('[id=Nome-container__RAND__], [id=Nome-container-readonly__RAND__]').html('<span class="match-text" id="Nome-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Pessoas_view_parent]').hide(); } else { $j('.btn[id=Pessoas_view_parent]').show(); }

					if(typeof(Nome_update_autofills__RAND__) == 'function') Nome_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Zona_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Zona-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Zona__RAND__.value, t: 'Eleitores', f: 'Zona' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Zona"]').val(resp.results[0].id);
							$j('[id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

						if(typeof(secao_reload__RAND__) == 'function') secao_reload__RAND__(AppGini.current_Zona__RAND__.value);

							if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Eleitores', f: 'Zona' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Zona__RAND__.value = e.added.id;
				AppGini.current_Zona__RAND__.text = e.added.text;
				$j('[name="Zona"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

						if(typeof(secao_reload__RAND__) == 'function') secao_reload__RAND__(AppGini.current_Zona__RAND__.value);

				if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
			});

			if(!$j("#Zona-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Zona__RAND__.value, t: 'Eleitores', f: 'Zona' },
					success: function(resp) {
						$j('[name="Zona"]').val(resp.results[0].id);
						$j('[id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

						if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Zona__RAND__.value, t: 'Eleitores', f: 'Zona' },
				success: function(resp) {
					$j('[id=Zona-container__RAND__], [id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

					if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function secao_reload__RAND__(filterer_Zona) {
		<?php if($fieldsAreEditable) { ?>

			$j("#secao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_Zona: filterer_Zona, id: AppGini.current_secao__RAND__.value, t: 'Eleitores', f: 'secao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="secao"]').val(resp.results[0].id);
							$j('[id=secao-container-readonly__RAND__]').html('<span class="match-text" id="secao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Secao_view_parent]').hide(); } else { $j('.btn[id=Secao_view_parent]').show(); }


							if(typeof(secao_update_autofills__RAND__) == 'function') secao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_Zona: filterer_Zona, s: term, p: page, t: 'Eleitores', f: 'secao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_secao__RAND__.value = e.added.id;
				AppGini.current_secao__RAND__.text = e.added.text;
				$j('[name="secao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Secao_view_parent]').hide(); } else { $j('.btn[id=Secao_view_parent]').show(); }


				if(typeof(secao_update_autofills__RAND__) == 'function') secao_update_autofills__RAND__();
			});

			if(!$j("#secao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_secao__RAND__.value, t: 'Eleitores', f: 'secao' },
					success: function(resp) {
						$j('[name="secao"]').val(resp.results[0].id);
						$j('[id=secao-container-readonly__RAND__]').html('<span class="match-text" id="secao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Secao_view_parent]').hide(); } else { $j('.btn[id=Secao_view_parent]').show(); }

						if(typeof(secao_update_autofills__RAND__) == 'function') secao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_secao__RAND__.value, t: 'Eleitores', f: 'secao' },
				success: function(resp) {
					$j('[id=secao-container__RAND__], [id=secao-container-readonly__RAND__]').html('<span class="match-text" id="secao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Secao_view_parent]').hide(); } else { $j('.btn[id=Secao_view_parent]').show(); }

					if(typeof(secao_update_autofills__RAND__) == 'function') secao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function partido_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#partido-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_partido__RAND__.value, t: 'Eleitores', f: 'partido' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="partido"]').val(resp.results[0].id);
							$j('[id=partido-container-readonly__RAND__]').html('<span class="match-text" id="partido-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }


							if(typeof(partido_update_autofills__RAND__) == 'function') partido_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Eleitores', f: 'partido' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_partido__RAND__.value = e.added.id;
				AppGini.current_partido__RAND__.text = e.added.text;
				$j('[name="partido"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }


				if(typeof(partido_update_autofills__RAND__) == 'function') partido_update_autofills__RAND__();
			});

			if(!$j("#partido-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_partido__RAND__.value, t: 'Eleitores', f: 'partido' },
					success: function(resp) {
						$j('[name="partido"]').val(resp.results[0].id);
						$j('[id=partido-container-readonly__RAND__]').html('<span class="match-text" id="partido-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

						if(typeof(partido_update_autofills__RAND__) == 'function') partido_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_partido__RAND__.value, t: 'Eleitores', f: 'partido' },
				success: function(resp) {
					$j('[id=partido-container__RAND__], [id=partido-container-readonly__RAND__]').html('<span class="match-text" id="partido-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Partidos_view_parent]').hide(); } else { $j('.btn[id=Partidos_view_parent]').show(); }

					if(typeof(partido_update_autofills__RAND__) == 'function') partido_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function indicacao_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#indicacao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_indicacao__RAND__.value, t: 'Eleitores', f: 'indicacao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="indicacao"]').val(resp.results[0].id);
							$j('[id=indicacao-container-readonly__RAND__]').html('<span class="match-text" id="indicacao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


							if(typeof(indicacao_update_autofills__RAND__) == 'function') indicacao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Eleitores', f: 'indicacao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_indicacao__RAND__.value = e.added.id;
				AppGini.current_indicacao__RAND__.text = e.added.text;
				$j('[name="indicacao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }


				if(typeof(indicacao_update_autofills__RAND__) == 'function') indicacao_update_autofills__RAND__();
			});

			if(!$j("#indicacao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_indicacao__RAND__.value, t: 'Eleitores', f: 'indicacao' },
					success: function(resp) {
						$j('[name="indicacao"]').val(resp.results[0].id);
						$j('[id=indicacao-container-readonly__RAND__]').html('<span class="match-text" id="indicacao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

						if(typeof(indicacao_update_autofills__RAND__) == 'function') indicacao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_indicacao__RAND__.value, t: 'Eleitores', f: 'indicacao' },
				success: function(resp) {
					$j('[id=indicacao-container__RAND__], [id=indicacao-container-readonly__RAND__]').html('<span class="match-text" id="indicacao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Colaboradores_view_parent]').hide(); } else { $j('.btn[id=Colaboradores_view_parent]').show(); }

					if(typeof(indicacao_update_autofills__RAND__) == 'function') indicacao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Eleitores_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Eleitores_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Eleitores_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Eleitores_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Eleitores_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Nome').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Nome_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Mae').replaceWith('<div class=\"form-control-static\" id=\"Mae\">' + (jQuery('#Mae').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#DataN').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DataNDay, #DataNMonth, #DataNYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CPF').replaceWith('<div class=\"form-control-static\" id=\"CPF\">' + (jQuery('#CPF').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Titulo').replaceWith('<div class=\"form-control-static\" id=\"Titulo\">' + (jQuery('#Titulo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Zona').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Zona_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#secao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#secao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#partido').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#partido_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#indicacao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#indicacao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Nome)%%>', $combo_Nome->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Nome)%%>', $combo_Nome->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Nome)%%>', urlencode($combo_Nome->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(DataN)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_DataN->GetHTML(true) . '</div>' : 
			$combo_DataN->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(DataN)%%>', $combo_DataN->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Zona)%%>', $combo_Zona->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Zona)%%>', $combo_Zona->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Zona)%%>', urlencode($combo_Zona->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(secao)%%>', $combo_secao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(secao)%%>', $combo_secao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(secao)%%>', urlencode($combo_secao->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(partido)%%>', $combo_partido->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(partido)%%>', $combo_partido->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(partido)%%>', urlencode($combo_partido->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(indicacao)%%>', $combo_indicacao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(indicacao)%%>', $combo_indicacao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(indicacao)%%>', urlencode($combo_indicacao->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Nome' => ['Pessoas', 'Nome'], 'Zona' => ['Zona', 'Zona'], 'secao' => ['Secao', 'Se&#231;&#227;o'], 'partido' => ['Partidos', 'Partido'], 'indicacao' => ['Colaboradores', 'Indica&#231;&#227;o'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Mae)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DataN)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CPF)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Titulo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Zona)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(secao)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(partido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(indicacao)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', safe_html($urow['Nome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', html_attr($row['Nome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode($urow['Nome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Mae)%%>', safe_html($urow['Mae']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Mae)%%>', html_attr($row['Mae']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Mae)%%>', urlencode($urow['Mae']), $templateCode);
		$templateCode = str_replace('<%%VALUE(DataN)%%>', app_datetime($row['DataN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DataN)%%>', urlencode(app_datetime($urow['DataN'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CPF)%%>', safe_html($urow['CPF']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CPF)%%>', html_attr($row['CPF']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CPF)%%>', urlencode($urow['CPF']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Titulo)%%>', safe_html($urow['Titulo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Titulo)%%>', html_attr($row['Titulo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo)%%>', urlencode($urow['Titulo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Zona)%%>', safe_html($urow['Zona']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Zona)%%>', html_attr($row['Zona']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Zona)%%>', urlencode($urow['Zona']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(secao)%%>', safe_html($urow['secao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(secao)%%>', html_attr($row['secao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(secao)%%>', urlencode($urow['secao']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(partido)%%>', safe_html($urow['partido']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(partido)%%>', html_attr($row['partido']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(partido)%%>', urlencode($urow['partido']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(indicacao)%%>', safe_html($urow['indicacao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(indicacao)%%>', html_attr($row['indicacao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(indicacao)%%>', urlencode($urow['indicacao']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Mae)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Mae)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DataN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DataN)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CPF)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CPF)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Titulo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Zona)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Zona)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(secao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(secao)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(partido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(partido)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(indicacao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(indicacao)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tNome_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Eleitores_autofill.php?rnd1=$rnd1&mfk=Nome&id=' + encodeURIComponent('".addslashes($row['Nome'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Eleitores_autofill.php?rnd1=$rnd1&mfk=Nome&id=' + encodeURIComponent(AppGini.current_Nome{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#Nome$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#Nome$rnd1').prop('disabled', false); " : "\$j('#Nome$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#Nome_caption').length) \$j('#Nome_caption').click(function() { Nome_update_autofills$rnd1(); });\n";

	$templateCode .= "\tsecao_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'Eleitores_autofill.php?rnd1=$rnd1&mfk=secao&id=' + encodeURIComponent('".addslashes($row['secao'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'Eleitores_autofill.php?rnd1=$rnd1&mfk=secao&id=' + encodeURIComponent(AppGini.current_secao{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#secao$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#secao$rnd1').prop('disabled', false); " : "\$j('#secao$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#secao_caption').length) \$j('#secao_caption').click(function() { secao_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Eleitores');
	if($hasSelectedId) {
		$jdata = get_joined_record('Eleitores', $selectedId);
		if($jdata === false) $jdata = get_defaults('Eleitores');
		$rdata = $row;
	}
	$templateCode .= loadView('Eleitores-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Eleitores_dv
	if(function_exists('Eleitores_dv')) {
		$args = [];
		Eleitores_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}