<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('Eleitores');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = Request::val('mfk');
	$id = makeSafe(Request::val('id'));
	$rnd1 = intval(Request::val('rnd1')); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'Nome':
			if(!$id) {
				?>
				$j('#Estado<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Cidade<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#Bairro<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `Pessoas`.`Id` as 'Id', `Pessoas`.`Nome` as 'Nome', IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') as 'Estado', IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') as 'Cidade', IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') as 'Bairro', `Pessoas`.`Rua` as 'Rua', `Pessoas`.`numero` as 'numero', `Pessoas`.`CEP` as 'CEP', `Pessoas`.`Contato` as 'Contato', IF(    CHAR_LENGTH(`Profissoes1`.`Profissao`) || CHAR_LENGTH(`Profissoes1`.`Seguimento`), CONCAT_WS('',   `Profissoes1`.`Profissao`, '   -   ', `Profissoes1`.`Seguimento`), '') as 'profissao', `Pessoas`.`Email` as 'Email', `Pessoas`.`Midias` as 'Midias', `Pessoas`.`Obs` as 'Obs' FROM `Pessoas` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas`.`Bairro` LEFT JOIN `Profissoes` as Profissoes1 ON `Profissoes1`.`id`=`Pessoas`.`profissao`  WHERE `Pessoas`.`Id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#Estado<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Estado']))); ?>&nbsp;');
			$j('#Cidade<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Cidade']))); ?>&nbsp;');
			$j('#Bairro<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Bairro']))); ?>&nbsp;');
			<?php
			break;

		case 'secao':
			if(!$id) {
				?>
				$j('#local<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `Secao`.`id` as 'id', `Secao`.`Numero` as 'Numero', IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') as 'Cidade', IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') as 'Bairro', IF(    CHAR_LENGTH(`Zona2`.`Numero`), CONCAT_WS('',   `Zona2`.`Numero`), '') as 'Zona', `Secao`.`Endereco` as 'Endereco', `Secao`.`Local` as 'Local', `Secao`.`Eleitores` as 'Eleitores' FROM `Secao` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Secao`.`Cidade` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona1`.`Municipio` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Secao`.`Bairro` LEFT JOIN `Zona` as Zona2 ON `Zona2`.`id`=`Secao`.`Zona`  WHERE `Secao`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#local<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(["\r", "\n"], '', safe_html($row['Local']))); ?>&nbsp;');
			<?php
			break;


	}

?>