<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Eleitores.php');
	include_once(__DIR__ . '/Eleitores_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Eleitores');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Eleitores';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Eleitores`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Eleitores`.`Mae`" => "Mae",
		"if(`Eleitores`.`DataN`,date_format(`Eleitores`.`DataN`,'%d/%m/%Y'),'')" => "DataN",
		"`Eleitores`.`CPF`" => "CPF",
		"`Eleitores`.`Titulo`" => "Titulo",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona1`.`Numero`), CONCAT_WS('',   `Zona1`.`Numero`), '') /* Zona */" => "Zona",
		"IF(    CHAR_LENGTH(`Secao1`.`Numero`), CONCAT_WS('',   `Secao1`.`Numero`, '    -    '), '') /* Se&#231;&#227;o */" => "secao",
		"IF(    CHAR_LENGTH(`Secao1`.`Local`), CONCAT_WS('',   `Secao1`.`Local`), '') /* Local de vota&#231;&#227;o */" => "local",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`), CONCAT_WS('',   `Partidos1`.`Sigla`), '') /* Partido */" => "partido",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Indica&#231;&#227;o */" => "indicacao",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Eleitores`.`id`',
		2 => '`Pessoas1`.`Nome`',
		3 => 3,
		4 => '`Eleitores`.`DataN`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`Zona1`.`Numero`',
		11 => 11,
		12 => '`Secao1`.`Local`',
		13 => '`Partidos1`.`Sigla`',
		14 => 14,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Eleitores`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Eleitores`.`Mae`" => "Mae",
		"if(`Eleitores`.`DataN`,date_format(`Eleitores`.`DataN`,'%d/%m/%Y'),'')" => "DataN",
		"`Eleitores`.`CPF`" => "CPF",
		"`Eleitores`.`Titulo`" => "Titulo",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona1`.`Numero`), CONCAT_WS('',   `Zona1`.`Numero`), '') /* Zona */" => "Zona",
		"IF(    CHAR_LENGTH(`Secao1`.`Numero`), CONCAT_WS('',   `Secao1`.`Numero`, '    -    '), '') /* Se&#231;&#227;o */" => "secao",
		"IF(    CHAR_LENGTH(`Secao1`.`Local`), CONCAT_WS('',   `Secao1`.`Local`), '') /* Local de vota&#231;&#227;o */" => "local",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`), CONCAT_WS('',   `Partidos1`.`Sigla`), '') /* Partido */" => "partido",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Indica&#231;&#227;o */" => "indicacao",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Eleitores`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Eleitores`.`Mae`" => "M&#226;e",
		"`Eleitores`.`DataN`" => "Nascimento",
		"`Eleitores`.`CPF`" => "CPF",
		"`Eleitores`.`Titulo`" => "Titulo",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona1`.`Numero`), CONCAT_WS('',   `Zona1`.`Numero`), '') /* Zona */" => "Zona",
		"IF(    CHAR_LENGTH(`Secao1`.`Numero`), CONCAT_WS('',   `Secao1`.`Numero`, '    -    '), '') /* Se&#231;&#227;o */" => "Se&#231;&#227;o",
		"IF(    CHAR_LENGTH(`Secao1`.`Local`), CONCAT_WS('',   `Secao1`.`Local`), '') /* Local de vota&#231;&#227;o */" => "Local de vota&#231;&#227;o",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`), CONCAT_WS('',   `Partidos1`.`Sigla`), '') /* Partido */" => "Partido",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Indica&#231;&#227;o */" => "Indica&#231;&#227;o",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Eleitores`.`id`" => "id",
		"IF(    CHAR_LENGTH(`Pessoas1`.`Nome`), CONCAT_WS('',   `Pessoas1`.`Nome`), '') /* Nome */" => "Nome",
		"`Eleitores`.`Mae`" => "Mae",
		"if(`Eleitores`.`DataN`,date_format(`Eleitores`.`DataN`,'%d/%m/%Y'),'')" => "DataN",
		"`Eleitores`.`CPF`" => "CPF",
		"`Eleitores`.`Titulo`" => "Titulo",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona1`.`Numero`), CONCAT_WS('',   `Zona1`.`Numero`), '') /* Zona */" => "Zona",
		"IF(    CHAR_LENGTH(`Secao1`.`Numero`), CONCAT_WS('',   `Secao1`.`Numero`, '    -    '), '') /* Se&#231;&#227;o */" => "secao",
		"IF(    CHAR_LENGTH(`Secao1`.`Local`), CONCAT_WS('',   `Secao1`.`Local`), '') /* Local de vota&#231;&#227;o */" => "local",
		"IF(    CHAR_LENGTH(`Partidos1`.`Sigla`), CONCAT_WS('',   `Partidos1`.`Sigla`), '') /* Partido */" => "partido",
		"IF(    CHAR_LENGTH(`Pessoas2`.`Nome`) || CHAR_LENGTH(`Funcoes1`.`Nome`), CONCAT_WS('',   `Pessoas2`.`Nome`, '    -    ', `Funcoes1`.`Nome`), '') /* Indica&#231;&#227;o */" => "indicacao",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Nome' => 'Nome', 'Zona' => 'Zona', 'secao' => 'Se&#231;&#227;o', 'partido' => 'Partido', 'indicacao' => 'Indica&#231;&#227;o', ];

	$x->QueryFrom = "`Eleitores` LEFT JOIN `Pessoas` as Pessoas1 ON `Pessoas1`.`Id`=`Eleitores`.`Nome` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Eleitores`.`Zona` LEFT JOIN `Secao` as Secao1 ON `Secao1`.`id`=`Eleitores`.`secao` LEFT JOIN `Partidos` as Partidos1 ON `Partidos1`.`id`=`Eleitores`.`partido` LEFT JOIN `Colaboradores` as Colaboradores1 ON `Colaboradores1`.`Id`=`Eleitores`.`indicacao` LEFT JOIN `Pessoas` as Pessoas2 ON `Pessoas2`.`Id`=`Colaboradores1`.`Nome` LEFT JOIN `Funcoes` as Funcoes1 ON `Funcoes1`.`Id`=`Colaboradores1`.`Funcao` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Pessoas1`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Pessoas1`.`Cidade` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Pessoas1`.`Bairro` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Eleitores_view.php';
	$x->TableTitle = 'Eleitores';
	$x->TableIcon = 'resources/table_icons/email_to_friend.png';
	$x->PrimaryKey = '`Eleitores`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Nome', 'Nascimento', 'Estado', 'Cidade', 'Bairro', 'Local de vota&#231;&#227;o', 'Indica&#231;&#227;o', ];
	$x->ColFieldName = ['Nome', 'DataN', 'Estado', 'Cidade', 'Bairro', 'local', 'indicacao', ];
	$x->ColNumber  = [2, 4, 7, 8, 9, 12, 14, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Eleitores_templateTV.html';
	$x->SelectedTemplate = 'templates/Eleitores_templateTVS.html';
	$x->TemplateDV = 'templates/Eleitores_templateDV.html';
	$x->TemplateDVP = 'templates/Eleitores_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Eleitores_init
	$render = true;
	if(function_exists('Eleitores_init')) {
		$args = [];
		$render = Eleitores_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Eleitores_header
	$headerCode = '';
	if(function_exists('Eleitores_header')) {
		$args = [];
		$headerCode = Eleitores_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Eleitores_footer
	$footerCode = '';
	if(function_exists('Eleitores_footer')) {
		$args = [];
		$footerCode = Eleitores_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
