<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Funcoes.php');
	include_once(__DIR__ . '/Funcoes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Funcoes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Funcoes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Funcoes`.`Id`" => "Id",
		"`Funcoes`.`Nome`" => "Nome",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Funcoes`.`Id`',
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Funcoes`.`Id`" => "Id",
		"`Funcoes`.`Nome`" => "Nome",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Funcoes`.`Id`" => "Id",
		"`Funcoes`.`Nome`" => "Nome",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Funcoes`.`Id`" => "Id",
		"`Funcoes`.`Nome`" => "Nome",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Funcoes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Funcoes_view.php';
	$x->TableTitle = 'Fun&#231;&#245;es';
	$x->TableIcon = 'resources/table_icons/draw_airbrush.png';
	$x->PrimaryKey = '`Funcoes`.`Id`';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['Nome', ];
	$x->ColFieldName = ['Nome', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Funcoes_templateTV.html';
	$x->SelectedTemplate = 'templates/Funcoes_templateTVS.html';
	$x->TemplateDV = 'templates/Funcoes_templateDV.html';
	$x->TemplateDVP = 'templates/Funcoes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Funcoes_init
	$render = true;
	if(function_exists('Funcoes_init')) {
		$args = [];
		$render = Funcoes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Funcoes_header
	$headerCode = '';
	if(function_exists('Funcoes_header')) {
		$args = [];
		$headerCode = Funcoes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Funcoes_footer
	$footerCode = '';
	if(function_exists('Funcoes_footer')) {
		$args = [];
		$footerCode = Funcoes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
