<?php		
/*
		
Se voê deseja traduzir a sua aplicação AppGini, esse
é o lugar certo para fazer isso! No entanto, por favor
verifique este arquivo no link abaixo antes pois você
pode utilizá-lo ao invés de começar do zero:
		
https://bigprof.com/appgini/download-language-files
		
IMPORTANTE:
==========
Traduza somente as strings À DIREITA da seta (=>).

NÃO TRADUZA as strings entre colchetes ([]).
Também não taduza as strings entre os sinais < e >
e também deixe inalteradas as strings %s.
		
=====================================================
POR FAVOR OBSERVE:
==================
Quando uma nova versão do AppGini é liberada, novas
strings podem ser adicionadas ao arquivo "defaultLang.php".
Para traduzi-las, simplesmente as copie para este arquivo
("language.php") e traduza-as aqui. 
NÃO AS TRADUZA diretamente no arquivo "defaultLang.php".
=====================================================

Para evitar qualquer erro nasmensagens, por favor certifique-se de

1. Adicionar uma vírgula no final de cada linha, caso não tenha;
2. Deixe a última linha da tradução assim:
];

=====================================================
Traduzido para o Português do Brasil por (pt_BR) by Osvaldo Alencar (alencosv@gmail.com)
Instagram/Tweeter: @alencosv
AppGini 5.97 - 14/06/2021
=====================================================
*/

$Translation = [	
	'language' =>'portugu&ecirc;s',
	'quick search' =>"Busca R&aacute;pida",
	'records x to y of z' =>"Registros <FirstRecord> at&eacute; <LastRecord> de <RecordCount>",
	'filters' =>"Filtros",
	'filter' =>"Filtro",
	'filtered field' =>"Campo filtrado",
	'comparison operator' =>"Operador de Compara&ccedil;&atilde;o",
	'comparison value' =>"Valor de Compara&ccedil;&atilde;o",
	'and' =>"E",
	'or' =>"Ou",
	'equal to' =>"Igual a",
	'not equal to' =>"Diferente de",
	'greater than' =>"Maior que",
	'greater than or equal to' =>"Maior ou Igual a",
	'less than' =>"Inferior a",
	'less than or equal to' =>"Menor ou Igual a",
	'like' =>"Cont&eacute;m",
	'not like' =>"N&atilde;o Cont&eacute;m",
	'is empty' =>"Vazio",
	'is not empty' =>"N&atilde;o Vazio",
	'apply filters' =>"Aplicar Filtros",
	'save filters' =>"Salvar e Aplicar Filtros",
	'saved filters title' =>"C&oacute;digo HTML da Aplica&ccedil;&atilde;o dos Filtros",
	'saved filters instructions' =>"Copie o c&oacute;digo abaixo e cole-o em um arquivo HTML para salvar o filtro rec&eacute;m-definido para que possa voltar a ele em qualquer momento no futuro, sem ter de redefin&iacute;-lo. Voc&ecirc; pode salvar o HTML no seu computador e acessar esta exibi&ccedil;&atilde;o de tabela pr&eacute;-filtrada atrav&eacute;s dele.",
	'hide code' =>"Ocultar este c&oacute;digo",
	'printer friendly view' =>"Impress&atilde;o",
	'save as csv' =>"Salvar em formato CSV (valores separados por v&iacute;rgulas)",
	'edit filters' =>"Editar Filtros",
	'clear filters' =>"Limpar Filtros",
	'order by' =>'Ordenar por',
	'go to page' =>'Ir &agrave; P&aacute;gina:',
	'none' =>'Nenhum',
	'Select all records' =>'Selecionar Todos os Registros',
	'With selected records' =>'Com Registros Selecionados',
	'Print Preview Detail View' =>'Visualizar Detalhes',
	'Print Preview Table View' =>'Visualiza&ccedil;&atilde;o da Tabela',
	'Print' =>'Imprimir',
	'Cancel Printing' =>'Cancelar Impress&atilde;o',
	'Cancel Selection' =>'Cancelar sele&ccedil;&atilde;o',
	'Maximum records allowed to enable this feature is' =>'Quantidade m&aacute;xima de registros permitida para habilitar este recurso &eacute;',
	'No matches found!' =>'Nada encontrado!',
	'Start typing to get suggestions' =>'Comece a digitar para obter sugest&otilde;es.',
		
	// _dml.php
	'are you sure?' =>'Voc&ecirc; tem certeza que deseja Excluir este registro ?',
	'add new record' =>'Adicionar Novo Registro',
	'update record' =>'Atualizar',
	'delete record' =>'Excluir',
	'deselect record' =>'Desmarcar registro',
	"couldn't delete" =>"N&atilde;o foi poss&iacute;vel remover o registro devido &agrave; exist&ecirc;ncia de <RelatedRecords> registro(s) relacionado(s) na tabela [<TableName>]",
	'confirm delete' =>'Este registro tem <RelatedRecords> registros relacionados na tabela [<TableName>]. Deseja remov&ecirc;-lo mesmo assim ? <Delete> &nbsp; <Cancel>',
	'yes' =>'Sim',
	'no' =>'N&atilde;o',
	'pkfield empty' =>' Este &eacute; um campo chave e n&atilde;o pode estar vazio.',
	'upload image' =>'Arquivo a ser enviado:',
	'select image' =>'Selecionar',
	'remove image' =>'Remover',
	'month names' =>'Janeiro,Fevereiro,Mar&ccedil;o,Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro',
	'field not null' =>'Voc&ecirc; n&atilde;o pode deixar este campo em branco.',
	'*' =>'*',
	'today' =>'Hoje',
	'Hold CTRL key to select multiple items from the above list.' =>'Mantenha pressionada a tecla CTRL para selecionar v&aacute;rios elementos da lista acima.',
	'Save New' =>'Salvar',
	'Save As Copy' =>'Salvar Como C&oacute;pia',
	'Deselect' =>'Desmarcar',
	'Add New' =>'Adicionar',
	'Delete' =>'Excluir',
	'Cancel' =>'Cancelar',
	'Print Preview' =>'Impress&atilde;o',
	'Save Changes' =>'Salvar',
	'CSV' =>'Salvar CSV',
	'Reset Filters' =>'Todos',
	'Find It' =>'Procurar',
	'Previous' =>'Anterior',
	'Next' =>'Pr&oacute;ximo',
	'Back' =>'Voltar',
	
	// lib.php
	'select a table' =>"MENU",
	'homepage' =>"P&aacute;gina Principal",
	'error:' =>"Aten&ccedil;&atilde;o",
	'sql error:' =>"Erro de SQL:",
	'query:' =>"Instru&ccedil;&atilde;o:",
	'< back' =>"Voltar",
	"if you haven't set up" =>"Se voc&ecirc; ainda n&atilde;o configurou a base de dados, voc&ecirc; pode fazer isto clicando <a href='setup.php'>aqui</a>.",
	'file too large'=>"Erro: O arquivo enviado excede o tamanho m&aacute;ximo permitido que &eacute; de <MaxSize> KB",
	'invalid file type'=>"Erro: Este tipo de arquivo n&atilde;o &eacute; permitido. Somente arquivos <FileTypes> podem ser enviados",
	
	// setup.php
	'goto start page' =>"Ir &agrave; p&aacute;gina inicial",
	'no db connection' =>"N&atilde;o foi poss&iacute;vel estabelecer uma conex&atilde;o &agrave; base de dados.",
	'no db name' =>"N&atilde;o foi poss&iacute;vel acessar o banco de dados'<dbname>' neste servidor.",
	'provide connection data' =>"Por favor, forne&ccedil;a as seguintes informa&ccedil;&otilde;es para se conectar &agrave; base de dados:",
	'mysql server' =>"Servidor (host) MySQL",
	'mysql username' =>"Usu&aacute;rio (username) do MySql",
	'mysql password' =>"Senha (password) do usu&aacute;rio do MySQL",
	'mysql db' =>"Nome da base de dados (database name)",
	'connect' =>"Conex&atilde;o",
	'couldnt save config' =>"N&atilde;o foi poss&iacute;vel salvar os dados da conex&atilde;o no'config.php'.<br />Por favor, verifique se a pasta:<br />'".dirname(__FILE__)."'<br />&eacute; grav&aacute;vel (chmod 775 ou chmod 777).",
	'setup performed' =>"O programa de instala&ccedil;&atilde;o ja foi executado",
	'delete md5' =>"Para executar a instala&ccedil;&atilde;o novamente, voc&ecirc; deve excluir o arquivo'setup.md5'.",
	'table exists' =>"A tabela <b><TableName></b> j&aacute; existe e cont&eacute;m <NumRecords> registros.",
	'failed' =>"Falhou",
	'ok' =>"Ok",
	'mysql said' =>"MySQL retornou a mensagem:",
	'table uptodate' =>"Tabela atualizada.",
	'couldnt count' =>"N&atilde;o foi poss&iacute;vel contar os registros da tabela <b><TableName></b>",
	'creating table' =>"Criando a tabela <b><TableName></b> ...",
	
	// separateDVTV.php
	'please wait' =>"Por favor, aguarde.",
	
	// _view.php
	'tableAccessDenied'=>"Conex&atilde;o interrompida por motivo de seguran&ccedil;a. Por favor, tente um novo acesso ou entre em contato com o administrador.",
	
	// incCommon.php
	'not signed in'=>"Voc&ecirc; n&atilde;o est&aacute; conectado.",
	'sign in'=>"Entrar",
	'signed as'=>"Acesso:",
	'sign out'=>"Sair",
	'admin setup needed'=>"Configura&ccedil;&atilde;o pelo administrador &eacute; necess&aacute;ria. Por favor, fa&ccedil;a o login no <a href=admin/>painel de administra&ccedil;&atilde;o</a> e configure o ambiente.",
	'db setup needed'=>"O m&oacute;dulo de instala&ccedil;&atilde;o ainda n&atilde;o foi executado. Por favor, acesse a <a href=setup.php>p&aacute;gina de configura&ccedil;&atilde;o</a> primeiro.",
	'new record saved'=>"Novo registro foi salvo com sucesso.",
	'record updated'=>"Registro atualizado com sucesso.",
	
	// index.php
	'admin area'=>"Administra&ccedil;&atilde;o",
	'login failed'=>"Sua tentativa de login anterior falhou. Por favor, tente novamente.",
	'sign in here'=>"Acesso",
	'remember me'=>"Lembrar-me",
	'username'=>"Usu&aacute;rio (CPF - Somente n&uacute;meros)",
	'password'=>"Senha",
	'go to signup'=>"Novo usu&aacute;rio ? <br />&nbsp; <a href=membership_signup.php>Cadastre-se aqui</a>",
	'forgot password'=>"Esqueceu sua senha ? <a href=membership_passwordReset.php>Clique aqui</a>",
	'browse as guest'=>"<b><a href=index.php>Acessar como visitante</a></b>",
	'no table access'=>"Voc&ecirc; n&atilde;o tem permiss&atilde;o para accessar a nenhuma pagina. Por favor fa&ccedil;a seu login antes.",
	'signup'=>"Cadastro",
	
	// checkMemberID.php
	'user already exists'=>"CPF <memberID> j&aacute; cadastrado. <a href=login.php>Fa&ccedil;a o seu login</a> ou <a href=membership_passwordReset.php>Recupere aqui a sua senha</a>",
	'username invalid' =>'CPF inv&aacute;lido. Corrija, por favor.',
	'user available'=>"CPF v&aacute;lido",
	'empty user'=>"Por favor insira o seu CPF de login na primeira caixa abaixo e depois clique no bot&atilde;o para'verificar a disponibilidade'.",
	
	// membership_thankyou.php
	'thanks'=>"Obrigado por registrar-se!",
	'sign in no approval'=>"Se voc&ecirc; escolheu um grupo que n&atilde;o requer aprova&ccedil;&atilde;o do administrador, voc&ecirc; pode logar-se agora acessando <a href=index.php?signIn=1>aqui</a>.",
	'sign in wait approval'=>"Se voc&ecirc; escolheu um grupo que requer aprova&ccedil;&atilde;o do administrador, por favor aguarde um e-mail de confirma&ccedil;&atilde;o.",
	
	// membership_signup.php
	'password invalid'=>"Voc&ecirc; deve fornecer uma senha v&aacute;lida de quatro caracteres ou mais e sem espa&ccedil;os. Por favor, volte e digite uma senha v&aacute;lida",
	'password no match'=>"A senha repetida n&atilde;o confere. Por favor, verifique novamente.",
	'username exists'=>"Este usu&aacute;rio j&aacute; existe. Por favor, retorne e escolha um diferente.",
	'email invalid'=>"Endere&ccedil;o de e-mail &eacute; inv&aacute;lido. Por favor, corrija-o.",
	'email exist'=>"Este e-mail j&aacute; existe.",
	'cpf invalido'=>"CPF Inv&acute;lido",
	'cpf exist'=>"CPF J&aacute; cadastrado",
	'group invalid'=>"Grupo inv&aacute;lido. Por favor, retorne e corrija a sua sele&ccedil;&atilde;o.",
	'sign up here'=>"Cadastro",
	'registered? sign in'=>"J&aacute; &eacute; cadastrado? <a href=index.php?signIn=1>Clique aqui</a>.",
	'sign up disabled'=>"Desculpe! Novos registros foram desabilitados pelo administrador. Por favor, tente em outra ocasi&atilde;o.",
	'check availability'=>"Verificar se este nome de usu&aacute;rio est&aacute; dispon&iacute;vel",
	'confirm password'=>"Confirme a senha",
	'email'=>"E-mail:",
	'group'=>"Classifica&ccedil;&atilde;o:",
	'groups *'=>"Grupos marcados com um asterisco(*) dependem de aprova&ccedil;&atilde;o da administra&ccedil;&atilde;o. Aguarde nosso email de confirma&ccedil;&atilde;o",
	'sign up'=>"Cadastrar-se",
	
	// membership_passwordReset.php
	'password reset'=>"Reset de Senha",
	'password reset details'=>"Informe o seu CPF ou email. Enviaremos um link para que voc&ecirc; possa gerar um nova senha.",
	'password reset subject'=>"Recupere Sua Senha",
	'password reset message'=>"Caro Usu&aacute;rio, \n Se voc&ecirc; requisitou o reset/altera&ccedil;&atilde;o de sua senha, por favor click neste link: \n <ResetLink> \n\n Caso Voc&ecirc; nao tenha requisitado o reset/altera&ccedil;&atilde;o de sua senha, Ignore esta Mensagem. \n\n Sauda&ccedil;&otilde;es.",
	'password reset ready'=>"Um Email contendo instru&ccedil;&otilde;es para efetuar o Reset de sua senha foi enviado ao seu email cadastrado. Por favor, verifique a <strong>caixa de entrada</strong>. Caso n&atilde;o o localize, verifique a <strong>caixa de spam</strong> e adicione o nosso email &agrave; sua lista de emails confi&aacute;veis. Siga as instru&ccedil;&otilde;es contidas neste email.<br /><br />Se voc&ecirc; n&atilde;o receber este email em at&eacute; 5 minutos, tente resetar sua senha novamente, e tenha certeza que entrou com seu usu&aacute;rio ou email correto.",
	'password reset invalid'=>"Usu&aacute;rio ou senha inv&aacute;lido. <a href=membership_passwordReset.php>Tente novamente</a>, ou <a href=index.php>retorne a p&aacute;gina inicial</a>.",
	'password change'=>"Trocar Senha",
	'new password'=>"Nova Senha",
	'password reset done'=>"Sua senha foi alterada com sucesso. Voc&ecirc; pode <a href=index.php?signOut=1>logar-se com a nova senha aqui</a>.",
	
	'Loading ...'=>'Carregando...',
	'No records found'=>'Nenhum registro encontrado',
	'You can add children records after saving the main record first'=>'Voc&ecirc; pode adicionar registros vinculados ap&oacute;s gravar o registro principal primeiro',
	
	'ascending' =>'Crescente',
	'descending' =>'Decrescente',
	'then by' =>'Em seguida por',
	
	// membership_profile
	'Legend' =>'Legenda',
	'Table' =>'M&oacute;dulo',
	'Edit' =>'Editar',
	'View' =>'Visualizar',
	'Only your own records' =>'Registros Pessoais',
	'All records owned by your group' =>'Registros do Grupo',
	'All records' =>'Todos os Registros',
	'Not allowed' =>'N&atilde;o permitido',
	'Your info' =>'Seus Dados',
	'Hello user' =>'Ol&aacute; %s!',
	'Your access permissions' =>'Permiss&otilde;es de Acesso',
	'Update profile' =>'Atualizar Perfil',
	'Update password' =>'Nova Senha',
	'Change your password' =>'Cadastrar Nova Senha',
	'Old password' =>'Senha anterior',
	'Password strength: weak' =>'For&ccedil;a da senha: Fraca',
	'Password strength: good' =>'For&ccedil;a da senha: Boa',
	'Password strength: strong' =>'For&ccedil;a da senha: Forte',
	'Wrong password' =>'Senha Incorreta',
	'Your profile was updated successfully' =>'Seu perfil foi atualizado com sucesso',
	'Your password was changed successfully' =>'Sua senha foi alterada com sucesso',
	'Your IP address' =>'IP de Acesso: ',
	
	/* Adicionado no AppGini 4.90 */
	'Records to display' =>'Registros para exibir',
	
	/* Adicionado no AppGini 5.10 */
	'Setup Data' =>'Informa&ccedil;&otilde;es de Setup',
	'Database Information' =>'Informa&ccedil;&oacute;es do Banco de Dados',
	'Admin Information' =>'Informa&ccedil;&otilde;es do Administrador',
	'setup intro 1' =>'Parece que n&atilde;o h&aacute; um arquivo de configura&ccedil;&atilde;o valido. Ele &eacute; necess&aacute;rio para que a aplica&ccedil;&atilde;o funcione.<br><br>Este setup ir&aacute; lhe ajudar a criar este arquivo. Mas em alguns servidores isto pode n&atilde;o funcionar. Neste caso, Voc&ecirc; vai precisar ajustar as permiss&otilde;es de pastas manualmente, ou criar o arquivo de configura&ccedil;&atilde;o manualmente.',
	'setup intro 2' =>'Bem-vindo ao sua nova aplica&ccedil;&atilde;o AppGini! Antes de come&ccedil;ar, precisamos de algumas informa&ccedil;&otilde;es sobre seu Banco de Dados. Voc&ecirc; vai precisar saber do seguinte antes de prosseguirmos:<ol><li>Endere&ccedil;o do Servidor do Banco de Dados(host)</li><li>Nome do Banco de Dados</li><li>Nome do Usu&aacute;rio do Banco de Dados</li><li>Senha do Banco de Dados</li></ol>Os itens acima, provavelmente, foram fornecidos pelo seu provedor de hospedagem web. Se voc&ecirc; n&atilde;o tiver essas informa&ccedil;&otilde;es, ent&atilde;o voc&ecirc; vai precisar entrar em contato com eles ou se referir a sua documenta&ccedil;&atilde;o de servi&ccedil;o antes de poder continuar. Se Voc&ecirc; estiver pronto, vamos come&ccedil;ar!',
	'setup finished' =>'<b>Successo!</b><br><br>Sua aplica&ccedil;&atilde;o AppGini foi instalada. Aqui v&atilde;o algumas sugest&otilde;es para iniciar a utiliza&ccedil;&atilde;o:',
	'setup next 1' =>'Inicie sua aplica&ccedil;&atilde;o adicionando registros, ou utilize os dados existentes se houverem.',
	'setup next 2' =>'Importe dados para a sua aplica&ccedil;&atilde;o de um arquivo CSV.',
	'setup next 3' =>'V&aacute; para a pagina do Administrador sempre que Voc&ecirc; modificar sua aplica&ccedil;&atilde;o para ajusta-la as novas altera&ccedil;&otilde;es.',
	'db_name help' =>'O nome do Banco de Dados que voc&ecirc; quer usar em sua aplica&ccedil;&atilde;o AppGini em',
	'db_server help' =>'<i>localhost</i> funciona na maioria dos Servidores. Se n&atilde;o funcionar, voc&ecirc; dever&aacute; obter informa&ccedil;&otilde;es a respeito com seu provedor de Hospedagem.',
	'db_username help' =>'Nome de Usu&aacute;rio do MySQL',
	'db_password help' =>'Senha do MySQL',
	'username help' =>'Especifique o nome do usu&aacute;rio administrador que voc&ecirc; gostaria de usar para acessar a &aacute;rea de administra&ccedil;&atilde;o. Deve ter quatro caracteres ou mais.',
	'password help' =>'Especifique uma senha forte para o acesso a area Administrativa de sua aplica&ccedil;&atilde;o.',
	'email help' =>'Digite o endere&ccedil;o de e-mail onde voc&ecirc; deseja que as notifica&ccedil;&otilde;es de administra&ccedil;&atilde;o sejam enviadas.',
	'Continue' =>'Continue ...',
	'Lets go' =>'Vamos come&ccedil;ar!',
	'Submit' =>'Enviar',
	'Hide' =>'Ocultar Ajuda',
	'Database info is correct' =>'&#10003; Informa&ccedil;&otilde;es do Banco de Dados est&atilde;o corretas !',
	'Database connection error' =>'&#10007; Erro ao conectar ao Banco de Dados !',
	'The following errors occured' =>'Ocorreram os seguintes erros',
	'failed to create config instructions' =>'Provavelmente as permiss&otilde;es das pastas est&atilde;o ajustadas para bloquear a cria&ccedil;&atilde;o de arquivos em seu servidor. N&atilde;o se preocupe ! Voc&ecirc; ainda pode criar o arquivo de configura&ccedil;&atilde;o manualmente.<br><br>Simplesmente cole o codigo a seguir em um editor de textos e salve o arquivo como"config.php", ent&atilde;o fa&ccedil;a o upload deste arquivo usando FTP ou qualquer outro meio na pasta %s em seu servidor.',
	'Only show records having filterer' =>'Somente exibir registros quando %s for %s',
	
	/* Adicionado no AppGini 5.20 */
	'You don\'t have enough permissions to delete this record' =>'Voc&ecirc; n&atilde;o tem permiss&atilde;o para remover este registro',
	'Couldn\'t delete this record' =>'N&atilde;o foi possÃvel remover este registro',
	'The record has been deleted successfully' =>'O registro foi removido com sucesso',
	'Couldn\'t save changes to the record' =>'N&atilde;o foi possÃvel gravar as altera&ccedil;&otilde;es no registro',
	'Couldn\'t save the new record' =>'N&atilde;o foi possÃvel salvar o novo registro',
	
	/* Adicionado no AppGini 5.30 */
	'More' =>'Mais',
	'Confirm deleting multiple records' =>'Confirma&ccedil;&atilde;o para remover varios registros',
	'<n> records will be deleted. Are you sure you want to do this?' =>'<n> registros ser&atilde;o removidos. Voc&ecirc; tem certeza que deseja fazer isso?',
	'Yes, delete them!' =>'Sim, pode exclu&iacute;-los!',
	'No, keep them.' =>'N&atilde;o, manter os registros.',
	'Deleting record <i> of <n>' =>'Removendo registro <i> de <n>',
	'Delete progress' =>'Progresso da Remo&ccedil;&atilde;o',
	'Show/hide details' =>'Exibir/Esconder detalhes',
	'Connection error' =>'Erro de conex&atilde;o',
	'Add more actions' =>'Adicionar mais a&ccedil;&otilde;es',
	'Update progress' =>'Progresso da Transfer&ecirc;ncia',
	'Change owner' =>'Transfer&ecirc;ncia de Propriedade',
	'Updating record <i> of <n>' =>'Transferindo registro <i> de <n>',
	'Change owner of <n> selected records to' =>'Transferindo <n> registros selecionados para',
	
	/* Adicionado no AppGini 5.40 */
	'permalink' =>'Permalink',
	'invalid provider' =>'Provedor inv&aacute;lido!',
	'invalid url' =>'URL inv&aacute;lida!',
	'cant retrieve coordinates from url' =>'N&atilde;o pude obter informa&ccedil;&otilde;es desta URL!',
	
	/* Adicionado no AppGini 5.51 */
	'maintenance mode admin notification' =>'Modo de Manuten&ccedil;&atilde;o Habilitado! Voc&ecirc; pode desabilit&aacute;-lo da p&aacute;gina de Administra&ccedil;&atilde;o.',
	'unique field error' =>'Este valor j&aacute; existe ou &eacute; inv&aacute;lido.',
	
	/* Adicionado no AppGini 5.60 */
	'show all user records from table' =>'Exibir todos os registros deste usu&aacute;rio da tabela"<tablename>"',
	'show all group records from table' =>'Exibir todos os registros deste grupo da tabela"<tablename>"',
	'email this user' =>'Email para o usu&aacute;rio',
	'email this group' =>'Email para o grupo',
	'owner' =>'Propriet&aacute;rio',
	'created' =>'Cria&ccedil;&atilde;o',
	'last modified' =>'&Uacute;ltima modifica&ccedil;&atilde;o',
	'record has no owner' =>'Este registro n&atilde;o pertence a nenhum usu&aacute;rio. Voc&ecirc; pode atribuir um usu&aacute;rio na &aacute;rea de Administra&ccedil;&atilde;o.',
	'admin-only info' =>'A Informa&ccedil;&atilde;o abaixo esta sendo exibida porque Voc&ecirc; esta conectado como Super Admin. Outros usu&aacute;rios n&atilde;o podem ver isto.',
	'discard changes confirm' =>'Descartar altera&ccedil;&otilde;es para este registro?',
	
	/* Adicionado no AppGini 5.70 */
	'hide/show columns' =>'Esconder/Exibir colunas',
	'next column' =>'Pr&oacute;xima coluna',
	'previous column' =>'Coluna anterior',
	
	/* Adicionado no AppGini 5.72 */
	'hide all' =>'Ocultar Tudo',
	'toggle' =>'Inverter',
	
	/* Adicionado no AppGini 5.73 */
	'datetimepicker locale' =>'pt_BR', // If needed, set a locale for use in datetime picker. For supported locales, type moment.locales() in your browser console.
	'account token theft warning' =>'Algu&eacute;m tentou acessar a sua conta roubando o seu token de acesso baseado em cookies. Por precau&ccedil;&atilde;o, voc&ecirc; foi desconectado e precisar&aacute; fazer um novo acesso.',
	
	/* Adicionado no AppGini 5.75 */
	'rebuild fields' =>'Corrija essa falha acessando a op&ccedil;&atilde;o Administra&ccedil;&atilde;o>Utilidades>Reconstruir campos',
	
	/* Adicionado no AppGini 5.80 */
	'group added successfully' =>'Grupo criado com sucesso',
	'group updated successfully' =>'As modifica&ccedil;&otilde;es desse grupo foram salvas com sucesso',
	'saved filter link' =>'Link do filtro salvo',
	'app documentation' =>'Documenta&ccedil;&atilde;o do App',
	'back to top' =>'Retornar para o topo',
	'check all' =>'Marcar tudo',
	'uncheck all' =>'Desmarcar tudo',
	'invert checks' =>'Inverter marca&ccedil;&atilde;o',
	'set all to x' =>'Marcar todas as op&ccedil;&otilde;es como <x>',
	
	// incHeader.php
	
	'membership management' =>"&Aacute;rea de Gest&atilde;o",
	'password mismatch' =>"Incompatibilidade de Senha",
	'error' =>'Erro',
	'invalid email' =>"Endere&ccedil;o de Email inv&aacute;lido",
	'sending mails' =>"O envio de emails poder&aacute; demorar um pouco. Por Favor, n&atilde;o feche esta p&aacute;gina at&eacute; ver a mensagem'Conclu&iacute;do'.",
	'complete step 4' =>"Por favor, complete a etapa 4, selecionando o membro que deseja transferir registros para.",
	'info' =>"Info",
	'sure move member' =>'Tem certeza de que deseja mover membro \'<MEMBER>\' e seus dados de grupo \'<OLDGROUP>\' para o grupo \'<NEWGROUP>\'?',
	'sure move data of member' =>'Tem certeza de que deseja mover os dados de membro \'<OLDMEMBER>\' do grupo \'<OLDGROUP>\' ao membro \'<NEWMEMBER>\' do grupo \'<NEWGROUP>\'?',
	'sure move all members' =>'Tem certeza de que deseja mover todos os usu&aacute;rios e os dados do grupo \'<OLDGROUP>\' para o grupo \'<NEWGROUP>\'?',
	'sure move data of all members' =>'Tem certeza de que deseja mover os dados de todos os usu&aacute;rios do grupo \'<OLDGROUP>\' para o Usu&aacute;rio \'<MEMBER>\' do grupo \'<NEWGROUP>\'?',
	'toggle navigation' =>"Toggle de Navega&ccedil;&atilde;o",
	'admin area' =>"&Aacute;rea do Administrador",
	'groups' =>"Grupos",
	'view groups' =>"Ver Grupos",
	'add group' =>"Criar Grupo",
	'edit anonymous permissions' =>"Editar Permiss&otilde;es An&ocirc;nimas",
	'members' =>"Usu&aacute;rios",
	'view members' =>"Ver Usu&aacute;rios",
	'add member' =>"Cadastrar Usu&aacute;rios",
	"view members' records" =>"Ocorr&ecirc;ncias",
	"utilities" =>"Utilidades",
	"admin settings" =>"Configura&ccedil;&otilde;es do Administrador",
	"rebuild thumbnails" =>"Reconstruir Miniaturas",
	'rebuild fields' =>"Reconstruir Campos",
	'import CSV' =>"Importar dados CSV",
	'batch transfer' =>"Assistente para transfer&ecirc;ncia de lote",
	'mail all users' =>"Enviar e-mail para os usu&aacute;rios",
	'AppGini forum' =>"F&oacute;rum AppGini",
	"user's area" =>'Retornar',
	"sign out" =>"Sair",
	"attention" =>"Aten&ccedil;&atilde;o!",
	'security risk admin' =>'Voc&ecirc; est&aacute; usando o nome de usu&aacute;rio e senha de administrador padr&atilde;o. Este &eacute; um enorme risco de seguran&ccedil;a. Por favor, altere, pelo menos, a senha de administrador nas<a href="pageSettings.php"> Configura&ccedil;&otilde;es de Administrador</a><em> imediatamente</em>.',
	'security risk' =>'Voc&ecirc; est&aacute; usando a senha de administrador padr&atilde;o. Este &eacute; um enorme risco de seguran&ccedil;a. Por favor, altere a senha de administrador nas<a href="pageSettings.php"> Configura&ccedil;&otilde;es de Administrador</a> <em>imediatamente</em>.',
	'plugins' =>'Plugins',
	
	//pageAssignOwners.php
	"assigned table records to group" =>"Atribu&iacute;do(s) <NUMBER> registros da tabela <b>'<TABLE>'</b> para o grupo <b>'<GROUP>'</b>",
	"assigned table records to group and member" =>"Atribu&iacute;do(s) <NUMBER> registros da tabela <b>'<TABLE>'</b> para o usu&aacute;rio <b>'<MEMBERID>'</b> do grupo <b>'<GROUP>'</b>",
	'data ownership assign' =>"Atribui&ccedil;&atilde;o de Propriedade",
	'records ownership done' =>"Todos os registros agora possuem propriet&aacute;rios .<br>Retornar para a <a href='pageHome.php'>P&aacute;gina Inicial</a>.",
	'select group' =>"Selecionar Grupo",
	'data ownership' =>"&Agrave;s vezes, voc&ecirc; pode ter tabelas com dados que foram inseridos antes de implementar este sistema de gest&atilde;o, ou introduzidos com outras aplica&ccedil;&otilde;es que desconhecem este mesmo sistema. Estes dados atualmente n&atilde;o t&ecirc;m donos. Esta p&aacute;gina permite que voc&ecirc; atribua grupos de propriet&aacute;rios e membros propriet&aacute;rios a esses dados.",
	"table" =>"Tabela",
	"records with no owners" =>"Registros sem propriet&aacute;rios",
	"new owner group" =>"Novo Grupo Propriet&aacute;rio",
	"new owner member" =>"Novo Usu&aacute;rio Propriet&aacute;rio*",
	"cancel" =>"Cancelar",
	"assign new owners" =>"Atribuir novos propriet&aacute;rios",
	"please wait" =>"Por favor, aguarde ...",
	"if no owner member assigned" =>'* Caso voc&ecirc; n&atilde;o atribua um membro propriet&aacute;rio agora, poder&aacute; usar o <a href="pageTransferOwnership.php">Assistente para transfer&ecirc;ncia em lote</a> posteriormente.',
	
	//pageDeleteGroup.php
	"can not delete group remove members" =>'Excluir este grupo. Por favor antes de tudo remova os membros...',
	"can not delete group transfer records" =>'Excluir este grupo. Por favor antes de tudo, transfira seus registros de dados para outro grupo...',
	
	//pageEditGroup.php
	"group exists error" =>"Erro: Nome do grupo j&aacute; existente. Voc&ecirc; deve escolher um nome de grupo &uacute;nico.",
	"group not found error" =>"Erro: Grupo n&atilde;o encontrado!",
	"edit group" =>"Editar o grupo'<GROUPNAME>'",
	"add new group" =>"Criar novo grupo",
	"anonymous group attention" =>"Aten&ccedil;&atilde;o! Este &eacute; um grupo an&ocirc;nimo.",
	"show tool tips" =>"Veja dicas sobre ferramentas, movendo o mouse sobre as op&ccedil;&otilde;es",
	"group name" =>"Nome do grupo",
	"readonly group name" =>"O nome deste grupo an&ocirc;nimo &eacute; somente leitura.",
	"anonymous group name" =>"Se voc&ecirc; nomear o grupo'<ANONYMOUSGROUP>', ele ser&aacute; considerado um grupo an&ocirc;nimo<br>que define as permiss&otilde;es de usu&aacute;rios visitantes que n&atilde;o entram no sistema.",
	"description" =>"Descri&ccedil;&atilde;o",
	"allow visitors sign up" =>'Permitir que os visitantes possam se inscrever?',
	"admin add users" =>"N&atilde;o. Somente o administrador pode adicionar usu&aacute;rios.",
	"admin approve users" =>"Sim, mas depende da aprova&ccedil;&atilde;o do administrador.",
	"automatically approve users" =>"Sim, com aprova&ccedil;&atilde;o autom&aacute;tica.",
	"group table permissions" =>"Permiss&otilde;es de tabelas para esse grupo",
	"no" =>"N&atilde;o",
	"owner" =>"Propriet&aacute;rio",
	"group" =>"Grupo",
	"all" =>"Todos",
	"insert" =>"Inserir",
	"view" =>"Ver",
	"edit" =>"Editar",
	"delete" =>"Deletar",
	"save changes" =>"Salvar altera&ccedil;&otilde;es",
	
	//pageEditMember.php
	"username error" =>"Error: Nome de usu&aacute;rio j&aacute; existe ou &eacute; inv&aacute;lido. Forne&ccedil;a um nome de usu&aacute;rio contendo 4 a 20 caracteres v&aacute;lidos..",
	"member not found" =>"Error: Membro n&atilde;o encontrado!",
	"user has special permissions" =>"Este usu&aacute;rio n&atilde;o tem permiss&otilde;es especiais que substituam suas permiss&otilde;es de grupo.",
	"user has group permissions" =>'Este utilizador possui <ahref="pageEditGroup.php?groupID=<GROUPID>">permiss&otilde;es de seu grupo</a>.',
	"set user special permissions" =>'Definir permiss&otilde;es especiais para este usu&aacute;rio',
	"sure continue" =>"Se voc&ecirc; fizer quaisquer altera&ccedil;&otilde;es a este membro e n&atilde;o salv&aacute;-los, ser&atilde;o perdidos se voc&ecirc; continuar. Voc&ecirc; tem certeza que quer continuar?",
	"edit member" =>"Editar membro <MEMBERID>",
	"add new member" =>"Cadastrar",
	"anonymous guest member" =>"Aten&ccedil;&atilde;o! Este membro &eacute; an&ocirc;nimo.",
	"admin member" =>'Aten&ccedil;&atilde;o! Este &eacute; um membro administrador. Voc&ecirc; pode mudar o nome de usu&aacute;rio, senha ou e-mail desse membro, tamb&eacute;m voc&ecirc; pode modificar nas <a href="pageSettings.php">configura&ccedil;&otilde;es do Administrador.</a>',
	"member username" =>"Nome de usu&aacute;rio Membro",
	"check availability" =>"Verificar disponibilidade",
	"read only username" =>"O nome de usu&aacute;rio do membro convidado &eacute; somente leitura.",
	"password" =>"Senha",
	"change password" =>"Digite uma senha somente se voc&ecirc; for mudar<br>a senha deste membro. Caso contr&aacute;rio, deixe este campo em branco.",
	"confirm password" =>"Confirmar senha",
	"email" =>"Email",
	"approved" =>"Aprovado?",
	"banned" =>"Proibido?",
	"comments" =>"Coment&aacute;rios",
	"back to members" =>"Voltar para usu&aacute;rios",
	"member added" =>"Usu&aacute;rio <USERNAME> adicionado com sucesso",
	
	//pageEditMemberPermissions.php
	"member permissions saved" =>"As permiss&otilde;es do usu&aacute;rio foram salvas com sucesso.",
	"member permissions reset" =>"As permiss&otilde;es do usu&aacute;rio foram redefinidas para o mesmo que o seu grupo.",
	"user table permissions" =>"As permiss&otilde;es da tabela para o usu&aacute;rio <a href='pageEditMember.php?memberID=<MEMBER>' title='View member details'><MEMBERID></a> do grupo <a href='pageEditGroup.php?groupID=<GROUPID>'  title='View group details and permissions'><GROUP></a>",
	"no member permissions" =>'O usu&aacute;rio n&atilde;o tem nenhuma permiss&atilde;o especiais. Esta lista mostra as permiss&otilde;es de seu grupo.',
	"reset member permissions" =>"Restaurar as permiss&otilde;es do Membro",
	"remove special permissions" =>'Isto remover todas as permiss&otilde;es especiais deste usu&aacute;rio e ele ter&aacute; as mesmas permiss&otilde;es que o seu grupo. Tem certeza de que quer fazer isso?',
	
	//pageEditOwnership.php
	"invalid table" =>"Tabela inv&aacute;lida.",
	"invalid primary key" =>"O valor da chave prim&aacute;ria est&aacute; inv&aacute;lida",
	"record not found" =>"Registro n&atilde;o encontrado. . . se tiver sido importado externamente, tente atribuir um propriet&aacute;rio a partir da &aacute;rea de administra&ccedil;&atilde;o.",
	"invalid username" =>"Nome de usu&aacute;rio inv&aacute;lido",
	"record not found error" =>"Erro: Registro n&atilde;o encontrado!",
	"edit Record Ownership" =>"Modificar Registro",
	"owner group" =>"Grupo: ",
	"view all records by group" =>"Ver todos os registros deste grupo",
	"owner member" =>"Usu&aacute;rio:",
	"view all records by member" =>"Ver todos os registros deste usu&aacute;rio",
	"switch record ownership" =>"Para transferir a posse desse registro para outro usu&aacute;rio de outro grupo, primeiro altere o grupo propriet&aacute;rio e salve as modifica&ccedil;&otilde;es.",
	"record created on" =>"Data do cadastro:",
	"record modified on" =>"Data da &uacute;ltima modifica&ccedil;&atilde;o:",
	"view all records of table" =>"Ver todos os registros desta tabela",
	"record data" =>"Data de registro",
	"print" =>"Imprimir",
	"could not retrieve field list" =>"N&atilde;o foi poss&iacute;vel recuperar a lista de campos da tabela'<TABLENAME>'",
	"field name" =>"Nome do campo",
	"value" =>"Valor",
	
	//pageHome.php
	"visitor sign up" =>'<a href="../membership_signup.php" target="_blank">Inscri&ccedil;&atilde;o de Visitante</a> desativada porque no momento n&atilde;o h&aacute; grupos onde possa se inscrever. Para habilitar as inscri&ccedil;&otilde;es, voc&ecirc; deve definir pelo menos um grupo.',
	"table data without owner" =>'Voc&ecirc; tem dados em uma ou mais tabelas que n&atilde;o possui um dono. Para atribuir um grupo propriet&aacute;rio para estes dados, <a href="pageAssignOwners.php"><b>Clique Aqui</b></a>.',
	"membership management homepage" =>"Gest&atilde;o do Sistema",
	"newest updates" =>"Atualiza&ccedil;&otilde;es recentes",
	"view record details" =>"Ver detalhes dos registros",
	"newest entries" =>"Cadastros recentes",
	"available add-ons" =>"Add-ons Dispon&iacute;veis",
	"more info" =>"Mais informa&ccedil;&otilde;es",
	"close" =>"Fechar",
	"view add-ons" =>"Ver todos os add-ons",
	"top members" =>"Usu&aacute;rios Mais Ativos",
	"edit member details" =>"Editar detalhes dos Usu&aacute;rios",
	"view member records" =>"Ver registros de dados dos Usu&aacute;rios",
	"records" =>"Registros",
	"members stats" =>"Resumo",
	"total groups" =>"Total de grupos",
	"active members" =>"Usu&aacute;rios Ativos",
	"view active members" =>"Ver Usu&aacute;rios ativos",
	"members awaiting approval" =>"Usu&aacute;rios aguardando aprova&ccedil;&atilde;o",
	"view members awaiting approval" =>"Ver Usu&aacute;rios que aguardam aprova&ccedil;&atilde;o",
	"banned members" =>"Usu&aacute;rios bloqueados",
	"view banned members" =>"Ver Usu&aacute;rios bloqueados",
	"total members" =>"Total de Usu&aacute;rios",
	"view all members" =>"Ver todos os Usu&aacute;rios",
	'BigProf tweets' =>'Tweets da BigProf Software',
	'follow BigProf' =>'Seguir a @bigprof',
	'loading bigprof feed' =>'Carregar feed @bigprof...',
	'remove feed' =>'Remover o feed',
	
	//pageMail.php
	"can not send mail" =>"Voc&ecirc; n&atilde;o pode enviar e-mails atualmente. O endere&ccedil;o do remetente de e-mail configurado n&atilde;o &eacute; v&aacute;lido. Por favor <a href='pageSettings.php'>primeiro corriga e</a> em seguida, tente novamente.",
	"all groups" =>"Todos os grupos",
	"no recipient" =>"N&atilde;o foi poss&iacute;vel encontrar destinat&aacute;rio. Por favor, certifique-se de fornecer um destinat&aacute;rio v&aacute;lido.",
	"invalid subject line" =>"Linha de assunto inv&aacute;lida.",
	"no recipient found" =>"N&atilde;o conseguimos encontrar destinat&aacute;rios. Por favor, certifique-se de fornecer um destinat&aacute;rio v&aacute;lido.",
	"mail queue not saved" =>"N&atilde;o foi poss&iacute;vel salvar fila de correio. Por favor, verifique se o diret&oacute;rio'<CURRDIR>' &eacute; grav&aacute;vel (chmod 755 or chmod 777).",
	"send mail" =>"Enviar mensagem de Email para um membro ou grupo.",
	"send mail to all members" =>"Voc&ecirc; est&aacute; enviando um e-mail a todos os membros. Isso pode levar muito tempo e afetar o desempenho do servidor. Se voc&ecirc; tem um grande n&uacute;mero de membros, n&atilde;o recomendamos o envio de um e-mail a todos eles de uma s&oacute; vez.",
	"from" =>"De",
	"change setting" =>"Alterar configura&ccedil;&atilde;o",
	"to" =>"Para",
	"subject" =>"Assunto",
	"message" =>"Mensagem",
	"send message" =>"Enviar Mensagem",
	
	//pagePrintRecord.php
	"record details" =>"Gest&atilde;o de Usu&aacute;rios - Detalhes dos Registros",
	'table name' =>"Tabela: <TABLENAME>",
	
	//pageRebuildFields.php
	'create or update table' =>"<b>A&ccedil;&atilde;o</b>: <i><ACTION></i> | <b>Campo</b>: <i><FIELD></i> | <b>Tabela</b>: <i><TABLE></i> | <b>Query executada</b>: <pre><QUERY></pre>",
	
	'view or rebuild fields' =>"Visualizar/Reconstruir Campos",
	'show deviations only' =>"Mostrar apenas desvios",
	'show all fields' =>"Mostrar todos os campos",
	'compare tables page' =>"Esta p&aacute;gina compara as tabelas e campos estrutura/esquema como projetado no aplicativo. A estrutura banco de dados real permite voc&ecirc; corrigir quaisquer desvios.",
	'field' =>"Campo",
	'AppGini definition' =>"Defini&ccedil;&otilde;es do <b>AppGini</b>",
	'database definition' =>"Defini&ccedil;&otilde;es atuais do banco de dados",
	'table name title' =>"Tabela <TABLENAME>",
	'does not exist' =>"N&atilde;o Existe!",
	'create field' =>"Criar o campo, executando uma consulta ADD COLUMN.",
	'create it' =>"Criar",
	'fix field' =>"Corrigir o campo executando a query ALTER COLUMN tornando a sua defini&ccedil;&atilde;o igual a do <b>aplicativo</b>.",
	'fix it' =>"Corrigir",
	'field update warning' =>"PERIGO!! Em alguns casos, isto pode resultar em perda de dados. Voc&ecirc; ainda deseja continuar?",
	'no deviations found' =>"Nenhum desvio encontrado. Todos os campos est&atilde;o OK!",
	'error fields' =>"Encontrado(s) <CREATENUM> campo(s) n&atilde;o-existente(s) que precisa(m) ser criado(s).<br>Existe(m) <UPDATENUM> campo(s) que possivelmente precisa(m) atualizados.",
	
	//pageRebuildThumbnails.php
	'rebuild thumbnails' =>"Reconstruir Miniaturas",
	'thumbnails utility' =>"Use este utilit&aacute;rio se voc&ecirc; tiver um ou mais campos de imagem em uma tabela que n&atilde;o tem miniaturas ou com miniaturas com dimens&otilde;es incorretas.",
	'rebuild thumbnails of table' =>"Reconstruir miniaturas da Tabela",
	'rebuild' =>"Reconstruir",
	'rebuild thumbnails of table_name' =>"Reconstruindo miniaturas da tabela'<i><TABLENAME></i>'...",
	'do not close page message' =>"N&atilde;o feche esta p&aacute;gina at&eacute; ver uma mensagem de confirma&ccedil;&atilde;o de que todas as miniaturas foram constru&iacute;dos.",
	'rebuild thumbnails status' =>"Status: Miniaturas sendo reconstruÃdas. Aguarde...",
	'building field thumbnails' => "Reconstru&ccedil;&atilde;o de miniaturas para o campo'<i><FIELD></i>'...",
	'done' =>"Feito.",
	'finished status' =>"Status: Finalizado. Voc&ecirc; j&aacute; pode fechar esta p&aacute;gina.",
	
	//pageSender.php
	'invalid mail queue' =>"Fila de email inv&aacute;lida.",
	'sending message failed' =>"Envio de mensagem para'<EMAIL>': Falhou!",
	'sending message ok' =>"Envio de mensagem para'<EMAIL>': Sucesso!",
	'done!' =>"Resultado do Envio",
	'close page' =>"Voc&ecirc; pode fechar esta p&aacute;gina agora ou navegar para outra p&aacute;gina.",
	'mail log' =>"Log de email:",
	
	//pageSettings.php
	'invalid security token' =>'Token de seguran&ccedil;a inv&aacute;lido! Por favor <a href="pageSettings.php">recarregar a p&aacute;gina</a> e tente novamente.',
	'unique admin username error' =>"O novo nome de usu&aacute;rio administrador j&aacute; est&aacute; tomada por outro membro. Por favor, verifique se o novo nome de usu&aacute;rio administrador &eacute; &uacute;nica.",
	'unique anonymous username error' =>'O novo nome de usu&aacute;rio an&ocirc;nimo j&aacute; est&aacute; tomada por outro membro. Por favor, certifique-se o nome de usu&aacute;rio fornecido &eacute; exclusivo.',
	'unique anonymous group name error' =>'O nome do novo grupo an&ocirc;nimo j&aacute; est&aacute; em uso por outro grupo. Por favor, certifique-se o nome do grupo fornecido &eacute; exclusivo.',
	'admin password mismatch' =>'Senha de Administrador n&atilde;o confere. Confirme a senha.',
	'invalid sender email' =>'E-mail do remetente est&aacute; inv&aacute;lido".',
	'errors occurred' =>"Os seguintes erros ocorreram:",
	'go back' =>'Por Favor <a href="pageSettings.php" onclick="history.go(-1); return false;">volte</a> para corrigir o(s) erro(s) acima e tente novamente.',
	'record updated automatically' =>"Registro atualizado automaticamente <DATE>",
	'admin settings saved' =>"Configura&ccedil;&otilde;es salvas com sucesso.<br>Retornar para <a href=\"pageSettings.php\">configura&ccedil;&otilde;es do administrador</a>.",
	'admin settings not saved' =>"As configura&ccedil;&otilde;es de administrador n&atilde;o foram salvas com sucesso. motivo da falha: <ERROR><br>volta para <a href=\"pageSettings.php\" onclick=\"history.go(-1); return false;\">configura&ccedil;&otilde;es de administador</a>.",
	'show tool tips' =>'Exibir dicas das ferramentas ao passar o mouse sobre as op&ccedil;&otilde;es',
	'admin username' =>"Nome de usu&aacute;rio do Administrador",
	'admin password' =>"Senha do administrador",
	'change admin password' =>"Digite uma senha somente se voc&ecirc; deseja alterar a senha de administrador.",
	'sender email' =>"Email do remetente",
	'sender name and email' =>"Nome do Remetente e e-mail usado no campo 'Para' ao enviar",
	'email messages' =>"mensagens de e-mail para grupos ou usu&aacute;rios.",
	'admin notifications' =>"Notifica&ccedil;&otilde;es do administrador",
	'no email notifications' =>"N&atilde;o enviar notifica&ccedil;&atilde;o de e-mail para o administrador.",
	'member waiting approval' =>"Notificar o administrador somente quando um novo usu&aacute;rio estiver aguardando aprova&ccedil;&atilde;o.",
	'new sign-ups' =>"Notificar o administrador todas as novas inscri&ccedil;&otilde;es.",
	'sender name' =>"Nome do remetente",
	'members custom field 1' =>"Campo personalizado 1",
	'members custom field 2' =>"Campo personalizado 2",
	'members custom field 3' =>"Campo personalizado 3",
	'members custom field 4' =>"Campo personalizado 4",
	'member approval email subject' =>"Assunto do email",
	'member approval email subject control' =>"Quando o administrador aprova um usu&aacute;rio, o mesmo recebe uma notifica&ccedil;&atilde;o por e-mail. Defina o t&iacute;tulo da mensagem no campo acima e no campo abaixo defina a mensagem.",
	'member approval email message' =>"Mensagem de aprova&ccedil;&atilde;o",
	'MySQL date' =>"String de Formata&ccedil;&atilde;o MySQL: <br>Data",
	'MySQL reference' =>'Por favor, consulte <a href="http://dev.mysql.com/doc/refman/5.0/en/date-and-time-functions.html#function_date-format" target="_blank">a refer&ecirc;ncia MySQL</a> para poss&iacute;veis formatos.',
	'PHP short date' =>"String de Formata&ccedil;&atilde;o PHP: <br>Data Curta",
	'PHP manual' =>'Por favor, consulte <a href="http://www.php.net/manual/en/function.date.php" target="_blank">o Manual do PHP </a> para poss&iacute;veis formatos.',
	'PHP long date' =>"String de Formata&ccedil;&atilde;o PHP: <br>Data Longa",
	'groups per page' =>"Grupos por p&aacute;gina",
	'members per page' =>"Usu&aacute;rio por p&aacute;gina",
	'records per page' =>"Registros por p&aacute;gina",
	'default sign-up mode' =>"Modo de inscri&ccedil;&atilde;o padr&atilde;o para novos grupos",
	'no sign-up allowed' =>"Nenhum inscri&ccedil;&atilde;o permitida. Apenas o administrador pode adicionar membros.",
	'admin approve members' =>"Inscri&ccedil;&atilde;o permitida, mas o administrador deve aprovar membros.",
	'automatically approve members' =>"Inscri&ccedil;&atilde;o permitida e automaticamente aprovada.",
	'anonymous group' =>"Nome do grupo<br>an&ocirc;nimo",
	'anonymous user name' =>"Nome do usu&aacute;rio<br>an&ocirc;nimo.",
	'hide twitter feed' =>"Esconder feed do Twitter<br>na p&aacute;gina inicial do administrador?",
	'twitter feed' =>"Nosso feed do Twitter ajuda a mant&ecirc;-lo informado sobre as nossas &uacute;ltimas not&iacute;cias, recursos &uacute;teis, novos lan&ccedil;amentos, e muitas outras dicas.",
	
	//pageTransferOwnership.php
	'invalid source member' =>"O usu&aacute;rio selecionado &eacute; de origem inv&aacute;lida.",
	'invalid destination member' =>"O usu&aacute;rio selecionado possui um destino inv&aacute;lido.",
	'moving member' =>"Mover o usu&aacute;rio'<MEMBERID>' e os seus dados do Grupo'<SOURCEGROUP>' para o Grupo'<DESTINATIONGROUP>' ...",
	'data records transferred' =>"O usu&aacute;rio'<MEMBERID>' agora pertence ao grupo'<NEWGROUP>'. registros de dados transferidos: <DATARECORDS>.",
	'moving data' =>"Mover os dados do usu&aacute;rio'<SOURCEMEMBER>' do Grupo'<SOURCEGROUP>' o Membro'<DESTINATIONMEMBER>' para o Grupo'<DESTINATIONGROUP>' ...",
	'member records status' =>"O usu&aacute;rio'<SOURCEMEMBER>' do Grupo'<SOURCEGROUP>' possu&iacute; <DATABEFORE> dados de registros. <TRANSFERSTATUS> do usu&aacute;rio'<DESTINATIONMEMBER>' do Grupo'<DESTINATIONGROUP>'.",
	'moving all group members' =>"Mover todos os usu&aacute;rio e os dados do grupo'<SOURCEGROUP>' para o Grupo'<DESTINATIONGROUP>' ...",
	'failed transferring group members' =>"Falha na opera&ccedil;&atilde;o . Nunhum usu&aacute;rio foi transferido do grupo'<SOURCEGROUP>' para'<DESTINATIONGROUP>'.",
	'group members transferred' =>"Todos os usu&aacute;rios do grupo'<SOURCEGROUP>' agora pertencem ao grupo'<DESTINATIONGROUP>'.",
	'failed transfer data records' =>"N&atilde;o foi poss&iacute;vel transferir os registros de dados.",
	'data records were transferred' =>"<DATABEFORE> registros foram transferidos com sucesso!",
	'moving group data to member' =>"Mover dados de todos os usu&aacute;rios do grupo'<SOURCEGROUP>' para o usu&aacute;rio'<DESTINATIONMEMBER>' do Grupo'<DESTINATIONGROUP>' ...",
	'moving group data to member status' =>"<NUMBER> regitros foram transferidos a partir do grupo'<SOURCEGROUP>' para o usu&aacute;rio'<DESTINATIONMEMBER>' do Grupo'<DESTINATIONGROUP>'",
	'status' =>"STATUS:",
	'batch transfer link' =>'Para repetir a mesma transfer&ecirc;ncia novamente, voc&ecirc; pode <a href="pageTransferOwnership.php?sourceGroupID=<SOURCEGROUP>&amp;sourceMemberID=<SOURCEMEMBER>&amp;destinationGroupID=<DESTINATIONGROUP>&amp;destinationMemberID=<DESTINATIONMEMBER>&amp;moveMembers=<MOVEMEMBERS>">guardar ou copiar este link</a>.',
	'ownership batch transfer' =>"Transfer&ecirc;ncia de propriedade de lote.",
	'step 1' =>"PASSO 1:",
	'batch transfer wizard' =>"O assistente de transfer&ecirc;ncia em lote permite a transfer&ecirc;ncia de registros de dados de um ou de todos os usu&aacute;rios de um grupo (O <i>grupo de origem</i>) para um usu&aacute;rio de um outro grupo (O <i>membro de destino</i> do <i>grupo de destino</i>)",
	'source group' =>"Grupo de origem",
	'update' =>"Atualizar",
	'next step' =>"pr&oacute;ximo passo",
	'group statistics' =>"Este grupo tem <MEMBERS> usu&aacute;rios, e <RECORDS> registros de dados.",
	'step 2' =>"PASSO 2:",
	'source member message' =>"O usu&aacute;rio de origem pode ser um membro ou todos os membros do grupo de origem.",
	'source member' =>"Membro de origem",
	'all group members' =>"Todos os membros do grupo'<GROUPNAME>'",
	'member statistics' =>"Este membro tem <RECORDS> dados registrados.",
	'step 3' =>"PASSO 3:",
	'destination group message' =>"O grupo de destino pode ser o mesmo ou diferente do grupo de origem. Apenas os grupos que t&ecirc;m membros est&atilde;o listados abaixo.",
	'destination group' =>"Grupo de destino",
	'step 4' =>"PASSO 4:",
	'destination member message' =>"O membro de destino ser&aacute; o novo propriet&aacute;rio dos registros de dados do membro de origem.",
	'destination member' =>"Destino do Membro",
	'begin transfer' =>"Iniciar Transfer&ecirc;ncia",
	'move records' =>"Voc&ecirc; poderia mover registros do membro (s) de origem para um membro do grupo de destino, ou mover o membro de origem (s), juntamente com os seus registros de dados ao grupo de destino.",
	'move data records to member' =>"Mover registros de dados para este membro:",
	'move source member to group' =>"Mover origem de Membro e todos os seus registos de dados para o'<GROUPNAME>' grupo.",
	
	//pageUploadCSV.php
	'file not found error' =>"Error: Arquivos'<FILENAME>' n&atilde;o encontrados.",
	'preview and confirm CSV data' =>"Pr&eacute;-visualizar os dados CSV em seguida, confirme para import&aacute;-lo ...",
	'display csv file rows' =>"Exibindo as primeiras 10 linhas do arquivo CSV ...",
	'change CSV settings' =>'Alterar configura&ccedil;&otilde;es de CSV',
	'import CSV data' =>'Confirmar e dados de importa&ccedil;&atilde;o CSV &gt;',
	'apply CSV settings' =>'Confirmar dados de importa&ccedil;&atilde;o CSV',
	'importing CSV data' =>'Importar dados CSV ...',
	'start at estimated record' =>"A partir do registro <RECORDNUMBER> de <RECORDS> registros totais estimados ...",
	'table backed up' =>"Backup da tabela'<TABLE>' salva como'<TABLENAME>'.",
	'table backup not done' =>"Tabela'<TABLE>' est&aacute; vazia, ent&atilde;o nenhum backup foi feito.",
	'importing batch' =>'Importat LOTE <BATCH> de <BATCHNUM>:',
	'ok' =>'Ok',
	'records inserted or updated successfully' =>"<RECORDS> registros inseridos / atualizados em <SECONDS> segundos.",
	'mission accomplished' =>"Miss&atilde;o cumprida!",
	'assign a records owner' =>"Atribuir um propriet&aacute;rio para os registros importados &gt;",
	'please wait and do not close' =>"Por favor aguarde. N&atilde;o feche esta p&aacute;gina...",
	'hide advanced options' =>"Ocultar op&ccedil;&otilde;es avan&ccedil;adas",
	'show advanced options' =>"Mostrar op&ccedil;&otilde;es avan&ccedil;adas",
	'import CSV to database' =>"Importar um arquivo CSV para o banco de dados",
	'import CSV to database page' =>"Esta p&aacute;gina permite fazer upload de um arquivo CSV (por exemplo, aquele gerado a partir do MS Excel) e import&aacute;-lo para uma das tabelas do banco de dados. Isto torna t&atilde;o f&aacute;cil de bulk-preencher o banco de dados com dados de outras fontes em vez de inserir manualmente cada registro &uacute;nico.",
	'populate table from CSV' =>"Esta &eacute; a tabela que voc&ecirc; deseja preencher com dados do arquivo CSV.",
	'CSV file' =>"Arquivo CSV",
	'preview CSV data' =>"Visualiza&ccedil;&atilde;o de dados CSV &gt;",
	'no table name provided' =>"Nenhum nome para tabela foi fornecido.",
	'can not open CSV' =>"N&atilde;o &eacute; poss&iacute;vel abrir arquivo CSV'<FILENAME>'.",
	'empty CSV file' =>"O arquivo CSV'<FILENAME>' est&aacute; vazio.",
	'no CSV file data' =>"O arquivo CSV'<FILENAME>' n&atilde;o tem dados para ler.",
	'field separator' =>"separador de campo",
	'default comma' =>"O padr&atilde;o &eacute; a v&iacute;rgula (,)",
	'field delimiter' =>"delimitador de campo",
	'default double-quote' =>'O padr&atilde;o &eacute; aspas (")',
	'maximum characters per line' =>"M&aacute;ximo de caracteres por linha",
	'trouble importing CSV' =>"Se voc&ecirc; tiver problemas para importar o arquivo CSV, tente aumentar esse valor.",
	'ignore lines number' =>"N&uacute;mero de linhas de ignorar",
	'skip lines number' =>"Alterar este valor se voc&ecirc; quiser pular um n&uacute;mero espec&iacute;fico de linhas no arquivo CSV.",
	'first line field names' =>"A primeira linha do arquivo cont&eacute;m nomes de campo",
	'field names must match' =>"Os nomes dos campos devem<br>exatamente<br>coincidir com aqueles no banco de dados.",
	'update table records' =>"Atualizar registros da tabela, se os seus valores de chave prim&aacute;ria coincidem com aqueles no arquivo CSV.",
	'ignore CSV table records' =>"Se n&atilde;o for marcada, os registros no arquivo CSV com os mesmos valores de chave prim&aacute;ria como aqueles na tabela<br>ser&aacute; ignorado<br>",
	'back up the table' =>"Voltar-se a tabela antes de importar dados CSV para ele.",
	
	//pageViewGroups.php
	'no matching results found' =>"Nenhum resultado correspondentes foram encontrados.",
	'search groups' =>"Pesquisar Grupos",
	'find' =>"Buscar",
	'reset' =>"Restaurar",
	'members count' =>"Quant. Usu&aacute;rios",
	'Edit group' =>"Editar Grupo",
	'confirm delete group' =>"Tem a certeza que pretende eliminar completamente esse grupo?",
	'delete group' =>"Excluir Grupo",
	'view group records' =>"Ver registros do Grupo",
	'view group members' =>"Ver Usu&aacute;rios do Grupo",
	'send message to group' =>"Enviar mensagem para grupo",
	'previous' =>"Anterior",
	'displaying groups' =>"Exibir Grupo <GROUPNUM1> a <GROUPNUM2> de <GROUPS>",
	'next' =>"pr&oacute;ximo",
	'key' =>"Legenda:",
	'edit group details' =>"Editar detalhes do grupo e permiss&otilde;es.",
	'add member to group' =>"Adicionar novo usu&aacute;rio no grupo.",
	'view data records' =>"Ver todos os registros inseridos pelos usu&aacute;rios do grupo.",
	'list group members' =>"Listar todos os usu&aacute;rios do grupo.",
	'send email to all members' =>"Enviar e-mail para os usu&aacute;rios do grupo.",
	
	//pageViewMembers.php
	'search members' =>"Procurar usu&aacute;rios <SEARCH> em <HTMLSELECT>",
	'all fields' =>"Todos os campos",
	'any' =>"Qualquer",
	'waiting approval' =>"Esperando aprova&ccedil;&atilde;o",
	'active' =>"Ativado",
	'Banned' =>"Bloqueado",
	'username' =>"Usu&aacute;rio",
	'sign up date' =>"Data do Registro",
	'Status' =>"Status",
	'Action' =>"A&ccedil;&atilde;o",
	'Edit member' =>"Editar Usu&aacute;rio",
	'sure delete user' =>"Tem certeza de que deseja excluir o usu&aacute;rio \'<USERNAME>\'?",
	'delete member' =>"Excluir Usu&aacute;rio",
	"approve this member" =>"Aprovar",
	"unban this member" =>"Desbloquear",
	"ban this member" =>"Bloquear",
	"View member records" =>"Ver registros do Usu&aacute;rio",
	"send message to member" =>"Enviar e-mail",
	'displaying members' =>"Exibindo usu&aacute;rios <MEMBERNUM1> a <MEMBERNUM2> de <MEMBERS>",
	'activate member' =>"Ativar Usu&aacute;rio",
	'ban member' =>"Bloquear Usu&aacute;rio",
	'view entered member records' =>"Ver todos os registros inseridos pelo Usu&aacute;rio.",
	'send email to member' =>"Enviar e-mail.",
	
	//pageViewRecords.php
	'data records' =>"Ocorr&ecirc;ncias",
	'show records' =>"Mostrar registros de",
	'all tables' =>"Todas as Tabelas",
	'sort records' =>"Classificar registros por",
	'date created' =>"Data Criada",
	'date modified' =>"Data modificada",
	'newer first' =>"Recentes primeiro",
	'older first' =>"mais antigos primeiro",
	'created' =>"Cadastro",
	'modified' =>"Modifica&ccedil;&atilde;o",
	'data' =>"Dados",
	'change record ownership' =>"Altera&ccedil;&atilde;o de propriedade deste registro",
	'sure delete record' =>"Tem certeza de que deseja excluir este registro?",
	'delete record' =>"Eliminar este registro",
	'displaying records' =>"Exibindo registros <RECORDNUM1> de <RECORDNUM2> at&eacute; <RECORDS>",
	
	// ------------------------------------------------------------------------
	/* Adicionado no AppGini 5.51 */
	'maintenance mode admin notification' =>'O Modo Manuten&ccedil;&atilde;o est&aacute; habilitado! Voce pode desabilitar na p&aacute;gina de Administra&ccedil;&atilde;o.',
	'maintenance mode message' =>'Modo Manuten&ccedil;&atilde;o',
	'maintenance mode' =>'Modo Manuten&ccedil;&atilde;o',
	'OFF' =>'Desligado',
	'ON' =>'Ligado',
	'enable maintenance mode?' =>'Tem certeza de que deseja habilitar o Modo de Manuten&ccedil;&atilde;o? Apenas o Administrador poder&aacute; acessar o sistema nesse modo',
	'disable maintenance mode?' =>'Tem certeza de que deseja sair do Modo de Manuten&ccedil;&atilde;o? Todos os usu&aacute;rios ter&atilde;o acesso ao sistema.',
	
	/* Adicionado no AppGini 5.60 */
	'csv file upload error' =>'Ocorreu um erro ao processar o arquivo CSV requisitado.',
	'back and retry' =>'Retorne e tente novamente',
	'upload or choose csv file' =>'Upload a CSV file or open an existing one',
	'choose csv upload' =>'Selecione um arquivo CSV para fazer o upload',
	'no file chosen yet' =>'Nenhum arquivo foi selecionado ainda',
	'start upload' =>'Iniciar upload',
	'select a table' =>'Selecione uma tabela',
	'error reading csv data' =>'Ocorreu um erro na leitura do arquivo CSV. tente resetar/redefinir as configura&ccedil;&otIlde;es CSV',
	'belongs to' =>'Pertence a',
	'skip column' =>'Pular essa coluna',
	'connection failed retrying' =>'A conex&atilde;o falhou. Tentando novamente em  <SECONDS> segundos...',
	'connection failed timeout' =>'Tempo de conex&atilde;o esgotado. Tente novamente mais tarde.',
	'sure delete csv' =>'Tem certeza de que deseja excluir o arquivo CSV [CSVFILE] do servidor?',
	'invalid csv file selected' =>'O arquivo selecionado &eacute; inv&aacute;lido. Deve ser CSV.',
	'couldnt delete csv file' =>'N&atilde;o foi poss&iacute;vel excluir o arquivo CSV.',
	'error backing up table' =>'Erro: N&atilde;o foi poss&iacute;vel fazer o backup da tabela <TABLE>.',
	'no columns selected' =>'Please select at least one column to import and make sure each selected column belongs to a UNIQUE field.',
	'csrf token expired or invalid' =>'Alguma coisa deu errado com essa p&aacute;gina. Por favor, retorne e tente novamente.',
	'back to groups' =>'Retornar Para Grupos',
	'member updated' =>"Usu&aacute;rio <USERNAME> atualizado com sucesso",
	'fix errors before submitting' =>'Please fix the highlighted errors before submitting the page!',
	
	/* Adicionado no AppGini 5.62 */
	'mail_function' =>'M&eacute;todo de envio de emails',
	'smtp_server' =>'Servidor SMTP',
	'smtp_encryption' =>'Criptografia SMTP',
	'smtp_port' =>'Porta SMTP',
	'smtp_port_hint' =>'Valores t&iacute;picos de portas SMTP: <BR>N&atilde;o-criptografada - 25;<br>Criptografia SSL - 465;<br>Criptografia TLS - 587',
	'smtp_user' =>'Login SMTP',
	'smtp_pass' =>'Senha SMTP',
	'configure mail settings' =>'Configurar o Servidor de Email',
	'display debugging info' =>'Mostrar Detalhes do Envio',
	'debugging info hint' =>'Este recurso torna-se &uacute;til, se voc&ecirc; tiver problemas de envio com a porta SMTP configurada.',
	
	/* Adicionado no AppGini 5.70 */
	'create backup file' =>'Criar Backup',
	'database backups' =>'Backups do Banco de Dados',
	'no backups found' =>'Nenhum backup localizado. Pressione a op&ccedil;&atilde;o"Criar Backup" para salvar o banco de dados.',
	'available backups' =>'Backups Dispon&iacute;veis',
	'restore backup' =>'Recuperar',
	'delete backup' =>'Excluir Backup',
	'backup restored' =>'Backup recuperado com sucesso.',
	'backup deleted' =>'Backup exclu&iacute;do com sucesso.',
	'restore error' =>'Ocorreu um erro durante a restaura&ccedil;&atilde;o do backup.',
	'backup delete error' =>'Ocorreu um erro ao excluir o backup.',
	'confirm delete backup' =>'Tem certeza que deseja excluir este backup?',
	'confirm restore' =>'Ao restaurar o seu banco de dados de um arquivo de backup, todas as informa&ccedl;&otilde;es (dados, usu&aacute;rios e senhas) ser&atilde;o sobrescritas, recuperando o estado anterior quando o backup foi realizado.\n\nDurante o processo, o Modo de Manuten&ccedil;&atilde;o ser&aacute habilitado para evitar que usu&aacute;rios conectados interfiram no processo e ser&aacute; desativado quando a restaura&ccedil;&aacute;o for conclu&iacute;da.\n\nTem certeza de que deseja continuar?',
	'confirm backup' =>'Durante o processo de backup, o modo de manuten&ccedil;&aacute;o ser&aacute; habilitado para evitar que usu&aacute;rios alterem o banco de dados. o modo manuten&ccedil;&aacute;o ser&aacute; desabilitado no final do processo.\n\nTem certeza de que deseja continuar?',
	'cant create backup folder' =>'Error: Can\'t create or write to admin/backups folder. Please check your folder permissions and ownership or contact your server administrator for help.',
	'fix all' =>'CORRIGIR TUDO',
	'backup before fix' =>'Recomenda-se fazer um backup do banco de dados antes de proceder com as corre&ccedil;&otilde;es.',
	'about backups' =>'Os backups s&atilde;o feitos usando o comando mysqldump. Se o backup n&atilde;o for criado, possivelmente o servidor n&atilde;o concedeu permiss&atilde;o.',
	
	/* Adicionado no AppGini 5.73 */
	'server status disabled' =>'O status do servidor est&aacute; desabilitado nesta aplica&ccedil;&atilde;o. Para habilitar, marque a op&ccedil;atilde;o "Allow admin access to server status page" nas Configura&ccedil;&otilde;es de Seguran&ccedil;a e recompile a aplica&ccedil;&atilde;o.',
	'server status' =>'Status do Servidor',
	'db status' =>'Status do Banco de Dados',
	'generated by' =>'Esta aplica&ccedil;&atilde;o foi gerada com o AppGini vers&atilde;o <VERSION> em <DATETIME>.',
	'column table name' =>'Nome da Tabela',
	'db storage' =>'Armazenamento do Banco de Dados',
	'column size kb' =>'Tamanho (KB)',
	'total' =>'Total',
	'php info' =>'PHP info',
	'files' =>'arquivos',
	'uploads info' =>'Resumo dos Uploads',
	'error' =>'Error',
	'add group' =>'Adicionar Grupo',
	"view members' records" =>"Visualizar Registros dos Usu&aacute;rios",
	'utilities' =>'Utilidades',
	'admin settings' =>'Configura&ccedil;&otilde;es do Administrador',
	'import CSV' =>'Importar arquivo CSV',
	'attention' =>'Aten&ccedil;&atilde;o!',
	'assigned table records to group' =>"Atribu&iacute;dos <NUMBER> registros da tabela '<TABLE>' ao grupo'<GROUP>'",
	'assigned table records to group and member' =>"Assigned <NUMBER> records of table'<TABLE>' to group'<GROUP>' , member'<MEMBERID>'",
	'records with no owners' =>'Registros sem propriet&aacute;rios',
	'new owner group' =>'Novo propriet&aacute;rio do grupo',
	'new owner member' =>'Novo propriet&aacute;rio do usu&aacute;rio*',
	'assign new owners' =>'Atribuir novos propriet&aacute;rios',
	'if no owner member assigned' =>'* Caso voc&ecirc; n&atilde;o defina um propriet&aacute;rio aqui, poder&aacute; utilizar o <a href="pageTransferOwnership.php">Assistente de Transfer&ecirc;ncia em Lote</a> depois.',
	'can not delete group remove members' =>"N&atilde;o &eacute; poss&iacute;vel remover esse grupo. Por favor, remova os membros antes.",
	'can not delete group transfer records' =>"N&atilde;o &eacute; poss&iacute;vel excluir esse grupo. Por favor, transfira os registros existentes para um outro grupo, antes...",
	'group exists error' =>'Erro: J&aacute; existe um grupo com esse nome. Escolha um outro nome que seja &uacute;nico.',
	'group not found error' =>'Erro: Grupo n&atilde;o encontrado!',
	'edit group' =>"Edi&ccedil;&atilde;o do Grupo '<GROUPNAME>'",
	'add new group' =>'Adicionar Novo Grupo',
	'anonymous group attention' =>'Aten&ccedil;&atilde;o! Esse &eacute; o Grupo An&ocirc;nimo.',
	'group name' =>'Nome do Grupo',
	'readonly group name' =>'Aqui o nome do grupo an&ocirc;nimo est&aacute; dispon&iacute;vel apenas para leitura.',
	'anonymous group name' =>"Se voc&ecirc; nomear o grupo'<ANONYMOUSGROUP>', ele ser&aacute; considerado como o grupo an&ocirc;nimo<br>que define as permiss&otilde;es dos visitantes que n&atilde;o precisam conectar-se para acessar o sistema.",
	'description' =>'Descri&ccedil;&atilde;o',
	'allow visitors sign up' =>'Permitir que visitantes se cadastrem?',
	'admin add users' =>'N&atilde;o. Somente  o administrador pode adicionar novos usu&aacute;rios.',
	'admin approve users' =>'Sim, e o administrador deve aprov&aacute;-los.',
	'automatically approve users' =>'Sim, e automaticamente os aprove.',
	'group table permissions' =>'Permiss&otilde;es de acesso &agrave;s tabelas para esse grupo',
	'group' =>'Grupo ',
	'all' =>'Tudo',
	'insert' =>'Inserir',
	'View' =>'Visualizar',
	'Delete' =>'Excluir',
	'username error' =>'Erro: Esse nome de usu&aacute;rio j&aacute; existe ou &eacute; inv&aacute;lido. Cerrifique-se de que informou um nome contendo entre 4 e 20 caracteres.',
	'member not found' =>'Erro: Usu&aacute;rio n&atilde;o localizado!',
	'user has special permissions' =>'Este usu&aacute;rio tem permiss&otilde;es especiais que superp&otilde;em-se &agrave;s permiss&otilde;es do grupo.',
	'user has group permissions' =>'Este usu&aacute;rio herda as <a href="pageEditGroup.php?groupID=<GROUPID>">permiss&otilde;es desse grupo</a>.',
	'set user special permissions' =>'Definir permiss&otilde;es especiais para esse usu&aacute;rio',
	'sure continue' =>'Se voc&ecirc; fez alguma altera&ccedil;&atilde;o no perfil desse usu&aacute;rio e n&atilde;o as salvou ainda, elas ser&atilde;o perdidas se continuar. Tem certeza de que deseja continuar?',
	'edit member' =>'Editar Usu&aacute;rio <MEMBERID>',
	'add new member' =>'Adicionar Novo Usu&aacute;rio',
	'anonymous guest member' =>'Aten&ccedil;&atilde;o! Esse &eacute; o usu&aacute;rio an&ocirc;nimo (convidado).',
	'admin member' =>'Aten&ccedil;&atilde;o! Esse &eacute; o Usu&aacute;rio Administrador. Voc&ecirc; n&atilde; pode modificar o seu nome de usu&aacute;rio, senha ou email aqui. Para tal, acesse o <a href="pageSettings.php">arquivo de configura&ccedil;&otilde;es do admin</a> page.',
	'member username' =>'Nome de Usu&aacute;rio',
	'read only username' =>'O nome de usu&aacute;rio do convidado &eacute; apenas de leitura.',
	'password' =>'Senha',
	'change password' =>"Digite uma senha somente se voc&ecirc; quiser alterar a senha desse usu&aacute;rio<br>Caso contr&aacute;rio, deixe esse campo vazio.",
	'email' =>'Email: ',
	'approved' =>'Aprovado',
	'banned' =>'Suspender',
	'comments' =>'Coment&aacute;rios',
	'back to members' =>'Retornar Para Usu&aacute;rios',
	'member added' =>'Usu&aacute;rio <USERNAME> adicionado com sucesso',
	'member permissions saved' =>'As permiss&otilde;es do usu&aacute;rio foram salvas com sucesso.',
	'member permissions reset' =>'As permiss&otilde;es do usu&aacute;rio foram reconfiguradas para as mesmas do seu grupo.',
	'user table permissions' =>"Permiss&otilde;es de tabela do usu&aacute;rio <a href='pageEditMember.php?memberID=<MEMBER>' title='Visualizar detalhes do usu&aacute;rio'><MEMBERID></a> do grupo <a href='pageEditGroup.php?groupID=<GROUPID>'  title='Visualizar detalhes e permiss&otilde;es'><GROUP></a>",
	'no member permissions' =>"Este usu&aacute;rio atualmente n&atilde;o tem nenhuma permiss&atilde;o especial. Esta lista mostra as permiss&otilde;es do seu grupo.",
	'reset member permissions' =>'Resetar permiss&otilde;es do usu&aacute;rio',
	'remove special permissions' =>'Esta a&ccedil;&atilde;o vai remover todas as permiss&otilde;es especiais desse usu&aacute;rio, que passar&atilde;o  a ser as mesmas do seu grupo. Tem certeza de que deseja continuar?',
	'invalid table' =>'Tabela Inv&aacute;lida.',
	'invalid primary key' =>'Valor de chave prim&aacute;ria inv&aacute;lido',
	'record not found' =>'Registro n&atilde;o encontrado... se ele foi importado externamente, tente atribuir um propriet&aacute;rio para o mesmo na &Aacute;rea do Administrador.',
	'invalid username' =>'Nome de Usu&aacute;rio Inv&aacute;lido',
	'record not found error' =>'Erro: Registro n&atilde;o encontrado!',
	'edit Record Ownership' =>'Editar Propriedade do Registro',
	'owner group' =>'Propriet&acute;rio do Grupo',
	'view all records by group' =>'Visualizar todos os registros para esse grupo',
	'owner member' =>'Propriet&aacute;rio do Usu&aacute;rio',
	'view all records by member' =>'Visualizar todos os registros para esse usu&aacute;rio',
	'switch record ownership' =>'Se voc&ecirc; deseja trocar a propriedade desse registro para um usu&aacute;rio de outro grupo, voc&ecirc; precisa trocar a propriedade do grupo e salvar as altera&ccedil;&otilde;es antes.',
	'record created on' =>'Registro criado em',
	'record modified on' =>'Registro modificado em',
	'view all records of table' =>'Visualizar todos os registros dessa tabela',
	'record data' =>'Dados do Registro',
	'could not retrieve field list' =>"N&atilde;o foi poss&iacute;vel recuperar a lista de campos da tabela '<TABLENAME>'",
	'field name' =>'Nome do campo',
	'value' =>'Valor',
	'visitor sign up' =>'<a href="../membership_signup.php" target="_blank">O Cadastro de Visitante</a> est&aacute; desabilitado porque n&atilde;o existe nenhum grupo dispon&iacute;vel.',
	'table data without owner' =>'Existem registros sem propriet&aacute;rios em uma ou mais tabelas. Para atribuir propriet&aacute;rios, <a href="pageAssignOwners.php">clique aqui</a>.',
	'membership management homepage' =>'Gerenciamento de Usu&aacute;rios',
	'newest updates' =>'Atualiza&ccedil;&otilde;es Mais Recentes',
	'view record details' =>'Visualizar detalhes do registro',
	'newest entries' =>'Lan&ccedil;amentos Mais Recentes',
	'available add-ons' =>'Add-ons Dispon&iacute;veis',
	'more info' =>'Mais Informa&ccedil;&otilde;es',
	'close' =>'Fechar',
	'view add-ons' =>'Visualizar todos os add-ons',
	'top members' =>'Usu&aacute;rios Mais Ativos',
	'edit member details' =>'Editar detalhes do usu&aacute;rio',
	'view member records' =>"Visualizar registros do usu&aacute;rio",
	'records' =>'registros',
	'total groups' =>'Total de Grupos',
	'active members' =>'Membros Ativos',
	'view active members' =>'Visualizar Usu&aacute;rios Ativos',
	'members awaiting approval' =>'Usu&aacute;rios aguardando aprova&ccedil;&atilde;o',
	'view members awaiting approval' =>'Visualizar usu&aacute;rios aguardando aprova&ccedil;&atilde;o',
	'banned members' =>'Membros Bloqueados',
	'view banned members' =>'Visualizar Usu&aacute;rios Bloqueados',
	'total members' =>'Total de Usu&aacute;rios',
	'view all members' =>'Visualizar todos os usu&aacute;rios',
	'BigProf tweets' =>'Tweets By BigProf Software',
	'follow BigProf' =>'Siga @bigprof',
	'loading bigprof feed' =>'Carregando os feed da @bigprof ...',
	'remove feed' =>'Remover esse feed',
	'can not send mail' =>"No momento n&atilde;o &acute; poss&iacute;cel enviar emails. O remetente de email n&atide;o encontra-se devidamente configurado. Por favor <a href='pageSettings.php'>corrija a configura&ccedil;&atilde;o</a> e tente novamente.",
	'all groups' =>'Todos os Grupos',
	'no recipient' =>"N&atilde;o foi poss&iacute;vel encontrar o destinat&aacute;rio. Por favor,certifique-se de ter informado um destinat&aacute;rio v&aacute;lido.",
	'invalid subject line' =>'Linha de Assunto Inv&aacute;lido.',
	'no recipient found' =>"N&atilde;o foi poss&iacute;vel encontrar os destinat&aacute;rios. Por favor, certifique-se de ter informado destinat&aacute;rios v&aacute;lidos.",
	'mail queue not saved' =>"N&atilde;o foi poss&iacute;vel salvar a fila de emails. Por favor, certifique-se de que o diret&ocaute;rio'<CURRDIR>' &eacute; grav&aacute;vel (chmod 755 ou chmod 777).",
	'send mail' =>'Enviar mensagem de email para um usu&aacute;rio / grupo',
	'send mail to all members' =>"Voc&ecirc; est&aacute; enviando um email para todos os usu&aacute;rios. Isto pode demorar bastante e afetar o desempenho do seu servidor. Caso voc&ecirc; tenha um grande n&uacute;mero de usu&aacute;rios,  n&atilde;o recomendamos enviar todos de uma &uacute;nica vez.",
	'from' =>'Remetente',
	'change setting' =>'Modifique essa configura&ccedil;&atilde;o',
	'to' =>'Para',
	'subject' =>'Assunto',
	'message' =>'Mensagem',
	'send message' =>'Enviar Mensagem',
	'record details' =>'Gerenciamento de Usu&aacute;rios - Detalhes dos Registros',
	'building field thumbnails' =>"Construindo miniaturas para '<i><FIELD></i>' field...",
	'data records transferred' =>"O usu&aacute;rio'<MEMBERID>' agora pertence ao grupo'<NEWGROUP>'. Registros/Dados transferidos: <DATARECORDS>.",
	'move data records to member' =>'Mover registros para esse usu&aacute;rio:',
	'apply CSV settings' =>'Atribuir configura&ccdeil;&otilde;es CSV',
	'importing batch' =>'Importando pacote <BATCH> de <BATCHNUM>:',
	'approve this member' =>'Aprovar esse usu&aacute;rio',
	'unban this member' =>'Desbloquear esse usu&aacute;rio',
	'ban this member' =>'Bloquear esse usu&aacute;rio',
	'View member records' =>"Visualizar todos os registros desse usu&aacute;rio",
	'send message to member' =>'Enviar mensagem para o usu&aacute;rio',
	'enable maintenance mode?' =>'Tem certeza de que deseja ativar o Modo de Manuten&ccedil;&atilde;o? Apenas usu&aacute;rios Administradores podem acessar o sistema neste modo!',
	'error reading csv data' =>'Ocorreu um erro dutante a leitura do arquivo CSV. Tente resetar/reconfigurar os par&acirc;metros CSV do arquivo.',
	'connection failed retrying' =>'Falha na conex&atilde;o. Tentando novamente em <SECONDS> segundos ...',
	'available backups' =>'Backups Dispon&iacute;veis',
	'php info' =>'Informa&ccedil;&otilde;es do PHP',
	'equal to' =>'Igual a',
	'are you sure?' =>'Tem certeza de que deseja excluir esse registro?',
	'*' =>'*',
	'Delete' =>'Excluir',
	'Save Changes' =>'Salvar',
	'Previous' =>'Anterior',
	'< back' =>'Retornar',
	"if you haven't set up" =>"Caso voc&ecir; n&atilde;o tenha configurado ainda o banco de dados, voc&ecirc; pode faz&ecirc;-If you haven't set up the database yet, you can do so by clicking <a href='setup.php'>here</a>.",
	'delete md5' =>"Caso queira for&ccedil;ar o setup novamente, primeiro exclua o arquivo 'setup.md5' deste diret&oacute;rio.",
	'sign in' =>'Acessar',
	'record updated' =>'As modifica&ccedil;&otilde;es foram salvas com sucesso.',
	'browse as guest' =>'<a href=index.php>Continue navegando como visitante</a>',
	'groups *' =>"Se voc&ecirc; optar por inscrever-se em um grupo marcado por asterisco (*), voc&ecirc; n&atilde;o ter&aacute; acesso ao sistema at&eacute; que o administrador lhe autorize. Voc&ecirc; receber&aacute; um email quando for aprovado",
	'sign up' =>'Cadastrar',
	'password reset' =>'P&aacute;gina de Reset de Senha',
	'Loading ...' =>'Carregando ...',
	'No records found' =>'Nenhum arquivo encontrado',
	'You can add children records after saving the main record first' =>'Voc&ecirc; pode adicionar registros filhos ap&oacute;s salvar o arquivo pai',
	'ascending' =>'Ascendente',
	'descending' =>'Descendente',
	'then by' =>'e ent&atilde;o por',
	'All records' =>'Todos os Registros',
	'email help' =>'Informe o endere&ccedil;o de email para o qual as notifica&ccedil;&otilde;es do administrador devem ser enviadas.',
	"You don't have enough permissions to delete this record" =>"Voc&ecirc; n&atilde;o tem permiss&otilde;es suficientes para excluir esse registro",
	"Couldn't delete this record" =>"N&atilde;o foi poss&iacute;vel excluir esse registro",
	"Couldn't save changes to the record" =>"N&atilde;o foi poss&iacute;vel salvar as altera&ccedil;&otilde;es do registro",
	"Couldn't save the new record" =>"N&atilde;o foi poss&iacute;vel salvar o novo registro",
	'<n> records will be deleted. Are you sure you want to do this?' =>'<n> registros ser&atilde;o exclu&iacute;dos. Tem certeza de que deseja continuar?',
	'unique field error' =>'Este valor j&aacute; existe ou &eacute; inv&aacute;lido. Por favor certifique-se de especificar um valor v&aacute;lido &uacute;nico.',
	'group updated successfully' =>'As configura&ccedil;&otilde;es do grupo foram salvas com sucesso',
	'invert checks' =>'Inverter Sele&ccedil;&atilde;o',
	'tip check csv for errors' =>'Dica: voc&ecirc; pode verificar se o seu arquivo CSV cont&eacute;m erros usando <a href="https://csvlint.io/" target="_blank">csvlint.io</a>',
	'keyboard shortcuts' =>'Atalhos do teclado',
	'keyboard shortcuts disabled' =>'Atalhos do teclado desabilitados',
	'keyboard shortcuts enabled' =>'Os atalhos do teclado est&atilde;o habilitados',
	'Enable' =>'Habilitar',
	'Disable' =>'Desabilitar',
	'display this help window' =>'Mostrar essa janela de ajuda',
	'close this window' =>'Fechar essa janela',
	'open x navigation menu' =>'Abrir menu de navega&ccedil;&atilde;o <b><x></b>',
	'user profile' =>'Perfil do Usu&aacute;rio',
	'clear search' =>'Limpar Busca',
	'navigate between sections of page' =>'Navegar entre as se&ccedil;&otilde;es da p&aacute;gina',
	'open admin info menu' =>'Abrir o menu de Informa&ccedil;&otilde;es do Admi',
	'navigate between sections of child records' =>'Navegar entre as se&ccedil;&otilde;es dos registros filhos',
	'old php version' =>"Voc&ecirc; est&aacute; usando a vers&atilde;o <PHP_VERSION> do PHP. A vers&atilde;o m&iacute;nima suportada para esse app &eacute; a <minPHP>. Por favor, fa&ccedil;a um upgrade do PHP ou instale o aplicativo em outro servidor.",
	'extension not enabled' =>"Este aplicativo n&atilde;o rodou porque a extens&atilde;o PHP <EXTENSION> n&atilde;o encontra-se habilitada. Por favor, habilite-a no arquivo php.ini, reinicie o servidor web e tente novamente.",
	'error reading csv file' =>'Erro de leitura do arquivo CSV. Por favor, certifique-se de que o arquivo existe e que as configura&ccedil;&otilde;es CSV est&atilde;o corretas.',
	'clean csv dir error' =>'N&atilde;o foi poss&iacute;vel criar ou ler/escrever no diret&oacute;rio "import-csv".',
	'Invalid import job' =>'Importa&ccedil;o inv&aacute;lida',
	'Previous record' =>'Registro Anterior',
	'Next record' =>'Pr&oacute;ximo Registro',
	'job in progress by another process' =>'Atividade em progresso em outra inst&acirc;ncia',
	'invalid clean csv file' =>'Arquivo CSV limpo inv&aacute;lido, n&atilde;o acess&iacute;vel para leitura ou ainda n&atilde;o encontra-se dispon&iacute;vel',
	'invalid csv map' =>'Mapeamento inv&aacute;lido dos campos CSV',
	'invalid field separator' =>'Separador de campos inv&aacute;lido',
	'import csv file' =>'Importar arquivo CSV',
	'import another csv file' =>'Importar outro arquivoCSV',
	'file upload error' =>'Erro no upload do arquivo',
	'to use tab' =>'Para usar TAB como separador decampo, use TAB',
	'field qualifier' =>'Qualificador de campo (wrapper)',
	'auto-detect csv columns' =>'Automaticamente detectaas colunas CSV de acordo com a tabela selecionada.',
	'nothing to import' =>'N&atilde;o existe nada a ser importado, Por favor selecione pelo menos uma coluna para importa&ccedil;&atilde;o.',
	'multiple columns mapped to same field' =>"Voc&ecirc; n&atilde;o pode importar m&uacute;ltiplas colunas para o mesmo campo.",
	'uploading in x seconds' =>'O Upload iniciar&aacute; em [SECONDS] segundos.',
	'cancel and back to csv upload' =>'Cancele e selecione um outro arquivo CSV',
	'confirm importing csv' =>'Confirme a importa&ccedil;&atilde;o dos registros CSV para a tabela selecionada',
	'total records' =>'Total de Registros',
	'imported records' =>'Registros Importados',
	'remaining' =>'Remanescentes',
	'ETA' =>'ETA',
	'import finished' =>'Importa&ccedil;&atilde;o conclu&iacute;da. Voc&ecirc; pode acessar os registros importados na tabela espec&iacute;fica.',
	'import job taking long keep page open permalink' =>'Essa tarefa de importa&ccedil;&atilde; parece estar demorando muito. Voc&ecirc; pode deixar esta p&aacute;gina aberta e realizar outra atividade em outra aba. Tamb&eacute;m recomendamos copiar o link abaixo pois assim voc&ecirc; pode continuar a importa&ccedil;&atilde;o posteriormente, caso alguma coisa d&ecirc; errado.',
	'pause' =>'Pausa',
	'resume' =>'Continuar',
	'new' =>'Novo',
	'updated' =>'Atualizado',
	'skipped' =>'Postergado',
	'fast import mode' =>'Modo R&aacute;pido de Impota&ccedil;&atilde;o (importa&ccedil;&atilde;o mais r&aacute;pida, mas estat&iacute;stica menos precisa, com atribui&ccedil;&atilde;o de propriedade feita posteriormente)',
	'assign owner for n records in table' =>'Atribuir propriet&aacute;rios para [n] registros sem propriet&aacute;rios nessa tabela',
	'no update missing pk field in csv' =>"Atualiza&ccedil;&atilde;o desabilitada pois n&atilde;o h&aacute; chave prim&aacute;ria definida no arquivo CSV, ou voc&ecirc; n&atilde;o tem acesso de edi&ccedil;&atilde;o nessa tabela.",
	'no insert update only' =>"Voc&ecirc; n&atilde; tem perimiss&atilde;o para inserir novos registros nessa tabela. Apenas atualiza&ccedil;es s&atilde;o permitidas.",
	'allow importing CSV files' =>'Permitir a importa&ccedil;&atilde;o de arquivos CSV',
	'description of import CSV files option' =>'Esta op&ccedil;&atilde;o permite que usu&aacute;rio(s) importem arquivos CSV para as tabelas onde ele(s) t&ecirc;m permiss&atilde;o para editar ou inserir.',
	'admin group attention' =>'Aten&ccedil;o! Esse &eacute; o grupo de Administradores.',
	'toggle import logs' =>'Mostra/Ocultar hist&oacute;rico de importa&ccedil;&otilde;es',
	'admin csv warning' =>'Esta p&aacute;gina ser&aacute; removida em vers&otilde;es futuras e voc&ecirc; deve utilizar a [a]nova p&aacute;gina de importa&ccedil;&atilde; CSV[/a].',
	'Jump to' =>'Saltar Para...',
	'check username availability' =>'Verifique se esse nome de usu&aacute;rio encontra-se dispon&iacute;vel',
	'try rebuild fields' =>'Voc&ecirc; pode tentar corrigir esse problema acessando &Aacute;rea do Administrador : Menu de Utilidades : Visualizar/Recosntruir Campos.',
	'click continue if slow' =>'Caso esta p&aacute;gina esteja demorando muito para carregar, [a]clique em Continuar[/a] paraavan&ccedil;ar.',
	
	 // Adicionado no 5.91
	'keyboard shorcuts reference' =>'Refer&ecirc;ncia de Atalhos do Teclado',
	
	 // Adicionado no 5.93
	'google API key' =>'Chave da API do Google',
	'google API key instructions' =>'Como obter e configurar a chave API do Google?',
	'base upload path' =>'Diret&oacute;rio Raiz do Upload',
	'base upload path change warning' =>'Caso voc&ecirc;modifique o caminho raiz do upload, os arquivos/imagens existentes ficar&atilde;o inacess&iacute;veis at&eacute; que sejam movidos para o novo diret&oacute;rio.',
	'base upload path instructions' =>'O caminho onde os arquivos/imagens enviados s&atilde;o armazenados. O caminho &eacute; definido relativo ao do aplicativo, mas voc&ecirc; pode come&ccedil;ar com <code>../</code> para especificar um caminho fora do diret&oacute;rio raiz.',
	'invalid upload path' =>'O caminho raiz especificado n&atilde.;o existe e n&atilde; p&ocirc;de ser criado..',
	'Appearance' =>'Apar&ecirc;ncia',
	'Mail' =>'E-Mail',
	'Preconfigured users and groups' =>'Usu&aacute;rios e Grupos Pr&eacute;-Configurados',
	'Application' =>'Aplica&ccedil;&atilde;o',

	// Adicionado no 5.97
	'Query logs' => 'Hist&oacute;rico das buscas',
	'Query log table does not exist' => 'Ocorreu um erro ao tentar criar a tabela appgini_query_log. Por favor certifique-se de que tem privil&eacute;gios pra criar tabelas (CREATE TABLE).',
	'slow queries' => 'Buscas lentas',
	'error queries' => 'Erro de busca',
	'date/time' => 'Data/time',
	'duration (sec)' => 'Dura&ccedil;&atilde;o (s)',
	'page address' => 'Endere&ccedil;o da P&aacute;gina',
	'query' => 'Busca',
	'page x of y' => 'P&aacute;gina <x> de <y>',
	'total # queries' => 'Total de buscas: #.',
];