<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Municipios.php');
	include_once(__DIR__ . '/Municipios_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Municipios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Municipios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Municipios`.`Id`" => "Id",
		"`Municipios`.`Nome`" => "Nome",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Municipios`.`Id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Municipios`.`Id`" => "Id",
		"`Municipios`.`Nome`" => "Nome",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Municipios`.`Id`" => "Id",
		"`Municipios`.`Nome`" => "Nome",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Municipios`.`Id`" => "Id",
		"`Municipios`.`Nome`" => "Nome",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Estado' => 'Estado', ];

	$x->QueryFrom = "`Municipios` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Municipios`.`Estado` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Municipios_view.php';
	$x->TableTitle = 'Munic&#237;pios';
	$x->TableIcon = 'resources/table_icons/google_map.png';
	$x->PrimaryKey = '`Municipios`.`Id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Nome', 'Estado', ];
	$x->ColFieldName = ['Nome', 'Estado', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Municipios_templateTV.html';
	$x->SelectedTemplate = 'templates/Municipios_templateTVS.html';
	$x->TemplateDV = 'templates/Municipios_templateDV.html';
	$x->TemplateDVP = 'templates/Municipios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Municipios_init
	$render = true;
	if(function_exists('Municipios_init')) {
		$args = [];
		$render = Municipios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Municipios_header
	$headerCode = '';
	if(function_exists('Municipios_header')) {
		$args = [];
		$headerCode = Municipios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Municipios_footer
	$footerCode = '';
	if(function_exists('Municipios_footer')) {
		$args = [];
		$footerCode = Municipios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
