<?php

// Data functions (insert, update, delete, form) for table Pessoas

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Pessoas_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Pessoas');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Nome' => Request::val('Nome', ''),
		'Estado' => Request::lookup('Estado', ''),
		'Cidade' => Request::lookup('Cidade', ''),
		'Bairro' => Request::lookup('Bairro', ''),
		'Rua' => Request::val('Rua', ''),
		'numero' => Request::val('numero', ''),
		'CEP' => Request::val('CEP', ''),
		'Contato' => Request::val('Contato', ''),
		'profissao' => Request::lookup('profissao', ''),
		'Email' => Request::val('Email', ''),
		'Midias' => Request::val('Midias', ''),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Contato'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefone': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Pessoas_before_insert
	if(function_exists('Pessoas_before_insert')) {
		$args = [];
		if(!Pessoas_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Pessoas', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Pessoas', $recID, calculated_fields()['Pessoas']);

	// hook: Pessoas_after_insert
	if(function_exists('Pessoas_after_insert')) {
		$res = sql("SELECT * FROM `Pessoas` WHERE `Id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Pessoas_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Pessoas', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Pessoas_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Pessoas_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Pessoas_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Pessoas', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Pessoas_before_delete
	if(function_exists('Pessoas_before_delete')) {
		$args = [];
		if(!Pessoas_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Eleitores
	$res = sql("SELECT `Id` FROM `Pessoas` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Eleitores` WHERE `Nome`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Pessoas_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Pessoas_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Colaboradores
	$res = sql("SELECT `Id` FROM `Pessoas` WHERE `Id`='{$selected_id}'", $eo);
	$Id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Colaboradores` WHERE `Nome`='" . makeSafe($Id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Colaboradores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Colaboradores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Pessoas_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Pessoas_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Pessoas` WHERE `Id`='{$selected_id}'", $eo);

	// hook: Pessoas_after_delete
	if(function_exists('Pessoas_after_delete')) {
		$args = [];
		Pessoas_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Pessoas' AND `pkValue`='{$selected_id}'", $eo);
}

function Pessoas_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Pessoas', $selected_id, 'edit')) return false;

	$data = [
		'Nome' => Request::val('Nome', ''),
		'Estado' => Request::lookup('Estado', ''),
		'Cidade' => Request::lookup('Cidade', ''),
		'Bairro' => Request::lookup('Bairro', ''),
		'Rua' => Request::val('Rua', ''),
		'numero' => Request::val('numero', ''),
		'CEP' => Request::val('CEP', ''),
		'Contato' => Request::val('Contato', ''),
		'profissao' => Request::lookup('profissao', ''),
		'Email' => Request::val('Email', ''),
		'Midias' => Request::val('Midias', ''),
	];

	if($data['Nome'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nome': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Contato'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefone': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Pessoas', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Pessoas_before_update
	if(function_exists('Pessoas_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Pessoas_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Pessoas', 
		backtick_keys_once($set), 
		['`Id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Pessoas_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Pessoas', $data['selectedID'], calculated_fields()['Pessoas']);

	// hook: Pessoas_after_update
	if(function_exists('Pessoas_after_update')) {
		$res = sql("SELECT * FROM `Pessoas` WHERE `Id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['Id'];
		$args = ['old_data' => $old_data];
		if(!Pessoas_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Pessoas', $selected_id);
}

function Pessoas_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Pessoas');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Pessoas', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Pessoas', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Pessoas', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Estado = Request::val('filterer_Estado');
	$filterer_Cidade = Request::val('filterer_Cidade');
	$filterer_Bairro = Request::val('filterer_Bairro');
	$filterer_profissao = Request::val('filterer_profissao');

	// populate filterers, starting from children to grand-parents
	if($filterer_Cidade && !$filterer_Estado) $filterer_Estado = sqlValue("select Estado from Municipios where Id='" . makeSafe($filterer_Cidade) . "'");
	if($filterer_Bairro && !$filterer_Cidade) $filterer_Cidade = sqlValue("select Cidade from Bairro where Id='" . makeSafe($filterer_Bairro) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Estado
	$combo_Estado = new DataCombo;
	// combobox: Cidade, filterable by: Estado
	$combo_Cidade = new DataCombo;
	// combobox: Bairro, filterable by: Cidade
	$combo_Bairro = new DataCombo;
	// combobox: profissao
	$combo_profissao = new DataCombo;

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Pessoas` WHERE `Id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Pessoas_view.php', false);
		}
		$combo_Estado->SelectedData = $row['Estado'];
		$combo_Cidade->SelectedData = $row['Cidade'];
		$combo_Bairro->SelectedData = $row['Bairro'];
		$combo_profissao->SelectedData = $row['profissao'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Estado->SelectedData = $filterer_Estado;
		$combo_Cidade->SelectedData = $filterer_Cidade;
		$combo_Bairro->SelectedData = $filterer_Bairro;
		$combo_profissao->SelectedData = $filterer_profissao;
	}
	$combo_Estado->HTML = '<span id="Estado-container' . $rnd1 . '"></span><input type="hidden" name="Estado" id="Estado' . $rnd1 . '" value="' . html_attr($combo_Estado->SelectedData) . '">';
	$combo_Estado->MatchText = '<span id="Estado-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Estado" id="Estado' . $rnd1 . '" value="' . html_attr($combo_Estado->SelectedData) . '">';
	$combo_Cidade->HTML = '<span id="Cidade-container' . $rnd1 . '"></span><input type="hidden" name="Cidade" id="Cidade' . $rnd1 . '" value="' . html_attr($combo_Cidade->SelectedData) . '">';
	$combo_Cidade->MatchText = '<span id="Cidade-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Cidade" id="Cidade' . $rnd1 . '" value="' . html_attr($combo_Cidade->SelectedData) . '">';
	$combo_Bairro->HTML = '<span id="Bairro-container' . $rnd1 . '"></span><input type="hidden" name="Bairro" id="Bairro' . $rnd1 . '" value="' . html_attr($combo_Bairro->SelectedData) . '">';
	$combo_Bairro->MatchText = '<span id="Bairro-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Bairro" id="Bairro' . $rnd1 . '" value="' . html_attr($combo_Bairro->SelectedData) . '">';
	$combo_profissao->HTML = '<span id="profissao-container' . $rnd1 . '"></span><input type="hidden" name="profissao" id="profissao' . $rnd1 . '" value="' . html_attr($combo_profissao->SelectedData) . '">';
	$combo_profissao->MatchText = '<span id="profissao-container-readonly' . $rnd1 . '"></span><input type="hidden" name="profissao" id="profissao' . $rnd1 . '" value="' . html_attr($combo_profissao->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Estado__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Estado'] : htmlspecialchars($filterer_Estado, ENT_QUOTES)); ?>"};
		AppGini.current_Cidade__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Cidade'] : htmlspecialchars($filterer_Cidade, ENT_QUOTES)); ?>"};
		AppGini.current_Bairro__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Bairro'] : htmlspecialchars($filterer_Bairro, ENT_QUOTES)); ?>"};
		AppGini.current_profissao__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['profissao'] : htmlspecialchars($filterer_profissao, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Estado_reload__RAND__) == 'function') Estado_reload__RAND__();
				<?php echo (!$allowUpdate || $dvprint ? 'if(typeof(Cidade_reload__RAND__) == \'function\') Cidade_reload__RAND__(AppGini.current_Estado__RAND__.value);' : ''); ?>
				<?php echo (!$allowUpdate || $dvprint ? 'if(typeof(Bairro_reload__RAND__) == \'function\') Bairro_reload__RAND__(AppGini.current_Cidade__RAND__.value);' : ''); ?>
				if(typeof(profissao_reload__RAND__) == 'function') profissao_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Estado_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Estado-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Estado__RAND__.value, t: 'Pessoas', f: 'Estado' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Estado"]').val(resp.results[0].id);
							$j('[id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Cidade_reload__RAND__) == 'function') Cidade_reload__RAND__(AppGini.current_Estado__RAND__.value);

							if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Pessoas', f: 'Estado' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Estado__RAND__.value = e.added.id;
				AppGini.current_Estado__RAND__.text = e.added.text;
				$j('[name="Estado"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Cidade_reload__RAND__) == 'function') Cidade_reload__RAND__(AppGini.current_Estado__RAND__.value);

				if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
			});

			if(!$j("#Estado-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Estado__RAND__.value, t: 'Pessoas', f: 'Estado' },
					success: function(resp) {
						$j('[name="Estado"]').val(resp.results[0].id);
						$j('[id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Estado__RAND__.value, t: 'Pessoas', f: 'Estado' },
				success: function(resp) {
					$j('[id=Estado-container__RAND__], [id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

					if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Cidade_reload__RAND__(filterer_Estado) {
		<?php if($fieldsAreEditable) { ?>

			$j("#Cidade-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_Estado: filterer_Estado, id: AppGini.current_Cidade__RAND__.value, t: 'Pessoas', f: 'Cidade' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Cidade"]').val(resp.results[0].id);
							$j('[id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

						if(typeof(Bairro_reload__RAND__) == 'function') Bairro_reload__RAND__(AppGini.current_Cidade__RAND__.value);

							if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_Estado: filterer_Estado, s: term, p: page, t: 'Pessoas', f: 'Cidade' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Cidade__RAND__.value = e.added.id;
				AppGini.current_Cidade__RAND__.text = e.added.text;
				$j('[name="Cidade"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

						if(typeof(Bairro_reload__RAND__) == 'function') Bairro_reload__RAND__(AppGini.current_Cidade__RAND__.value);

				if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
			});

			if(!$j("#Cidade-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Cidade__RAND__.value, t: 'Pessoas', f: 'Cidade' },
					success: function(resp) {
						$j('[name="Cidade"]').val(resp.results[0].id);
						$j('[id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

						if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Cidade__RAND__.value, t: 'Pessoas', f: 'Cidade' },
				success: function(resp) {
					$j('[id=Cidade-container__RAND__], [id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

					if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Bairro_reload__RAND__(filterer_Cidade) {
		<?php if($fieldsAreEditable) { ?>

			$j("#Bairro-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_Cidade: filterer_Cidade, id: AppGini.current_Bairro__RAND__.value, t: 'Pessoas', f: 'Bairro' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Bairro"]').val(resp.results[0].id);
							$j('[id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }


							if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_Cidade: filterer_Cidade, s: term, p: page, t: 'Pessoas', f: 'Bairro' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Bairro__RAND__.value = e.added.id;
				AppGini.current_Bairro__RAND__.text = e.added.text;
				$j('[name="Bairro"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }


				if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
			});

			if(!$j("#Bairro-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Bairro__RAND__.value, t: 'Pessoas', f: 'Bairro' },
					success: function(resp) {
						$j('[name="Bairro"]').val(resp.results[0].id);
						$j('[id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }

						if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Bairro__RAND__.value, t: 'Pessoas', f: 'Bairro' },
				success: function(resp) {
					$j('[id=Bairro-container__RAND__], [id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }

					if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function profissao_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#profissao-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_profissao__RAND__.value, t: 'Pessoas', f: 'profissao' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="profissao"]').val(resp.results[0].id);
							$j('[id=profissao-container-readonly__RAND__]').html('<span class="match-text" id="profissao-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }


							if(typeof(profissao_update_autofills__RAND__) == 'function') profissao_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Pessoas', f: 'profissao' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_profissao__RAND__.value = e.added.id;
				AppGini.current_profissao__RAND__.text = e.added.text;
				$j('[name="profissao"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }


				if(typeof(profissao_update_autofills__RAND__) == 'function') profissao_update_autofills__RAND__();
			});

			if(!$j("#profissao-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_profissao__RAND__.value, t: 'Pessoas', f: 'profissao' },
					success: function(resp) {
						$j('[name="profissao"]').val(resp.results[0].id);
						$j('[id=profissao-container-readonly__RAND__]').html('<span class="match-text" id="profissao-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }

						if(typeof(profissao_update_autofills__RAND__) == 'function') profissao_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_profissao__RAND__.value, t: 'Pessoas', f: 'profissao' },
				success: function(resp) {
					$j('[id=profissao-container__RAND__], [id=profissao-container-readonly__RAND__]').html('<span class="match-text" id="profissao-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Profissoes_view_parent]').hide(); } else { $j('.btn[id=Profissoes_view_parent]').show(); }

					if(typeof(profissao_update_autofills__RAND__) == 'function') profissao_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Pessoas_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Pessoas_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Pessoas_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Pessoas_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Pessoas_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Nome').replaceWith('<div class=\"form-control-static\" id=\"Nome\">' + (jQuery('#Nome').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Estado').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Estado_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Cidade').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Cidade_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Bairro').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Bairro_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Rua').replaceWith('<div class=\"form-control-static\" id=\"Rua\">' + (jQuery('#Rua').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#numero').replaceWith('<div class=\"form-control-static\" id=\"numero\">' + (jQuery('#numero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#CEP').replaceWith('<div class=\"form-control-static\" id=\"CEP\">' + (jQuery('#CEP').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Contato').replaceWith('<div class=\"form-control-static\" id=\"Contato\">' + (jQuery('#Contato').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#profissao').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#profissao_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Email').replaceWith('<div class=\"form-control-static\" id=\"Email\">' + (jQuery('#Email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Midias').replaceWith('<div class=\"form-control-static\" id=\"Midias\">' + (jQuery('#Midias').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Estado)%%>', $combo_Estado->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Estado)%%>', $combo_Estado->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Estado)%%>', urlencode($combo_Estado->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Cidade)%%>', $combo_Cidade->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Cidade)%%>', $combo_Cidade->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Cidade)%%>', urlencode($combo_Cidade->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Bairro)%%>', $combo_Bairro->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Bairro)%%>', $combo_Bairro->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Bairro)%%>', urlencode($combo_Bairro->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(profissao)%%>', $combo_profissao->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(profissao)%%>', $combo_profissao->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(profissao)%%>', urlencode($combo_profissao->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Estado' => ['Estados', 'Estado'], 'Cidade' => ['Municipios', 'Cidade'], 'Bairro' => ['Bairro', 'Bairro'], 'profissao' => ['Profissoes', 'Profiss&#227;o'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(Id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nome)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Estado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cidade)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Bairro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Rua)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(numero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CEP)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Contato)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(profissao)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Midias)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Obs)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(Id)%%>', safe_html($urow['Id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode($urow['Id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', safe_html($urow['Nome']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nome)%%>', html_attr($row['Nome']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode($urow['Nome']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Estado)%%>', safe_html($urow['Estado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Estado)%%>', html_attr($row['Estado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado)%%>', urlencode($urow['Estado']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cidade)%%>', safe_html($urow['Cidade']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cidade)%%>', html_attr($row['Cidade']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cidade)%%>', urlencode($urow['Cidade']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Bairro)%%>', safe_html($urow['Bairro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Bairro)%%>', html_attr($row['Bairro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Bairro)%%>', urlencode($urow['Bairro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Rua)%%>', safe_html($urow['Rua']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Rua)%%>', html_attr($row['Rua']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Rua)%%>', urlencode($urow['Rua']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(numero)%%>', safe_html($urow['numero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(numero)%%>', html_attr($row['numero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero)%%>', urlencode($urow['numero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CEP)%%>', safe_html($urow['CEP']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CEP)%%>', html_attr($row['CEP']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CEP)%%>', urlencode($urow['CEP']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Contato)%%>', safe_html($urow['Contato']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Contato)%%>', html_attr($row['Contato']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Contato)%%>', urlencode($urow['Contato']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(profissao)%%>', safe_html($urow['profissao']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(profissao)%%>', html_attr($row['profissao']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(profissao)%%>', urlencode($urow['profissao']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Email)%%>', safe_html($urow['Email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Email)%%>', html_attr($row['Email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Email)%%>', urlencode($urow['Email']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Midias)%%>', safe_html($urow['Midias']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Midias)%%>', html_attr($row['Midias']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Midias)%%>', urlencode($urow['Midias']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', safe_html($urow['Obs'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode($urow['Obs']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(Id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Nome)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Estado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cidade)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cidade)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Bairro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Bairro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Rua)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Rua)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(numero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(numero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CEP)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CEP)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Contato)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Contato)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(profissao)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(profissao)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Midias)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Midias)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Obs)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Obs)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Pessoas');
	if($hasSelectedId) {
		$jdata = get_joined_record('Pessoas', $selectedId);
		if($jdata === false) $jdata = get_defaults('Pessoas');
		$rdata = $row;
	}
	$templateCode .= loadView('Pessoas-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Pessoas_dv
	if(function_exists('Pessoas_dv')) {
		$args = [];
		Pessoas_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}