<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Profissoes.php');
	include_once(__DIR__ . '/Profissoes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Profissoes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Profissoes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Profissoes`.`id`" => "id",
		"`Profissoes`.`Profissao`" => "Profissao",
		"`Profissoes`.`Seguimento`" => "Seguimento",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Profissoes`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Profissoes`.`id`" => "id",
		"`Profissoes`.`Profissao`" => "Profissao",
		"`Profissoes`.`Seguimento`" => "Seguimento",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Profissoes`.`id`" => "ID",
		"`Profissoes`.`Profissao`" => "Profiss&#227;o",
		"`Profissoes`.`Seguimento`" => "Seguimento",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Profissoes`.`id`" => "id",
		"`Profissoes`.`Profissao`" => "Profissao",
		"`Profissoes`.`Seguimento`" => "Seguimento",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Profissoes` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Profissoes_view.php';
	$x->TableTitle = 'Profiss&#245;es';
	$x->TableIcon = 'resources/table_icons/chair.png';
	$x->PrimaryKey = '`Profissoes`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Profiss&#227;o', 'Seguimento', ];
	$x->ColFieldName = ['Profissao', 'Seguimento', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Profissoes_templateTV.html';
	$x->SelectedTemplate = 'templates/Profissoes_templateTVS.html';
	$x->TemplateDV = 'templates/Profissoes_templateDV.html';
	$x->TemplateDVP = 'templates/Profissoes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Profissoes_init
	$render = true;
	if(function_exists('Profissoes_init')) {
		$args = [];
		$render = Profissoes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Profissoes_header
	$headerCode = '';
	if(function_exists('Profissoes_header')) {
		$args = [];
		$headerCode = Profissoes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Profissoes_footer
	$footerCode = '';
	if(function_exists('Profissoes_footer')) {
		$args = [];
		$footerCode = Profissoes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
