<?php

// Data functions (insert, update, delete, form) for table Secao

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Secao_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Secao');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Numero' => Request::val('Numero', ''),
		'Cidade' => Request::lookup('Cidade', ''),
		'Bairro' => Request::lookup('Bairro', ''),
		'Zona' => Request::lookup('Zona', ''),
		'Endereco' => Request::val('Endereco', ''),
		'Local' => Request::val('Local', ''),
		'Eleitores' => Request::val('Eleitores', ''),
	];

	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Cidade'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cidade': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Bairro'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Bairro': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Zona'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Zona': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Local'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Local': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Secao_before_insert
	if(function_exists('Secao_before_insert')) {
		$args = [];
		if(!Secao_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Secao', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Secao', $recID, calculated_fields()['Secao']);

	// hook: Secao_after_insert
	if(function_exists('Secao_after_insert')) {
		$res = sql("SELECT * FROM `Secao` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Secao_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Secao', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Secao_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Secao_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Secao_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Secao', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Secao_before_delete
	if(function_exists('Secao_before_delete')) {
		$args = [];
		if(!Secao_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Eleitores
	$res = sql("SELECT `id` FROM `Secao` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Eleitores` WHERE `secao`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Secao_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Secao_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Secao` WHERE `id`='{$selected_id}'", $eo);

	// hook: Secao_after_delete
	if(function_exists('Secao_after_delete')) {
		$args = [];
		Secao_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Secao' AND `pkValue`='{$selected_id}'", $eo);
}

function Secao_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Secao', $selected_id, 'edit')) return false;

	$data = [
		'Numero' => Request::val('Numero', ''),
		'Cidade' => Request::lookup('Cidade', ''),
		'Bairro' => Request::lookup('Bairro', ''),
		'Zona' => Request::lookup('Zona', ''),
		'Endereco' => Request::val('Endereco', ''),
		'Local' => Request::val('Local', ''),
		'Eleitores' => Request::val('Eleitores', ''),
	];

	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Cidade'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cidade': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Bairro'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Bairro': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Zona'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Zona': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Local'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Local': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Secao', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Secao_before_update
	if(function_exists('Secao_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Secao_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Secao', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Secao_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Secao', $data['selectedID'], calculated_fields()['Secao']);

	// hook: Secao_after_update
	if(function_exists('Secao_after_update')) {
		$res = sql("SELECT * FROM `Secao` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Secao_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Secao', $selected_id);
}

function Secao_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Secao');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Secao', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Secao', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Secao', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Cidade = Request::val('filterer_Cidade');
	$filterer_Bairro = Request::val('filterer_Bairro');
	$filterer_Zona = Request::val('filterer_Zona');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Cidade
	$combo_Cidade = new DataCombo;
	// combobox: Bairro
	$combo_Bairro = new DataCombo;
	// combobox: Zona
	$combo_Zona = new DataCombo;

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Secao` WHERE `id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Secao_view.php', false);
		}
		$combo_Cidade->SelectedData = $row['Cidade'];
		$combo_Bairro->SelectedData = $row['Bairro'];
		$combo_Zona->SelectedData = $row['Zona'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Cidade->SelectedData = $filterer_Cidade;
		$combo_Bairro->SelectedData = $filterer_Bairro;
		$combo_Zona->SelectedData = $filterer_Zona;
	}
	$combo_Cidade->HTML = '<span id="Cidade-container' . $rnd1 . '"></span><input type="hidden" name="Cidade" id="Cidade' . $rnd1 . '" value="' . html_attr($combo_Cidade->SelectedData) . '">';
	$combo_Cidade->MatchText = '<span id="Cidade-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Cidade" id="Cidade' . $rnd1 . '" value="' . html_attr($combo_Cidade->SelectedData) . '">';
	$combo_Bairro->HTML = '<span id="Bairro-container' . $rnd1 . '"></span><input type="hidden" name="Bairro" id="Bairro' . $rnd1 . '" value="' . html_attr($combo_Bairro->SelectedData) . '">';
	$combo_Bairro->MatchText = '<span id="Bairro-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Bairro" id="Bairro' . $rnd1 . '" value="' . html_attr($combo_Bairro->SelectedData) . '">';
	$combo_Zona->HTML = '<span id="Zona-container' . $rnd1 . '"></span><input type="hidden" name="Zona" id="Zona' . $rnd1 . '" value="' . html_attr($combo_Zona->SelectedData) . '">';
	$combo_Zona->MatchText = '<span id="Zona-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Zona" id="Zona' . $rnd1 . '" value="' . html_attr($combo_Zona->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Cidade__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Cidade'] : htmlspecialchars($filterer_Cidade, ENT_QUOTES)); ?>"};
		AppGini.current_Bairro__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Bairro'] : htmlspecialchars($filterer_Bairro, ENT_QUOTES)); ?>"};
		AppGini.current_Zona__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Zona'] : htmlspecialchars($filterer_Zona, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Cidade_reload__RAND__) == 'function') Cidade_reload__RAND__();
				if(typeof(Bairro_reload__RAND__) == 'function') Bairro_reload__RAND__();
				if(typeof(Zona_reload__RAND__) == 'function') Zona_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Cidade_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Cidade-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Cidade__RAND__.value, t: 'Secao', f: 'Cidade' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Cidade"]').val(resp.results[0].id);
							$j('[id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }


							if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Secao', f: 'Cidade' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Cidade__RAND__.value = e.added.id;
				AppGini.current_Cidade__RAND__.text = e.added.text;
				$j('[name="Cidade"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }


				if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
			});

			if(!$j("#Cidade-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Cidade__RAND__.value, t: 'Secao', f: 'Cidade' },
					success: function(resp) {
						$j('[name="Cidade"]').val(resp.results[0].id);
						$j('[id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

						if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Cidade__RAND__.value, t: 'Secao', f: 'Cidade' },
				success: function(resp) {
					$j('[id=Cidade-container__RAND__], [id=Cidade-container-readonly__RAND__]').html('<span class="match-text" id="Cidade-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

					if(typeof(Cidade_update_autofills__RAND__) == 'function') Cidade_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Bairro_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Bairro-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Bairro__RAND__.value, t: 'Secao', f: 'Bairro' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Bairro"]').val(resp.results[0].id);
							$j('[id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }


							if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Secao', f: 'Bairro' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Bairro__RAND__.value = e.added.id;
				AppGini.current_Bairro__RAND__.text = e.added.text;
				$j('[name="Bairro"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }


				if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
			});

			if(!$j("#Bairro-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Bairro__RAND__.value, t: 'Secao', f: 'Bairro' },
					success: function(resp) {
						$j('[name="Bairro"]').val(resp.results[0].id);
						$j('[id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }

						if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Bairro__RAND__.value, t: 'Secao', f: 'Bairro' },
				success: function(resp) {
					$j('[id=Bairro-container__RAND__], [id=Bairro-container-readonly__RAND__]').html('<span class="match-text" id="Bairro-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Bairro_view_parent]').hide(); } else { $j('.btn[id=Bairro_view_parent]').show(); }

					if(typeof(Bairro_update_autofills__RAND__) == 'function') Bairro_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Zona_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Zona-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Zona__RAND__.value, t: 'Secao', f: 'Zona' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Zona"]').val(resp.results[0].id);
							$j('[id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }


							if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Secao', f: 'Zona' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Zona__RAND__.value = e.added.id;
				AppGini.current_Zona__RAND__.text = e.added.text;
				$j('[name="Zona"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }


				if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
			});

			if(!$j("#Zona-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Zona__RAND__.value, t: 'Secao', f: 'Zona' },
					success: function(resp) {
						$j('[name="Zona"]').val(resp.results[0].id);
						$j('[id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

						if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Zona__RAND__.value, t: 'Secao', f: 'Zona' },
				success: function(resp) {
					$j('[id=Zona-container__RAND__], [id=Zona-container-readonly__RAND__]').html('<span class="match-text" id="Zona-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Zona_view_parent]').hide(); } else { $j('.btn[id=Zona_view_parent]').show(); }

					if(typeof(Zona_update_autofills__RAND__) == 'function') Zona_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Secao_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Secao_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Secao_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Secao_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Secao_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Numero').replaceWith('<div class=\"form-control-static\" id=\"Numero\">' + (jQuery('#Numero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Cidade').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Cidade_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Bairro').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Bairro_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Zona').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Zona_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Endereco').replaceWith('<div class=\"form-control-static\" id=\"Endereco\">' + (jQuery('#Endereco').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Local').replaceWith('<div class=\"form-control-static\" id=\"Local\">' + (jQuery('#Local').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Eleitores').replaceWith('<div class=\"form-control-static\" id=\"Eleitores\">' + (jQuery('#Eleitores').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Cidade)%%>', $combo_Cidade->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Cidade)%%>', $combo_Cidade->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Cidade)%%>', urlencode($combo_Cidade->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Bairro)%%>', $combo_Bairro->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Bairro)%%>', $combo_Bairro->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Bairro)%%>', urlencode($combo_Bairro->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Zona)%%>', $combo_Zona->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Zona)%%>', $combo_Zona->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Zona)%%>', urlencode($combo_Zona->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Cidade' => ['Zona', 'Cidade'], 'Bairro' => ['Bairro', 'Bairro'], 'Zona' => ['Zona', 'Zona'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Numero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Cidade)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Bairro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Zona)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Endereco)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Local)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Eleitores)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', safe_html($urow['Numero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', html_attr($row['Numero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode($urow['Numero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Cidade)%%>', safe_html($urow['Cidade']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Cidade)%%>', html_attr($row['Cidade']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cidade)%%>', urlencode($urow['Cidade']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Bairro)%%>', safe_html($urow['Bairro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Bairro)%%>', html_attr($row['Bairro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Bairro)%%>', urlencode($urow['Bairro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Zona)%%>', safe_html($urow['Zona']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Zona)%%>', html_attr($row['Zona']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Zona)%%>', urlencode($urow['Zona']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Endereco)%%>', safe_html($urow['Endereco']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Endereco)%%>', html_attr($row['Endereco']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Endereco)%%>', urlencode($urow['Endereco']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Local)%%>', safe_html($urow['Local']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Local)%%>', html_attr($row['Local']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Local)%%>', urlencode($urow['Local']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Eleitores)%%>', safe_html($urow['Eleitores']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Eleitores)%%>', html_attr($row['Eleitores']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Eleitores)%%>', urlencode($urow['Eleitores']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Numero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Cidade)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Cidade)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Bairro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Bairro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Zona)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Zona)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Endereco)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Endereco)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Local)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Local)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Eleitores)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Eleitores)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Secao');
	if($hasSelectedId) {
		$jdata = get_joined_record('Secao', $selectedId);
		if($jdata === false) $jdata = get_defaults('Secao');
		$rdata = $row;
	}
	$templateCode .= loadView('Secao-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Secao_dv
	if(function_exists('Secao_dv')) {
		$args = [];
		Secao_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}