<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Secao.php');
	include_once(__DIR__ . '/Secao_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Secao');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Secao';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Secao`.`id`" => "id",
		"`Secao`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona2`.`Numero`), CONCAT_WS('',   `Zona2`.`Numero`), '') /* Zona */" => "Zona",
		"`Secao`.`Endereco`" => "Endereco",
		"`Secao`.`Local`" => "Local",
		"`Secao`.`Eleitores`" => "Eleitores",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Secao`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Bairro1`.`Nome`',
		5 => '`Zona2`.`Numero`',
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Secao`.`id`" => "id",
		"`Secao`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona2`.`Numero`), CONCAT_WS('',   `Zona2`.`Numero`), '') /* Zona */" => "Zona",
		"`Secao`.`Endereco`" => "Endereco",
		"`Secao`.`Local`" => "Local",
		"`Secao`.`Eleitores`" => "Eleitores",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Secao`.`id`" => "ID",
		"`Secao`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona2`.`Numero`), CONCAT_WS('',   `Zona2`.`Numero`), '') /* Zona */" => "Zona",
		"`Secao`.`Endereco`" => "Endere&#231;o",
		"`Secao`.`Local`" => "Local",
		"`Secao`.`Eleitores`" => "Eleitores",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Secao`.`id`" => "id",
		"`Secao`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Cidade */" => "Cidade",
		"IF(    CHAR_LENGTH(`Bairro1`.`Nome`), CONCAT_WS('',   `Bairro1`.`Nome`), '') /* Bairro */" => "Bairro",
		"IF(    CHAR_LENGTH(`Zona2`.`Numero`), CONCAT_WS('',   `Zona2`.`Numero`), '') /* Zona */" => "Zona",
		"`Secao`.`Endereco`" => "Endereco",
		"`Secao`.`Local`" => "Local",
		"`Secao`.`Eleitores`" => "Eleitores",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Cidade' => 'Cidade', 'Bairro' => 'Bairro', 'Zona' => 'Zona', ];

	$x->QueryFrom = "`Secao` LEFT JOIN `Zona` as Zona1 ON `Zona1`.`id`=`Secao`.`Cidade` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona1`.`Municipio` LEFT JOIN `Bairro` as Bairro1 ON `Bairro1`.`Id`=`Secao`.`Bairro` LEFT JOIN `Zona` as Zona2 ON `Zona2`.`id`=`Secao`.`Zona` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Secao_view.php';
	$x->TableTitle = 'Se&#231;&#227;o Eleitoral';
	$x->TableIcon = 'resources/table_icons/routing_turn_left_crossroads.png';
	$x->PrimaryKey = '`Secao`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Numero', 'Cidade', 'Bairro', 'Zona', 'Endere&#231;o', 'Local', 'Eleitores', ];
	$x->ColFieldName = ['Numero', 'Cidade', 'Bairro', 'Zona', 'Endereco', 'Local', 'Eleitores', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Secao_templateTV.html';
	$x->SelectedTemplate = 'templates/Secao_templateTVS.html';
	$x->TemplateDV = 'templates/Secao_templateDV.html';
	$x->TemplateDVP = 'templates/Secao_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Secao_init
	$render = true;
	if(function_exists('Secao_init')) {
		$args = [];
		$render = Secao_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Secao_header
	$headerCode = '';
	if(function_exists('Secao_header')) {
		$args = [];
		$headerCode = Secao_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Secao_footer
	$footerCode = '';
	if(function_exists('Secao_footer')) {
		$args = [];
		$footerCode = Secao_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
