<?php

// Data functions (insert, update, delete, form) for table Zona

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function Zona_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Zona');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Numero' => Request::val('Numero', ''),
		'Estado' => Request::lookup('Estado', ''),
		'Municipio' => Request::lookup('Municipio', ''),
	];

	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Estado'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Municipio'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Munic&#237;pio': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Zona_before_insert
	if(function_exists('Zona_before_insert')) {
		$args = [];
		if(!Zona_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Zona', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Zona', $recID, calculated_fields()['Zona']);

	// hook: Zona_after_insert
	if(function_exists('Zona_after_insert')) {
		$res = sql("SELECT * FROM `Zona` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Zona_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('Zona', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Zona_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Zona_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Zona_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Zona', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Zona_before_delete
	if(function_exists('Zona_before_delete')) {
		$args = [];
		if(!Zona_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: Eleitores
	$res = sql("SELECT `id` FROM `Zona` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Eleitores` WHERE `Zona`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Eleitores', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Secao
	$res = sql("SELECT `id` FROM `Zona` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Secao` WHERE `Cidade`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Secao', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Secao', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: Secao
	$res = sql("SELECT `id` FROM `Zona` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `Secao` WHERE `Zona`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Secao', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'Secao', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Zona_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Zona` WHERE `id`='{$selected_id}'", $eo);

	// hook: Zona_after_delete
	if(function_exists('Zona_after_delete')) {
		$args = [];
		Zona_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Zona' AND `pkValue`='{$selected_id}'", $eo);
}

function Zona_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Zona', $selected_id, 'edit')) return false;

	$data = [
		'Numero' => Request::val('Numero', ''),
		'Estado' => Request::lookup('Estado', ''),
		'Municipio' => Request::lookup('Municipio', ''),
	];

	if($data['Numero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Estado'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Municipio'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Munic&#237;pio': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Zona', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Zona_before_update
	if(function_exists('Zona_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Zona_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Zona', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Zona_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Zona', $data['selectedID'], calculated_fields()['Zona']);

	// hook: Zona_after_update
	if(function_exists('Zona_after_update')) {
		$res = sql("SELECT * FROM `Zona` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Zona_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('Zona', $selected_id);
}

function Zona_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Zona');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('Zona', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('Zona', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('Zona', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_Estado = Request::val('filterer_Estado');
	$filterer_Municipio = Request::val('filterer_Municipio');

	// populate filterers, starting from children to grand-parents
	if($filterer_Municipio && !$filterer_Estado) $filterer_Estado = sqlValue("select Estado from Municipios where Id='" . makeSafe($filterer_Municipio) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Estado
	$combo_Estado = new DataCombo;
	// combobox: Municipio, filterable by: Estado
	$combo_Municipio = new DataCombo;

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `Zona` WHERE `id`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Zona_view.php', false);
		}
		$combo_Estado->SelectedData = $row['Estado'];
		$combo_Municipio->SelectedData = $row['Municipio'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Estado->SelectedData = $filterer_Estado;
		$combo_Municipio->SelectedData = $filterer_Municipio;
	}
	$combo_Estado->HTML = '<span id="Estado-container' . $rnd1 . '"></span><input type="hidden" name="Estado" id="Estado' . $rnd1 . '" value="' . html_attr($combo_Estado->SelectedData) . '">';
	$combo_Estado->MatchText = '<span id="Estado-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Estado" id="Estado' . $rnd1 . '" value="' . html_attr($combo_Estado->SelectedData) . '">';
	$combo_Municipio->HTML = '<span id="Municipio-container' . $rnd1 . '"></span><input type="hidden" name="Municipio" id="Municipio' . $rnd1 . '" value="' . html_attr($combo_Municipio->SelectedData) . '">';
	$combo_Municipio->MatchText = '<span id="Municipio-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Municipio" id="Municipio' . $rnd1 . '" value="' . html_attr($combo_Municipio->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Estado__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Estado'] : htmlspecialchars($filterer_Estado, ENT_QUOTES)); ?>"};
		AppGini.current_Municipio__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['Municipio'] : htmlspecialchars($filterer_Municipio, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Estado_reload__RAND__) == 'function') Estado_reload__RAND__();
				<?php echo (!$allowUpdate || $dvprint ? 'if(typeof(Municipio_reload__RAND__) == \'function\') Municipio_reload__RAND__(AppGini.current_Estado__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Estado_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#Estado-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Estado__RAND__.value, t: 'Zona', f: 'Estado' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Estado"]').val(resp.results[0].id);
							$j('[id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Municipio_reload__RAND__) == 'function') Municipio_reload__RAND__(AppGini.current_Estado__RAND__.value);

							if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Zona', f: 'Estado' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Estado__RAND__.value = e.added.id;
				AppGini.current_Estado__RAND__.text = e.added.text;
				$j('[name="Estado"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Municipio_reload__RAND__) == 'function') Municipio_reload__RAND__(AppGini.current_Estado__RAND__.value);

				if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
			});

			if(!$j("#Estado-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Estado__RAND__.value, t: 'Zona', f: 'Estado' },
					success: function(resp) {
						$j('[name="Estado"]').val(resp.results[0].id);
						$j('[id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

						if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Estado__RAND__.value, t: 'Zona', f: 'Estado' },
				success: function(resp) {
					$j('[id=Estado-container__RAND__], [id=Estado-container-readonly__RAND__]').html('<span class="match-text" id="Estado-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Estados_view_parent]').hide(); } else { $j('.btn[id=Estados_view_parent]').show(); }

					if(typeof(Estado_update_autofills__RAND__) == 'function') Estado_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Municipio_reload__RAND__(filterer_Estado) {
		<?php if($fieldsAreEditable) { ?>

			$j("#Municipio-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_Estado: filterer_Estado, id: AppGini.current_Municipio__RAND__.value, t: 'Zona', f: 'Municipio' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Municipio"]').val(resp.results[0].id);
							$j('[id=Municipio-container-readonly__RAND__]').html('<span class="match-text" id="Municipio-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }


							if(typeof(Municipio_update_autofills__RAND__) == 'function') Municipio_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_Estado: filterer_Estado, s: term, p: page, t: 'Zona', f: 'Municipio' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Municipio__RAND__.value = e.added.id;
				AppGini.current_Municipio__RAND__.text = e.added.text;
				$j('[name="Municipio"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }


				if(typeof(Municipio_update_autofills__RAND__) == 'function') Municipio_update_autofills__RAND__();
			});

			if(!$j("#Municipio-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Municipio__RAND__.value, t: 'Zona', f: 'Municipio' },
					success: function(resp) {
						$j('[name="Municipio"]').val(resp.results[0].id);
						$j('[id=Municipio-container-readonly__RAND__]').html('<span class="match-text" id="Municipio-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

						if(typeof(Municipio_update_autofills__RAND__) == 'function') Municipio_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Municipio__RAND__.value, t: 'Zona', f: 'Municipio' },
				success: function(resp) {
					$j('[id=Municipio-container__RAND__], [id=Municipio-container-readonly__RAND__]').html('<span class="match-text" id="Municipio-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Municipios_view_parent]').hide(); } else { $j('.btn[id=Municipios_view_parent]').show(); }

					if(typeof(Municipio_update_autofills__RAND__) == 'function') Municipio_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/Zona_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/Zona_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalhes', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Zona_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Zona_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Zona_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Numero').replaceWith('<div class=\"form-control-static\" id=\"Numero\">' + (jQuery('#Numero').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Estado').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Estado_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Municipio').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Municipio_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Estado)%%>', $combo_Estado->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Estado)%%>', $combo_Estado->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Estado)%%>', urlencode($combo_Estado->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Municipio)%%>', $combo_Municipio->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Municipio)%%>', $combo_Municipio->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Municipio)%%>', urlencode($combo_Municipio->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Estado' => ['Estados', 'Estado'], 'Municipio' => ['Municipios', 'Munic&#237;pio'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Numero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Estado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Municipio)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', safe_html($urow['Numero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Numero)%%>', html_attr($row['Numero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode($urow['Numero']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Estado)%%>', safe_html($urow['Estado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Estado)%%>', html_attr($row['Estado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado)%%>', urlencode($urow['Estado']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Municipio)%%>', safe_html($urow['Municipio']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Municipio)%%>', html_attr($row['Municipio']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Municipio)%%>', urlencode($urow['Municipio']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Numero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Numero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Estado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Municipio)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Municipio)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Zona');
	if($hasSelectedId) {
		$jdata = get_joined_record('Zona', $selectedId);
		if($jdata === false) $jdata = get_defaults('Zona');
		$rdata = $row;
	}
	$templateCode .= loadView('Zona-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Zona_dv
	if(function_exists('Zona_dv')) {
		$args = [];
		Zona_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}