<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Zona.php');
	include_once(__DIR__ . '/Zona_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Zona');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Zona';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Zona`.`id`" => "id",
		"`Zona`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Munic&#237;pio */" => "Municipio",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Zona`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Municipios1`.`Nome`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Zona`.`id`" => "id",
		"`Zona`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Munic&#237;pio */" => "Municipio",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Zona`.`id`" => "ID",
		"`Zona`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Munic&#237;pio */" => "Munic&#237;pio",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Zona`.`id`" => "id",
		"`Zona`.`Numero`" => "Numero",
		"IF(    CHAR_LENGTH(`Estados1`.`Nome`) || CHAR_LENGTH(`Estados1`.`Sigla`), CONCAT_WS('',   `Estados1`.`Nome`, '    -    ', `Estados1`.`Sigla`), '') /* Estado */" => "Estado",
		"IF(    CHAR_LENGTH(`Municipios1`.`Nome`), CONCAT_WS('',   `Municipios1`.`Nome`), '') /* Munic&#237;pio */" => "Municipio",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Estado' => 'Estado', 'Municipio' => 'Munic&#237;pio', ];

	$x->QueryFrom = "`Zona` LEFT JOIN `Estados` as Estados1 ON `Estados1`.`id`=`Zona`.`Estado` LEFT JOIN `Municipios` as Municipios1 ON `Municipios1`.`Id`=`Zona`.`Municipio` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->AllowAdminShowSQL = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Zona_view.php';
	$x->TableTitle = 'Zona Eleitoral';
	$x->TableIcon = 'resources/table_icons/radiolocator.png';
	$x->PrimaryKey = '`Zona`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Numero', 'Estado', 'Munic&#237;pio', ];
	$x->ColFieldName = ['Numero', 'Estado', 'Municipio', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Zona_templateTV.html';
	$x->SelectedTemplate = 'templates/Zona_templateTVS.html';
	$x->TemplateDV = 'templates/Zona_templateDV.html';
	$x->TemplateDVP = 'templates/Zona_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Zona_init
	$render = true;
	if(function_exists('Zona_init')) {
		$args = [];
		$render = Zona_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Zona_header
	$headerCode = '';
	if(function_exists('Zona_header')) {
		$args = [];
		$headerCode = Zona_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Zona_footer
	$footerCode = '';
	if(function_exists('Zona_footer')) {
		$args = [];
		$footerCode = Zona_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
